### ISSUE TITLE
Building error when trying to create ast representation of module 'demo_CameraAndImages'

### ISSUE THREAD

**Issue by photoniker** [pylint-dev/pylint#10124]
### Bug description

```python
Got a F0002 fatal error while checking https://github.com/itom-project/itom/blob/master/styles/stylesheets/qDarkStyleSheet/utils/scss.py 


"""Cameras and images
===================

This demo shows with the example of the ``DummyGrabber``
how you acquire an image and apply some filters."""

from itom import dataIO
from itom import dataObject
from itom import algorithms
from itom import liveImage
from itom import saveIDC
from itom import loadIDC
from itom import plot
# sphinx_gallery_thumbnail_path = '11_demos/_static/_thumb/demoCameraAndImages.png'

###############################################################################
# Initialize a ``DummyGrabber`` camera

cam = dataIO("DummyGrabber")
cam.setParam("bpp", 8)
# start camera (only once)
cam.startDevice()

# show live image of camera
liveImage(cam)

###############################################################################
# .. hint:: The live images tries to acquire and get up to 50 images per second
#     from the camera. If you want to acquire images by yourself in a script, you need
#     to stop the timer of the live images for a certain amount of time. After you are
#     done with your manual acquisition, you can restart the timer again.

currentStatus = cam.getAutoGrabbing()
print("Current value of auto grabbing property of the camera:", currentStatus)

cam.setAutoGrabbing(False)

###############################################################################
# Acquire 10 images in a list of dataObjects

result = []
d = dataObject()  # empty data object where the image should be put in

for i in range(0, 10):
    cam.acquire()
    cam.getVal(d)  # d is a shallow copy of the camera image
    result.append(d.copy())

###############################################################################
# Save the list of images to the **image1.idc** file (idc is a file format for the python pickle module)
saveIDC("image1.idc", {"result": result, "description": "sample 1"})

###############################################################################
# Load the list of images
loaded_objects = loadIDC("image1.idc")
result2 = loaded_objects["result"]

# plot the 3rd image from the list
plot(result2[2])

###############################################################################
# Acquire 10 images in an image stack
num = 10
sizex = cam.getParam("sizex")
sizey = cam.getParam("sizey")
bpp = cam.getParam("bpp")

if bpp == 8:
    d = dataObject([num, sizey, sizex], "uint8")
else:
    d = dataObject([num, sizey, sizex], "uint16")

for idx in range(num):
    cam.acquire()
    cam.copyVal(d[idx, :, :])  # partial deep copy into one part of the 3d object d

plot(d)

###############################################################################
# Calculate mean value of image stack in z-direction.
result_mean = dataObject()

algorithms.calcMeanZ(d, result_mean, ignoreInf=0, calcStd=0)
# result_mean is a 3d Object with [1 x sizey x sizex] dimensions.
# We squeeze it to get a 2D Object
result_mean = result_mean.squeeze()

result_mean.setTag("title", f"mean value of {num} acquisitions")
result_mean.axisUnits = ("px", "px")
result_mean.axisDescriptions = ("y", "x")
plot(result_mean)
###############################################################################
# .. image:: ../../_static/demoCameraAndImages_1.png
#    :width: 100%

###############################################################################
# Apply Gaussian filter onto the mean image.
result_filter = dataObject()
kernelVal = 9
algorithms.gaussianFilter(
    result_mean, result_filter, kernelx=kernelVal, kernely=kernelVal
)

###############################################################################
# Copy meta information from source ``dataObject``.
result_filter.copyMetaInfo(result_mean)
result_filter.setTag("title", f"Gaussian filter with kernel {kernelVal}")
plot(result_filter)
###############################################################################
# .. image:: ../../_static/demoCameraAndImages_2.png
#    :width: 100%

# reset the auto grabbing functionality of possibly connected live images
cam.setAutoGrabbing(currentStatus)

# end camera
cam.stopDevice()



pylint crashed with a ``AstroidBuildingError`` and with the following stacktrace:

Traceback (most recent call last):
  File "\.cache\pre-commit\repo34g03oxu\py_env-default\Lib\site-packages\astroid\manager.py", line 230, in file_from_module_name
    value = self._mod_file_cache[(modname, contextfile)]
            ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^
KeyError: ('itom', None)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "\.cache\pre-commit\repo34g03oxu\py_env-default\Lib\site-packages\pylint\lint\pylinter.py", line 874, in get_ast
    return MANAGER.ast_from_file(filepath, modname, source=True)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "\.cache\pre-commit\repo34g03oxu\py_env-default\Lib\site-packages\astroid\manager.py", line 102, in ast_from_file
    return AstroidBuilder(self).file_build(filepath, modname)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "\.cache\pre-commit\repo34g03oxu\py_env-default\Lib\site-packages\astroid\builder.py", line 134, in file_build
    return self._post_build(module, builder, encoding)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "\.cache\pre-commit\repo34g03oxu\py_env-default\Lib\site-packages\astroid\builder.py", line 156, in _post_build
    self.delayed_assattr(delayed)
  File "\.cache\pre-commit\repo34g03oxu\py_env-default\Lib\site-packages\astroid\builder.py", line 226, in delayed_assattr
    for inferred in node.expr.infer():
  File "\.cache\pre-commit\repo34g03oxu\py_env-default\Lib\site-packages\astroid\nodes\node_ng.py", line 168, in infer
    yield from self._infer(context=context, **kwargs)
  File "\.cache\pre-commit\repo34g03oxu\py_env-default\Lib\site-packages\astroid\decorators.py", line 136, in raise_if_nothing_inferred
    yield next(generator)
          ^^^^^^^^^^^^^^^
  File "\.cache\pre-commit\repo34g03oxu\py_env-default\Lib\site-packages\astroid\decorators.py", line 105, in wrapped
    for res in _func(node, context, **kwargs):
  File "\.cache\pre-commit\repo34g03oxu\py_env-default\Lib\site-packages\astroid\bases.py", line 134, in _infer_stmts
    for inf in stmt.infer(context=context):
  File "\.cache\pre-commit\repo34g03oxu\py_env-default\Lib\site-packages\astroid\nodes\node_ng.py", line 182, in infer
    for i, result in enumerate(generator):
  File "\.cache\pre-commit\repo34g03oxu\py_env-default\Lib\site-packages\astroid\decorators.py", line 136, in raise_if_nothing_inferred
    yield next(generator)
          ^^^^^^^^^^^^^^^
  File "\.cache\pre-commit\repo34g03oxu\py_env-default\Lib\site-packages\astroid\decorators.py", line 105, in wrapped
    for res in _func(node, context, **kwargs):
  File "\.cache\pre-commit\repo34g03oxu\py_env-default\Lib\site-packages\astroid\bases.py", line 134, in _infer_stmts
    for inf in stmt.infer(context=context):
  File "\.cache\pre-commit\repo34g03oxu\py_env-default\Lib\site-packages\astroid\nodes\node_ng.py", line 182, in infer
    for i, result in enumerate(generator):
  File "\.cache\pre-commit\repo34g03oxu\py_env-default\Lib\site-packages\astroid\decorators.py", line 136, in raise_if_nothing_inferred
    yield next(generator)
          ^^^^^^^^^^^^^^^
  File "\.cache\pre-commit\repo34g03oxu\py_env-default\Lib\site-packages\astroid\decorators.py", line 105, in wrapped
    for res in _func(node, context, **kwargs):
  File "\.cache\pre-commit\repo34g03oxu\py_env-default\Lib\site-packages\astroid\inference.py", line 236, in infer_call
    for callee in self.func.infer(context):
  File "\.cache\pre-commit\repo34g03oxu\py_env-default\Lib\site-packages\astroid\nodes\node_ng.py", line 182, in infer
    for i, result in enumerate(generator):
  File "\.cache\pre-commit\repo34g03oxu\py_env-default\Lib\site-packages\astroid\decorators.py", line 136, in raise_if_nothing_inferred
    yield next(generator)
          ^^^^^^^^^^^^^^^
  File "\.cache\pre-commit\repo34g03oxu\py_env-default\Lib\site-packages\astroid\decorators.py", line 105, in wrapped
    for res in _func(node, context, **kwargs):
  File "\.cache\pre-commit\repo34g03oxu\py_env-default\Lib\site-packages\astroid\inference.py", line 308, in infer_attribute
    for owner in self.expr.infer(context):
  File "\.cache\pre-commit\repo34g03oxu\py_env-default\Lib\site-packages\astroid\nodes\node_ng.py", line 182, in infer
    for i, result in enumerate(generator):
  File "\.cache\pre-commit\repo34g03oxu\py_env-default\Lib\site-packages\astroid\decorators.py", line 136, in raise_if_nothing_inferred
    yield next(generator)
          ^^^^^^^^^^^^^^^
  File "\.cache\pre-commit\repo34g03oxu\py_env-default\Lib\site-packages\astroid\decorators.py", line 105, in wrapped
    for res in _func(node, context, **kwargs):
  File "\.cache\pre-commit\repo34g03oxu\py_env-default\Lib\site-packages\astroid\bases.py", line 134, in _infer_stmts
    for inf in stmt.infer(context=context):
  File "\.cache\pre-commit\repo34g03oxu\py_env-default\Lib\site-packages\astroid\nodes\node_ng.py", line 182, in infer
    for i, result in enumerate(generator):
  File "\.cache\pre-commit\repo34g03oxu\py_env-default\Lib\site-packages\astroid\decorators.py", line 136, in raise_if_nothing_inferred
    yield next(generator)
          ^^^^^^^^^^^^^^^
  File "\.cache\pre-commit\repo34g03oxu\py_env-default\Lib\site-packages\astroid\decorators.py", line 105, in wrapped
    for res in _func(node, context, **kwargs):
  File "\.cache\pre-commit\repo34g03oxu\py_env-default\Lib\site-packages\astroid\bases.py", line 134, in _infer_stmts
    for inf in stmt.infer(context=context):
  File "\.cache\pre-commit\repo34g03oxu\py_env-default\Lib\site-packages\astroid\nodes\node_ng.py", line 182, in infer
    for i, result in enumerate(generator):
  File "\.cache\pre-commit\repo34g03oxu\py_env-default\Lib\site-packages\astroid\decorators.py", line 136, in raise_if_nothing_inferred
    yield next(generator)
          ^^^^^^^^^^^^^^^
  File "\.cache\pre-commit\repo34g03oxu\py_env-default\Lib\site-packages\astroid\decorators.py", line 105, in wrapped
    for res in _func(node, context, **kwargs):
  File "\.cache\pre-commit\repo34g03oxu\py_env-default\Lib\site-packages\astroid\inference.py", line 236, in infer_call
    for callee in self.func.infer(context):
  File "\.cache\pre-commit\repo34g03oxu\py_env-default\Lib\site-packages\astroid\nodes\node_ng.py", line 182, in infer
    for i, result in enumerate(generator):
  File "\.cache\pre-commit\repo34g03oxu\py_env-default\Lib\site-packages\astroid\decorators.py", line 136, in raise_if_nothing_inferred
    yield next(generator)
          ^^^^^^^^^^^^^^^
  File "\.cache\pre-commit\repo34g03oxu\py_env-default\Lib\site-packages\astroid\decorators.py", line 105, in wrapped
    for res in _func(node, context, **kwargs):
  File "\.cache\pre-commit\repo34g03oxu\py_env-default\Lib\site-packages\astroid\bases.py", line 134, in _infer_stmts
    for inf in stmt.infer(context=context):
  File "\.cache\pre-commit\repo34g03oxu\py_env-default\Lib\site-packages\astroid\nodes\node_ng.py", line 182, in infer
    for i, result in enumerate(generator):
  File "\.cache\pre-commit\repo34g03oxu\py_env-default\Lib\site-packages\astroid\decorators.py", line 136, in raise_if_nothing_inferred
    yield next(generator)
          ^^^^^^^^^^^^^^^
  File "\.cache\pre-commit\repo34g03oxu\py_env-default\Lib\site-packages\astroid\decorators.py", line 105, in wrapped
    for res in _func(node, context, **kwargs):
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "\.cache\pre-commit\repo34g03oxu\py_env-default\Lib\site-packages\astroid\inference.py", line 288, in infer_import_from
    module = self.do_import_module()
             ^^^^^^^^^^^^^^^^^^^^^^^
  File "\.cache\pre-commit\repo34g03oxu\py_env-default\Lib\site-packages\astroid\mixins.py", line 102, in do_import_module
    return mymodule.import_module(
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "\.cache\pre-commit\repo34g03oxu\py_env-default\Lib\site-packages\astroid\nodes\scoped_nodes\scoped_nodes.py", line 527, in import_module
    return AstroidManager().ast_from_module_name(absmodname)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "\.cache\pre-commit\repo34g03oxu\py_env-default\Lib\site-packages\astroid\manager.py", line 145, in ast_from_module_name
    found_spec = self.file_from_module_name(modname, context_file)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "\.cache\pre-commit\repo34g03oxu\py_env-default\Lib\site-packages\astroid\manager.py", line 233, in file_from_module_name
    value = file_info_from_modpath(
            ^^^^^^^^^^^^^^^^^^^^^^^
  File "\.cache\pre-commit\repo34g03oxu\py_env-default\Lib\site-packages\astroid\modutils.py", line 350, in file_info_from_modpath
    return _spec_from_modpath(modpath, path, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "\.cache\pre-commit\repo34g03oxu\py_env-default\Lib\site-packages\astroid\modutils.py", line 569, in _spec_from_modpath
    found_spec = spec.find_spec(modpath, path)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "\.cache\pre-commit\repo34g03oxu\py_env-default\Lib\site-packages\astroid\interpreter\_import\spec.py", line 368, in find_spec
    finder, spec = _find_spec_with_path(
                   ^^^^^^^^^^^^^^^^^^^^^
  File "\.cache\pre-commit\repo34g03oxu\py_env-default\Lib\site-packages\astroid\interpreter\_import\spec.py", line 332, in _find_spec_with_path
    spec = finder.find_module(modname, module_parts, processed, submodule_path)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "\.cache\pre-commit\repo34g03oxu\py_env-default\Lib\site-packages\astroid\interpreter\_import\spec.py", line 207, in find_module
    file_type, filename, path = _search_zip(module_parts, self._zipimporters)
                                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "\.cache\pre-commit\repo34g03oxu\py_env-default\Lib\site-packages\astroid\interpreter\_import\spec.py", line 313, in _search_zip
    found = importer.find_module(modpath[0])
            ^^^^^^^^^^^^^^^^^^^^
AttributeError: 'zipimporter' object has no attribute 'find_module'. Did you mean: 'load_module'?
```

### Configuration

```ini
- repo: https://github.com/pre-commit/mirrors-pylint
    rev: v3.0.0a5
    hooks:
      - id: pylint
        files: .*\.py$
        args: [
          "--max-line-length=120",
          "--disable=C0103,
          C0302,
          C0411,
          C0412,
          C0114,
          C0325,
          E0611,
          E0001,
          E0401,
          W0120,
          W0107,
          W0104,
          W0108,
          W0622,
          W1203,
          W1308,
          W0511,
          R0402,
          R1711,
          R0914,
          R0913,
          R0801,
          R0912,
          R0915,
          R0911,
          R0902,
          R0903,
          R0904,
          R1702",
          "--py-version=3.6"
        ]
```

### Command used

```shell
python -m pre_commit run --all-files pylint
```

### Pylint output

```python
styles\stylesheets\qDarkStyleSheet\utils\scss.py:1:0: F0002: styles\stylesheets\qDarkStyleSheet\utils\scss.py: Fatal error while checking 'styles\stylesheets\qDarkStyleSheet\utils\scss.py'. Please open an issue in our bug tracker so we address this. There is a pre-filled template that you can use in '\Local\pylint\pylint\Cache\pylint-crash-2024-12-09-14.txt'. (astroid-error)
```

### Expected behavior

no crash

### Pylint version

```shell
pylint 3.0.0a5 (got after pre_commit autoupdate)
```

### OS / Environment

Windows 10

### Additional dependencies

```python

```

**Comment by jacobtylerwalls** [comment]
Thanks for the report, but v3.0.0a5 is a pre-release of pylint over two years old, please upgrade to a released version.

**Comment by photoniker** [comment]
@jacobtylerwalls Thats the version I got after executing pre_commit autoupdate. 
If I change he version manually to the latest (3.3.2), I get the error: 

`error: pathspec 'v3.3.2' did not match any file(s) known to git`

**Comment by Pierre-Sassoulas** [comment]
My guess is that you need to change the pylint's URL in pre-commit from pycqa to pylint-dev.

**Comment by photoniker** [comment]
Thanks this helps!
