### ISSUE TITLE
Astroid crash with basic hydra configuration

### ISSUE THREAD

**Issue by alinafdima** [pylint-dev/pylint#10139]
Issue title:
Astroid crash with basic hydra configuration (running from VSCode)

### Bug description

When parsing the following ``a.py``:

```python
from dataclasses import dataclass
import hydra

@dataclass
class MyConfig:
    test: int = 0


@hydra.main(version_base=None, config_name="config")
def train(cfg: MyConfig) -> None:
    print(cfg)


if __name__ == "__main__":
    train()  

```

### Command used

```shell
pylint a.py
```

### Pylint output

<details open>
    <summary>
        pylint crashed with a ``AstroidError`` and with the following stacktrace:
    </summary>

```python
Traceback (most recent call last):
  File "<ENV_PATH>/lib/python3.11/site-packages/pylint/lint/pylinter.py", line 788, in _lint_file
    check_astroid_module(module)
  File "<ENV_PATH>/lib/python3.11/site-packages/pylint/lint/pylinter.py", line 1017, in check_astroid_module
    retval = self._check_astroid_module(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<ENV_PATH>/lib/python3.11/site-packages/pylint/lint/pylinter.py", line 1069, in _check_astroid_module
    walker.walk(node)
  File "<ENV_PATH>/lib/python3.11/site-packages/pylint/utils/ast_walker.py", line 94, in walk
    self.walk(child)
  File "<ENV_PATH>/lib/python3.11/site-packages/pylint/utils/ast_walker.py", line 94, in walk
    self.walk(child)
  File "<ENV_PATH>/lib/python3.11/site-packages/pylint/utils/ast_walker.py", line 94, in walk
    self.walk(child)
  File "<ENV_PATH>/lib/python3.11/site-packages/pylint/utils/ast_walker.py", line 91, in walk
    callback(astroid)
  File "<ENV_PATH>/lib/python3.11/site-packages/pylint/checkers/variables.py", line 1642, in visit_name
    self._loopvar_name(node)
  File "<ENV_PATH>/lib/python3.11/site-packages/pylint/checkers/variables.py", line 2550, in _loopvar_name
    if astmts[i].statement().parent_of(stmt) and not utils.in_for_else_branch(
       ^^^^^^^^^^^^^^^^^^^^^
  File "/home/<USER>/.vscode-server/extensions/ms-python.pylint-2024.0.0/bundled/libs/astroid/nodes/node_ng.py", line 297, in statement
    return self.parent.statement()
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/<USER>/.vscode-server/extensions/ms-python.pylint-2024.0.0/bundled/libs/astroid/nodes/scoped_nodes/scoped_nodes.py", line 414, in statement
    raise StatementMissing(target=self)
astroid.exceptions.StatementMissing: Statement not found on <Module.test_astroid_error l.0 at 0x7fede0c71c50>

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "<ENV_PATH>/lib/python3.11/site-packages/pylint/lint/pylinter.py", line 752, in _lint_files
    self._lint_file(fileitem, module, check_astroid_module)
  File "<ENV_PATH>/lib/python3.11/site-packages/pylint/lint/pylinter.py", line 790, in _lint_file
    raise astroid.AstroidError from e
astroid.exceptions.AstroidError

```

</details>

### Expected behavior

No crash.

### Pylint version

```shell
pylint 3.0.3
astroid 3.2.4
Python 3.11.7 | packaged by conda-forge | (main, Dec 23 2023, 14:43:09) [GCC 12.3.0]
```

### OS / Environment

linux (Linux)

**Comment by jacobtylerwalls** [comment]
pylint 3.0.3 is not compatible with astroid 3.2.4. Please upgrade to the latest.

https://github.com/pylint-dev/pylint/blob/1a5ffc1f447b77071ffe18a9c6836c09147ee2ed/pyproject.toml#L44
