### ISSUE TITLE
Crash when linting code using a cryptography module

### ISSUE THREAD

**Issue by mathiasertl** [pylint-dev/pylint#10148]
### Bug description

I'm getting a traceback when parsing trivial code using this cryptography module. This issue happens with astroid 3.3.7, but *not* with astroid 3.3.6!

When parsing the following ``a.py``:

```python
"""demo"""

from cryptography.hazmat.primitives.asymmetric import types

print(types.PublicKeyTypes)

```

### Command used

```shell
pylint a.py
```

### Pylint output

<details open>
    <summary>
        pylint crashed with a ``AstroidError`` and with the following stacktrace:
    </summary>

```python
Traceback (most recent call last):
  File "/home/mati/git/mati/django-ca/.venv/lib/python3.13/site-packages/pylint/lint/pylinter.py", line 788, in _lint_file
    check_astroid_module(module)
    ~~~~~~~~~~~~~~~~~~~~^^^^^^^^
  File "/home/mati/git/mati/django-ca/.venv/lib/python3.13/site-packages/pylint/lint/pylinter.py", line 1017, in check_astroid_module
    retval = self._check_astroid_module(
        ast_node, walker, rawcheckers, tokencheckers
    )
  File "/home/mati/git/mati/django-ca/.venv/lib/python3.13/site-packages/pylint/lint/pylinter.py", line 1069, in _check_astroid_module
    walker.walk(node)
    ~~~~~~~~~~~^^^^^^
  File "/home/mati/git/mati/django-ca/.venv/lib/python3.13/site-packages/pylint/utils/ast_walker.py", line 90, in walk
    self.walk(child)
    ~~~~~~~~~^^^^^^^
  File "/home/mati/git/mati/django-ca/.venv/lib/python3.13/site-packages/pylint/utils/ast_walker.py", line 87, in walk
    callback(astroid)
    ~~~~~~~~^^^^^^^^^
  File "/home/mati/git/mati/django-ca/.venv/lib/python3.13/site-packages/pylint/checkers/imports.py", line 578, in visit_importfrom
    self._add_imported_module(node, f"{imported_module.name}.{name}")
    ~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/mati/git/mati/django-ca/.venv/lib/python3.13/site-packages/pylint/checkers/imports.py", line 1054, in _add_imported_module
    importedmodname = astroid.modutils.get_module_part(importedmodname)
  File "/home/mati/git/mati/django-ca/.venv/lib/python3.13/site-packages/astroid/modutils.py", line 430, in get_module_part
    file_from_modpath(
    ~~~~~~~~~~~~~~~~~^
        parts[starti : i + 1], path=path, context_file=context_file
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "/home/mati/git/mati/django-ca/.venv/lib/python3.13/site-packages/astroid/modutils.py", line 325, in file_from_modpath
    return file_info_from_modpath(modpath, path, context_file).location
           ~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/mati/git/mati/django-ca/.venv/lib/python3.13/site-packages/astroid/modutils.py", line 376, in file_info_from_modpath
    return _spec_from_modpath(modpath, path, context)
  File "/home/mati/git/mati/django-ca/.venv/lib/python3.13/site-packages/astroid/modutils.py", line 631, in _spec_from_modpath
    found_spec = spec.find_spec(modpath, path)
  File "/home/mati/git/mati/django-ca/.venv/lib/python3.13/site-packages/astroid/interpreter/_import/spec.py", line 476, in find_spec
    return _find_spec(tuple(modpath), tuple(path) if path else None)
  File "/home/mati/git/mati/django-ca/.venv/lib/python3.13/site-packages/astroid/interpreter/_import/spec.py", line 492, in _find_spec
    finder, spec = _find_spec_with_path(
                   ~~~~~~~~~~~~~~~~~~~~^
        _path, modname, module_parts, processed, submodule_path or path
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "/home/mati/git/mati/django-ca/.venv/lib/python3.13/site-packages/astroid/interpreter/_import/spec.py", line 412, in _find_spec_with_path
    spec = finder_instance.find_module(
        modname, module_parts, processed, submodule_path
    )
  File "/home/mati/git/mati/django-ca/.venv/lib/python3.13/site-packages/astroid/interpreter/_import/spec.py", line 153, in find_module
    spec = importlib.util.find_spec(".".join((*processed, modname)))
  File "<frozen importlib.util>", line 111, in find_spec
ValueError: cryptography.hazmat.primitives.asymmetric.types.__spec__ is None

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/mati/git/mati/django-ca/.venv/lib/python3.13/site-packages/pylint/lint/pylinter.py", line 752, in _lint_files
    self._lint_file(fileitem, module, check_astroid_module)
    ~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/mati/git/mati/django-ca/.venv/lib/python3.13/site-packages/pylint/lint/pylinter.py", line 790, in _lint_file
    raise astroid.AstroidError from e
astroid.exceptions.AstroidError

```

</details>

### Expected behavior

No crash.

### Pylint version

```shell
pylint 3.3.2
astroid 3.3.7
Python 3.13.1 (main, Dec  6 2024, 18:40:43) [Clang 18.1.8 ]
```

### OS / Environment

linux (Linux)
python 3.13.1
astroid==3.3.7
cryptography==44.0.0
pylint==3.3.2

(not sure if relevant, probably not):

pylint-django==2.6.1
pylint-plugin-utils==0.8.2

**Comment by mathiasertl** [comment]
appologies, still had the wrong issue tracker open. Closing this and creating it in the astroid project.

**Comment by Pierre-Sassoulas** [comment]
Astroid issue : https://github.com/pylint-dev/astroid/issues/2662
