### ISSUE TITLE
Cannot create a consistent method resolution order for MROs

### ISSUE THREAD

**Issue by frot** [pylint-dev/pylint#6225]
### Bug description

Crash ``Cannot create a consistent method resolution order for MROs (type, object), (ABCMeta, type, object), (type, ABCMeta) of class <ClassDef.AbstractGuiStatusItem l.9 at 0x7fb1118c54e0>.``

```python
from abc import ABC, ABCMeta, abstractmethod
from PyQt5.QtCore import QObject

class GuiStatusItem(QObject):
    pass

class AbstractGuiStatusItem(type(GuiStatusItem), ABCMeta):
    pass

class Supervisor(GuiStatusItem, ABC, metaclass=AbstractGuiStatusItem):
    def method(self):
        pass

    @abstractmethod
    def abstr(self):
        pass

class SocSupervisor(Supervisor):
    def abstr(self):
        pass
```

Without the metaclass I get "TypeError: metaclass conflict" when running.
With the metaclass everything works fine and reports the following MRO:
`[<class '__main__.SocSupervisor'>, <class '__main__.Supervisor'>, <class '__main__.GuiStatusItem'>, <class 'PyQt5.QtCore.QObject'>, <class 'sip.wrapper'>, <class 'sip.simplewrapper'>, <class 'abc.ABC'>, <class 'object'>]`

### Command used

```shell
pylint pycrash.py
```

### Pylint output

```shell
pycrash.py:9:0: E0240: Inconsistent method resolution order for class 'AbstractGuiStatusItem' (inconsistent-mro)
Exception on node <ClassDef.Supervisor l.13 at 0x7f51dc5417b0> in file 'tmp/pycrash.py'
Traceback (most recent call last):
  File ".local/lib/python3.10/site-packages/pylint/utils/ast_walker.py", line 73, in walk
    callback(astroid)
  File ".local/lib/python3.10/site-packages/pylint/checkers/typecheck.py", line 943, in visit_classdef
    if _is_invalid_metaclass(metaclass):
  File ".local/lib/python3.10/site-packages/pylint/checkers/typecheck.py", line 666, in _is_invalid_metaclass
    mro = metaclass.mro()
  File ".local/lib/python3.10/site-packages/astroid/nodes/scoped_nodes/scoped_nodes.py", line 3084, in mro
    return self._compute_mro(context=context)
  File ".local/lib/python3.10/site-packages/astroid/nodes/scoped_nodes/scoped_nodes.py", line 3074, in _compute_mro
    return _c3_merge(unmerged_mro, self, context)
  File ".local/lib/python3.10/site-packages/astroid/nodes/scoped_nodes/scoped_nodes.py", line 97, in _c3_merge
    raise InconsistentMroError(
astroid.exceptions.InconsistentMroError: Cannot create a consistent method resolution order for MROs (type, object), (ABCMeta, type, object), (type, ABCMeta) of class <ClassDef.AbstractGuiStatusItem l.9 at 0x7f51dc5410c0>.
```

### Expected behavior

pylint not crashing

### Pylint version

```shell
pylint 2.13.5
astroid 2.11.2
Python 3.10.2 (main, Jan 15 2022, 19:56:27) [GCC 11.1.0]
```

### OS / Environment

Manjaro Linux

**Comment by jacobtylerwalls** [comment]
Thanks for the report. This was fixed and tested in #8699.
