### ISSUE TITLE
Crash while linting Copr code on Fedora 37

### ISSUE THREAD

**Issue by praiskup** [pylint-dev/pylint#7613]
### Bug description

pylint crashed with a ``AstroidError`` and with the following stacktrace:
```
Traceback (most recent call last):
  File "/usr/lib/python3.11/site-packages/pylint/lint/pylinter.py", line 727, in _check_file
    check_astroid_module(ast_node)
  File "/usr/lib/python3.11/site-packages/pylint/lint/pylinter.py", line 926, in check_astroid_module
    retval = self._check_astroid_module(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/pylint/lint/pylinter.py", line 976, in _check_astroid_module
    walker.walk(node)
  File "/usr/lib/python3.11/site-packages/pylint/utils/ast_walker.py", line 93, in walk
    self.walk(child)
  File "/usr/lib/python3.11/site-packages/pylint/utils/ast_walker.py", line 93, in walk
    self.walk(child)
  File "/usr/lib/python3.11/site-packages/pylint/utils/ast_walker.py", line 93, in walk
    self.walk(child)
  [Previous line repeated 1 more time] 
  File "/usr/lib/python3.11/site-packages/pylint/utils/ast_walker.py", line 90, in walk
    callback(astroid)
  File "/usr/lib/python3.11/site-packages/pylint/checkers/typecheck.py", line 1114, in visit_attribute
    attr_parent = attr_node.parent
                  ^^^^^^^^^^^^^^^^
AttributeError: 'str' object has no attribute 'parent'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/lib/python3.11/site-packages/pylint/lint/pylinter.py", line 684, in _check_files
    self._check_file(get_ast, check_astroid_module, file) 
  File "/usr/lib/python3.11/site-packages/pylint/lint/pylinter.py", line 729, in _check_file
    raise astroid.AstroidError from e
astroid.exceptions.AstroidError
```

### Command used

```shell
pylint coprs_frontend/coprs/__init__.py coprs_frontend/coprs/logic/builds_logic.py coprs_frontend/coprs/views/apiv3_ns/apiv3_builds.py coprs_frontend/coprs/views/coprs_ns/coprs_builds.py
```

### Pylint output

```shell
Exception on node <Attribute.exception l.938 at 0x7f43e7a5bb90> in file '/home/praiskup/rh/projects/copr/copr/frontend/coprs_frontend/coprs/logic/builds_logic.py'
Traceback (most recent call last):
  File "/usr/lib/python3.11/site-packages/pylint/utils/ast_walker.py", line 90, in walk
    callback(astroid)
  File "/usr/lib/python3.11/site-packages/pylint/checkers/typecheck.py", line 1114, in visit_attribute
    attr_parent = attr_node.parent
                  ^^^^^^^^^^^^^^^^
AttributeError: 'str' object has no attribute 'parent'
coprs_frontend/coprs/logic/builds_logic.py:1:0: F0002: coprs_frontend/coprs/logic/builds_logic.py: Fatal error while checking 'coprs_frontend/coprs/logic/builds_logic.py'. Please open an issue in our bug tracker so we address this. There is a pre-filled template that you can use in '/home/praiskup/.cache/pylint/pylint-crash-2022-10-12-15.txt'. (astroid-error)
```

### Expected behavior

Should not traceback.

### Pylint version

```shell
pylint-2.14.4-3.fc37.noarch
python3-astroid-2.12.10-1.fc37.noarch
python3-3.11.0~rc2-1.fc37.x86_64
```

### OS / Environment

Fedora 37

**Comment by praiskup** [comment]
Steps:
- git clone https://pagure.io/copr/copr.git
- cd copr/frontend
- pylint coprs_frontend/coprs/__init__.py coprs_frontend/coprs/logic/builds_logic.py coprs_frontend/coprs/views/apiv3_ns/apiv3_builds.py coprs_frontend/coprs/views/coprs_ns/coprs_builds.py

**Comment by DanielNoord** [comment]
This could also be caused with by the `copr` pylint plugin. I know we have had issues with that before.

Could you try disabling that plugin in the `pylintrc` and see if the crash still occurs?
