### ISSUE TITLE
pyreverse: invalid argument causes exception

### ISSUE THREAD

**Issue by dgutson** [pylint-dev/pylint#7851]
### Bug description

`pyreverse --version`
causes
```
Traceback (most recent call last):
  File "/home/daniel/.local/bin/pyreverse", line 8, in <module>
    sys.exit(run_pyreverse())
  File "/home/daniel/.local/lib/python3.10/site-packages/pylint/__init__.py", line 67, in run_pyreverse
    PyreverseRun(argv or sys.argv[1:])
  File "/home/daniel/.local/lib/python3.10/site-packages/pylint/pyreverse/main.py", line 229, in __init__
    sys.exit(self.run(args))
  File "/home/daniel/.local/lib/python3.10/site-packages/pylint/pyreverse/main.py", line 237, in run
    project = project_from_files(
  File "/home/daniel/.local/lib/python3.10/site-packages/pylint/pyreverse/inspector.py", line 328, in project_from_files
    fpath = astroid.modutils.file_from_modpath(something.split("."))
  File "/home/daniel/.local/lib/python3.10/site-packages/astroid/modutils.py", line 334, in file_from_modpath
    return file_info_from_modpath(modpath, path, context_file).location
  File "/home/daniel/.local/lib/python3.10/site-packages/astroid/modutils.py", line 384, in file_info_from_modpath
    return _spec_from_modpath(modpath, path, context)
  File "/home/daniel/.local/lib/python3.10/site-packages/astroid/modutils.py", line 596, in _spec_from_modpath
    found_spec = spec.find_spec(modpath, path)
  File "/home/daniel/.local/lib/python3.10/site-packages/astroid/interpreter/_import/spec.py", line 392, in find_spec
    finder, spec = _find_spec_with_path(
  File "/home/daniel/.local/lib/python3.10/site-packages/astroid/interpreter/_import/spec.py", line 361, in _find_spec_with_path
    raise ImportError(f"No module named {'.'.join(module_parts)}")
ImportError: No module named --version
```

BTW, please add `--version` ;)

CC @qequ 

### Command used

```shell
--version
```

### Pylint output

```shell
Traceback (most recent call last):
  File "/home/daniel/.local/bin/pyreverse", line 8, in <module>
    sys.exit(run_pyreverse())
  File "/home/daniel/.local/lib/python3.10/site-packages/pylint/__init__.py", line 67, in run_pyreverse
    PyreverseRun(argv or sys.argv[1:])
  File "/home/daniel/.local/lib/python3.10/site-packages/pylint/pyreverse/main.py", line 229, in __init__
    sys.exit(self.run(args))
  File "/home/daniel/.local/lib/python3.10/site-packages/pylint/pyreverse/main.py", line 237, in run
    project = project_from_files(
  File "/home/daniel/.local/lib/python3.10/site-packages/pylint/pyreverse/inspector.py", line 328, in project_from_files
    fpath = astroid.modutils.file_from_modpath(something.split("."))
  File "/home/daniel/.local/lib/python3.10/site-packages/astroid/modutils.py", line 334, in file_from_modpath
    return file_info_from_modpath(modpath, path, context_file).location
  File "/home/daniel/.local/lib/python3.10/site-packages/astroid/modutils.py", line 384, in file_info_from_modpath
    return _spec_from_modpath(modpath, path, context)
  File "/home/daniel/.local/lib/python3.10/site-packages/astroid/modutils.py", line 596, in _spec_from_modpath
    found_spec = spec.find_spec(modpath, path)
  File "/home/daniel/.local/lib/python3.10/site-packages/astroid/interpreter/_import/spec.py", line 392, in find_spec
    finder, spec = _find_spec_with_path(
  File "/home/daniel/.local/lib/python3.10/site-packages/astroid/interpreter/_import/spec.py", line 361, in _find_spec_with_path
    raise ImportError(f"No module named {'.'.join(module_parts)}")
ImportError: No module named --version
```
```


### Expected behavior

`Unrecognized option --version`

### Pylint version

```shell
pylint 2.15.3
astroid 2.12.10
Python 3.10.6 (main, Nov  2 2022, 18:53:38) [GCC 11.3.0]
```

I can't know pyreverse version!
```


### OS / Environment

wsl ubuntu 22.04

### Additional dependencies

_No response_

**Comment by mbyrnepr2** [comment]
Thanks @dgutson I can reproduce it.

**Comment by qequ** [comment]
@Pierre-Sassoulas please assign this to me

**Comment by dgutson** [comment]
Fixed in https://github.com/pylint-dev/pylint/pull/8257

**Comment by Pierre-Sassoulas** [comment]
Thank you for the clean up @dgutson :)
