### ISSUE TITLE
astroid exception error: Fatal error while checking 'c:\Users\ulisp\Documents\Computer\Projekte\djac22\launchpad\admin.py'.

### ISSUE THREAD

**Issue by ulispalthoff** [pylint-dev/pylint#8642]
### Bug description

The following or similar error is shown when opening any django project file in VSCode:

c:\Users\ulisp\Documents\Computer\Projekte\djac22\launchpad\admin.py: Fatal error while checking 'c:\Users\ulisp\Documents\Computer\Projekte\djac22\launchpad\admin.py'. Please open an issue in our bug tracker so we address this. There is a pre-filled template that you can use in 'C:\Users\ulisp\AppData\Local\pylint\pylint\Cache\pylint-crash-2023-05-01-07-59-51.txt'.

When parsing the following file:

```python
""" djac/launchpad/views.py
Shows the startpage with links to reports, and dashboards.
Provides views for various reports.
Most data entries are handled in the admin.
"""

from datetime import date, datetime
from operator import truediv
from django.core.exceptions import ObjectDoesNotExist
from django.contrib.auth.decorators import login_required
from django.shortcuts import render
from django.http import HttpResponse
from django.template import loader
from django.db.models import Q
from launchpad.models import Transaction
from journal.models import Journal, BankAccount
from book.models import BookData, BookDetail,\
    EbookDetail, EbookPrice, Price, BookPage, BookPrice, Detail, Isbn
from .forms import SalesperbookForm, BookSelectForm, SelectAccountForm, PeriodCurrencyForm
from .functions import bookfinancials, exchangerate, ispublished, royalties_per_book


@login_required(login_url='/admin/login/')
def index(request):
    """ Shows the startpage. """

    transaction_list = Transaction.objects.all()
    template = loader.get_template('launchpad/index.html')
    ctxt = {
        'transaction_list': transaction_list,
    }
    return HttpResponse(template.render(ctxt))


@login_required(login_url='/admin/login/')
def accountsbalance(request):
    """ Lists balance of our bank accounts in a given period,
        Shows entry form for account, currency and period,
        then shows a list of all received/paid items from journal.
    """

    createdate = datetime.now()
    account = '...'
    acct = '...'
    startdate = ''
    enddate = ''
    currency = 'USD'
    sum_received = 0
    sum_paid = 0
    balance = 0
    items = 0
    c_list = []

    if request.method == 'POST':
        form = SelectAccountForm(request.POST)
        if form.is_valid():
            acct = form.cleaned_data['account']
            account = BankAccount.objects.get(pk=acct).bank
            startdate = form.cleaned_data['startdate']
            enddate = form.cleaned_data['enddate']
            currency = form.cleaned_data['currency']
            inoutlist = Journal.objects.all()\
                .filter(account=acct)\
                .filter(dat__range=(startdate, enddate)).order_by('dat')
            items = len(inoutlist)
        #
        # Convert into accounting currency if necessary.
        # Data from inoutlist are copied to c_list, with all figures in the target currency.
        # c_list lists the instances of the dictionary in/out item.
        #
        c_list = []
        sum_received = 0
        sum_paid = 0
        for item in inoutlist:
            if item.code.xref >= 200:
                c_received = 0
                c_paid = float(item.amount) * \
                    float(exchangerate(item.curr, currency, item.dat))
            else:
                c_received = float(
                    item.amount) * float(exchangerate(item.curr, currency, item.dat))
                c_paid = 0
            c_item = {
                'c_dat': item.dat,
                'c_code': item.code.xref,
                'c_jid': item.id,
                'c_received': c_received,
                'c_paid': c_paid,
            }
            c_list.append(c_item)
            sum_received += c_received
            sum_paid += c_paid
            balance = sum_received - sum_paid

        ctxt = {
            'form': form,
            'bank': account,
            'acct': acct,
            'createdate': createdate,
            'startdate': startdate,
            'enddate': enddate,
            'currency': currency,
            'sum_received': sum_received,
            'sum_paid': sum_paid,
            'balance': balance,
            'items': items,
            'c_list': c_list,
        }
        return render(request, 'launchpad/accbal.html', ctxt)
    else:
        form = SelectAccountForm()
        ctxt = {
            'form': form,
            'bank': account,
            'acct': acct,
            'createdate': createdate,
            'startdate': startdate,
            'enddate': enddate,
            'currency': currency,
            'sum_received': sum_received,
            'sum_paid': sum_paid,
            'balance': balance,
            'items': items,
            'c_list': c_list,
        }
    return render(request, 'launchpad/accbal.html', ctxt)


@login_required(login_url='/admin/login/')
def bookdetails(request):
    """ New, after merging Details into BookData
    url: /bookdetails/
    Presents a page with informations about a specific book.
    Price-related data are not yet shown.
    """
    # data to prepopulate the page
    errmsg = ''
    book = ''
    isbn = '978-1-937570-xx-x'
    author = 'Author'
    title = 'Title'
    subtitle = '--'
    btype = '??'
    pub = '??'
    page_count = 0
    page_format = '??'
    spine_width = 0
    weight = 0
    imprint = '??'
    pages = "--"
    print_costs = 0
    comment = ''
    dists = []
#    eups = []

    form = BookSelectForm(request.POST)
    inits = {
        'form': form,
        'book': book,
        'errmsg': errmsg,
        'isbn': isbn,
        'author': author,
        'title': title,
        'subtitle': subtitle,
        'type': btype,
        'pub': pub,
        'page_count': page_count,
        'page_format': page_format,
        'spine_width': spine_width,
        'weight': weight,
        'pages': pages,
        'costs': print_costs,
        'comment': comment,
    }

    if request.method == 'POST':
        form = BookSelectForm(request.POST)
        if form.is_valid():
            cbook = form.cleaned_data['book']
            if BookData.objects.filter(dpnum=cbook).exists():
                data = BookData.objects.get(dpnum=cbook)
            else:
                inits['errmsg'] = "Please enter a valid book number."
                return render(request, 'launchpad/bookdetails.html', inits)
        btype = data.type.type
        pub_date = data.pub_date
        if pub_date <= date.today():
            pub = 'published ' + pub_date.isoformat()
        else:
            pub = 'not yet published'
        page_count = data.page_count
        page_format = data.page_format
        spine_width = data.spine_width
        weight = data.weight
        imprint = data.imprint
        print_costs = data.print_costs
        author_add = data.author_add
        comment = data.comment
#        author_curr = data.author.curr
        if BookPage.objects.filter(book__dpnum=cbook).exists():
            pages = BookPage.objects.filter(book__dpnum=cbook).values('url')
#            distributors = BookPage.objects.filter(
#            book__dpnum=cbook).values('distributor__name')
        if Price.objects.filter(book__dpnum=cbook).exists():
            prc = Price.objects.filter(book__dpnum=cbook)
            for item in prc:
                curr = item.curr
                prd = {
                    'dist': item.distributor.name,
                    'eup': item.eup,
                    'bsp': item.bsp,
                    'dsp': item.dsp,
                }
                dists.append(prd)

        ctxt = {
            'form': form,
            'book': cbook,
            'errmsg': errmsg,
            'isbn': data.isbn,
            'author': data.author_title,
            'title': data.title,
            'subtitle': data.subtitle,
            'type': btype,
            'pub': pub,
            'page_count': page_count,
            'page_format': page_format,
            'spine_width': spine_width,
            'weight': weight,
            'imprint': imprint,
            'costs': print_costs,
            'author_add': author_add,
            'curr': curr,
            'pages': pages,
            'dists': dists,
            'comment': comment,
        }
        return render(request, 'launchpad/bookdetails.html', ctxt)
    else:
        form = BookSelectForm(initial=inits)
    return render(request, 'launchpad/bookdetails.html', inits)


@login_required(login_url='/admin/login/')
def booklist1(request):
    """ list of all book projects """

    list_title = 'All book projects'
    book_list = BookData.objects.order_by('dpnum')
    bookitem_list = []
    for item in book_list:
        book = item.dpnum
        if book > '10000':
            isbn = item.isbn
            author = BookData.objects.get(dpnum=book).author_title
            title = BookData.objects.get(dpnum=book).title
            bookitem = {
                'bk': book,
                'isbn': isbn,
                'author': author,
                'title': title,
            }
            bookitem_list.append(bookitem)
    context = {
        'list_title': list_title,
        'bookitem_list': bookitem_list,
    }
    template = loader.get_template('launchpad/booklist1.html')
    return HttpResponse(template.render(context))


@login_required(login_url='/admin/login/')
def booklist2(request):
    """list of all printed books"""
    list_title = 'Published print books'
    pub_date = '?'
    book_list = BookData.objects.filter(type__id__lte=6).filter(type__id__gte=3)\
        .order_by('dpnum')
    bookitem_list = []
    for item in book_list:
        book = item.dpnum
#        published, pub_date = ispublished(book)
        if item.pub_date <= date.today():
            isbn = item.isbn
            author = BookData.objects.get(dpnum=book).author_title
            title = BookData.objects.get(dpnum=book).title
            bookitem = {
                'bk': book,
                'isbn': isbn,
                'author': author,
                'title': title,
                'pub_date': pub_date,
            }
            bookitem_list.append(bookitem)
    context = {
        'list_title': list_title,
        'bookitem_list': bookitem_list,
    }
    template = loader.get_template('launchpad/booklist2.html')
    return HttpResponse(template.render(context))


@login_required(login_url='/admin/login/')
def ebooklist(request):
    """list of all ebooks"""

    list_title = 'Published ebooks'
    ebks = BookData.objects.filter(type__id__gte=7).order_by('dpnum')
    book_list = []
    for ebk in ebks:
        bk_num = ebk.dpnum
        if Detail.objects.filter(book_id=ebk.id).exists():
            p_date = Detail.objects.get(book_id=ebk.id).pub_date
            isbn = ebk.isbn
            author = ebk.author_title
            title = ebk.title
            bformat = ebk.btype
            bookitem = {
                'bk': bk_num,
                'isbn': isbn,
                'author': author,
                'title': title,
                'format': bformat,
                'pub_date': p_date,
            }
            book_list.append(bookitem)
    context = {
        'list_title': list_title,
        'bookitem_list': book_list,
    }
    template = loader.get_template('launchpad/ebooklist.html')
    return HttpResponse(template.render(context))


def isbnallocation(request):
    """ Creates a table with books and associated ISBN
    """
    page_title = 'ISBN allocation'
    isbn_list = Isbn.objects.all()

    # create dictionary with ISBN, DP number, author, title
    isbn_alloc = []
    for entry in isbn_list:
        if len(BookData.objects.filter(isbn__i_s_b_n=entry.i_s_b_n)) == 1:
            abd = BookData.objects.get(isbn__i_s_b_n=entry.i_s_b_n)
            adpnum = abd.dpnum
            aauth = abd.author_title
            atitle = abd.title
        else:
            # for isbn records which do not belong to exactly 1 book
            adpnum = ''
            aauth = ''
            atitle = ''
        isbn_rec = {
            'isbn': entry.i_s_b_n,
            'adpnum': adpnum,
            'aauth': aauth,
            'atitle': atitle,
        }
        if (len(BookData.objects.filter(isbn__i_s_b_n=entry.i_s_b_n)) < 2)\
                and adpnum != '99999' and entry.i_s_b_n != '978-1-937570-xx-x':
            isbn_alloc.append(isbn_rec)
    ctxt = {
        'page_title': page_title,
        'isbn_alloc': isbn_alloc,
        'adpnum': adpnum,
        'aauth': aauth,
        'atitle': atitle,
    }
    return render(request, 'launchpad/isbnallocation.html', ctxt)


@login_required(login_url='/admin/login/')
def financials(request):
    """ Dignity Press dashboard
    not yet functional!
    """

    page_title = "Financial Summary"
    startdate = "2011-01-01"
    enddate = "2021-12-31"
    currency = "USD"
    total_sales = 0
    total_expenses = 0
    total_royalties = 0
    total_gp = 0
    form = PeriodCurrencyForm()
    context = {
        'form': form,
        'page_title': page_title,
        'startdate': startdate,
        'enddate': enddate,
        'currency': currency,
        'total_sales': total_sales,
        'total_expenses': total_expenses,
        'total_royalties': total_royalties,
        'total_gp': total_gp,
    }

    if request.method == 'POST':
        form = PeriodCurrencyForm(request.POST)
        if form.is_valid():
            currency = form.cleaned_data['currency']
            startdate = form.cleaned_data['startdate']
            enddate = form.cleaned_data['enddate']

        saleslist = Journal.objects.all().filter(dat__range=(startdate, enddate))\
            .filter(code__xref__lte=199)
        total_sales = 0
        for item in saleslist:
            total_sales += item.amount\
                * exchangerate(item.curr, currency, item.dat)
        expenselist = Journal.objects.all().filter(dat__range=(startdate, enddate))\
            .filter(code__xref__gte=200)
        total_expenses = 0
        for item in expenselist:
            total_expenses += item.amount * \
                exchangerate(item.curr, currency, item.dat)
        royaltieslist = Journal.objects.all().filter(dat__range=(startdate, enddate))\
            .filter(code__xref=250)
        total_royalties = 0
        for item in royaltieslist:
            total_royalties += item.amount * \
                exchangerate(item.curr, currency, item.dat)
        total_gp = total_sales - total_expenses

        context = {
            'form': form,
            'page_title': page_title,
            'startdate': startdate,
            'enddate': enddate,
            'currency': currency,
            'total_sales': total_sales,
            'total_expenses': total_expenses,
            'total_royalties': total_royalties,
            'total_gp': total_gp,
        }
        return render(request, 'launchpad/financials.html', context)
    else:
        form = PeriodCurrencyForm()
        context = {
            'form': form,
            'page_title': page_title,
            'startdate': startdate,
            'enddate': enddate,
            'currency': currency,
            'total_sales': total_sales,
            'total_expenses': total_expenses,
            'total_royalties': total_royalties,
            'total_gp': total_gp,
        }
    return render(request, 'launchpad/financials.html', context)


def pricelist(request):
    """ Shows table with end user prices per book and distributor.
        Template launchpad/pricelist.html
    """

    rows = []
#    list_title = 'Pricelist'
    prices = Price.objects.all().order_by('book')
    for prc in prices:
        table_row = {
            'dpnum': prc.book.dpnum,
            'isbn': prc.book.isbn,
            'author': prc.book.author_title[0:19],
            'title': prc.book.title[0:29],
            'dist': prc.distributor.name,
            'price': prc.eup,
            'curr': prc.curr,
        }
        rows.append(table_row)
    context = {
        'rows': rows,
    }
    # book_list = BookData.objects.filter(type__id__gte=3).order_by('dpnum')
    # bookitem_list = []
    # for item in book_list:
    #     book = item.dpnum
    #     published = ispublished(book)
    #     if published and book > '10000' and book < '80000':
    #         author = BookData.objects.get(dpnum=book).author_title
    #         title = BookData.objects.get(dpnum=book).title
    #         edition = BookData.objects.get(dpnum=book).type
    #         if BookPrice.objects.filter(book__dpnum=book).filter(curr='USD').exists():
    #             eupusd = BookPrice.objects.filter(
    #                 curr='USD').get(book__dpnum=book).eup
    #         if BookPrice.objects.filter(book__dpnum=book).filter(curr='EUR').exists():
    #             eupeur = BookPrice.objects.filter(
    #                 curr='EUR').get(book__dpnum=book).eup
    #         if BookPrice.objects.filter(book__dpnum=book).filter(curr='GBP').exists():
    #             eupgbp = BookPrice.objects.filter(
    #                 curr='GBP').get(book__dpnum=book).eup
    #         bookitem = {
    #             'bk': book,
    #             'author': author,
    #             'title': title,
    #             'ed': edition,
    #             'eupusd': eupusd,
    #             'eupeur': eupeur,
    #             'eupgbp': eupgbp,
    #         }
    #         bookitem_list.append(bookitem)
    #     context = {
    #         'list_title': list_title,
    #         'bookitem_list': bookitem_list,
    #     }
    return render(request, 'launchpad/pricelist.html', context)


@login_required(login_url='/admin/login/')
def royalties(request):
    """ Work in Progress! Table with royalties due and paid for all books.

    Template launchpad/royalties.html
    Royalties are calculated from journal entries, as for report "Sales per book".
    This calculation should be separated in a function for re-use, also in report 'Total Sales'!
    """

    # initialization of variables
    list_title = 'Summary of Due/Paid Royalties'
    currency = 'USD'
    bookitem_list = []
    diff = 0
    paid = 0
    allbooksdue = 0
    allbookspaid = 0

    book_list = BookData.objects.all().order_by('dpnum')
    for item in book_list:
#        published, p_date = ispublished(item)
        booknr = item.dpnum
        author = item.author_title
        title = item.title

    # Calculation of due royalties per book, all periods
        due = royalties_per_book(booknr, '2000-01-01', '2099-12-31', 'USD')

    # Retrieve all payments from journal, transaction code 250.
    # If there exist several payments, the sum is needed.
        paid = 0
        payments = Journal.objects.filter(
            book__dpnum=booknr).filter(Q(code__xref=250))
        for payitem in payments:
            # convert to USD, where needed
            pay = payitem.amount * \
                exchangerate(payitem.curr, 'USD', payitem.dat)
            paid = paid + pay
        diff = due - paid
        bookitem = {
            'bk': booknr,
            'author': author,
            'title': title,
            'due': due,
            'paid': paid,
            'diff': diff,
        }
        bookitem_list.append(bookitem)
        allbooksdue = allbooksdue + due
        allbookspaid = allbookspaid + paid
        allbooksdiff = allbooksdue - allbookspaid
    context = {
        'list_title': list_title,
        'currency': currency,
        'books': bookitem_list,
        'allbooksdue': allbooksdue,
        'allbookspaid': allbookspaid,
        'allbooksdiff': allbooksdiff,
    }
    return render(request, 'launchpad/royalties.html', context)


@login_required(login_url='/admin/login/')
def sales(request):
    """ Shows table with sales for all books, for a given period.
    Template launchpad/sales.html
    Sales are calculated from journal entries, same as for report "Sales per book".
    This calculation should be separated in a function for re-use, e.g. in report 'Royalties'!
    """

    currency = 'USD'
    external_only = False
    bookitem_list = []
    total_books = 0
    total_revenue = 0
    total_cogs = 0
    total_profit = 0
    total_royalties = 0
    total_dp_share = 0

    if request.method == 'POST':
        errmsg = 'Please enter: '
        form = PeriodCurrencyForm(request.POST)
        if form.is_valid():
            startdate = form.cleaned_data['startdate']
            enddate = form.cleaned_data['enddate']
            currency = form.cleaned_data['currency']
            if startdate < enddate:
                book_list = BookData.objects.filter(type__id__lte=6).\
                    filter(type__id__gte=3).order_by('dpnum')
                bookitem_list = []
                total_books = 0
                total_revenue = 0
                total_cogs = 0
                total_profit = 0
                total_royalties = 0
                total_dp_share = 0
                for item in book_list:
#                    published, p_date = ispublished(item.dpnum)
                    book = item.dpnum
                    if (book < '80000') and (item.pub_date <= date.today()):
                        bofi = bookfinancials(
                            book, startdate, enddate, currency, external_only)
                        _, sum_books, sum_revenue, sum_cogs, profit, roy = bofi
                        dp_share = profit - roy
                        bookitem = {
                            'book': book,
                            'n_books': sum_books,
                            'revenue': sum_revenue,
                            'cogs': sum_cogs,
                            'profit': profit,
                            'royalties': roy,
                            'dp_share': dp_share,
                        }
                        bookitem_list.append(bookitem)
                        total_books += sum_books
                        total_revenue += sum_revenue
                        total_cogs += sum_cogs
                        total_profit += profit
                        total_royalties += roy
                        total_dp_share += dp_share
                    context = {
                        'errmsg': errmsg,
                        'form': form,
                        'list_title': 'Sales',
                        'bookitem_list': bookitem_list,
                        'currency': currency,
                        'total_books': total_books,
                        'total_revenue': total_revenue,
                        'total_cogs': total_cogs,
                        'total_profit': total_profit,
                        'total_royalties': total_royalties,
                        'total_dp_share': total_dp_share,
                    }
                return render(request, 'launchpad/sales.html', context)
            else:
                # startdate is later than enddate
                errmsg = 'Please correct: start date must be before end date.'
                form = PeriodCurrencyForm()
                context = {
                    'errmsg': errmsg,
                    'form': form,
                    'list_title': 'Sales',
                    'bookitem_list': bookitem_list,
                    'currency': currency,
                    'total_books': total_books,
                    'total_revenue': total_revenue,
                    'total_cogs': total_cogs,
                    'total_profit': total_profit,
                    'total_royalties': total_royalties,
                    'total_dp_share': total_dp_share,
                }
                return render(request, 'launchpad/sales.html', context)

        else:
            errmsg = 'Please correct:'
            context = {
                'errmsg': errmsg,
                'form': form,
                'list_title': 'Sales',
                'bookitem_list': bookitem_list,
                'currency': currency,
                'total_books': total_books,
                'total_revenue': total_revenue,
                'total_cogs': total_cogs,
                'total_profit': total_profit,
                'total_royalties': total_royalties,
                'total_dp_share': total_dp_share,
            }
    else:
        # first time rendering, or form is not valid: GET request
        form = PeriodCurrencyForm()
        errmsg = 'Please enter:'
        context = {
            'errmsg': errmsg,
            'form': form,
            'list_title': 'Sales',
            'bookitem_list': bookitem_list,
            'currency': currency,
            'total_books': total_books,
            'total_revenue': total_revenue,
            'total_cogs': total_cogs,
            'total_profit': total_profit,
            'total_royalties': total_royalties,
            'total_dp_share': total_dp_share,
        }
    return render(request, 'launchpad/sales.html', context)


@login_required(login_url='/admin/login/')
def salesperbook(request):
    """ Lists sales for a book in a given period

    Shows entry form for the book-id, period, then shows a list of all sales items from journal.
    """

    form = SalesperbookForm()
    # data to prepopulate the page
    createdate = date.today().isoformat()
    book = '12345'
    startdate = '2017-01-01'
    enddate = date.today().isoformat()
    currency = 'USD'
    errmsg = 'Please enter:'
    external_only = False
    external = ''
    isbn = '978-1-937570-xx-x'
    author = '...'
    title = '...'
    s_list = []
    items = 0
    sum_books = 0
    sum_revenue = 0
    sum_cogs = 0
    roy = 0
    profit = 0

    context = {
        'form': form,
        'errmsg': errmsg,
        'external': external,
        'book': book,
        'createdate': createdate,
        'startdate': startdate,
        'enddate': enddate,
        'currency': currency,
        'isbn': isbn,
        'author': author,
        'title': title,
        's_list': s_list,
        'items': items,
        'sum_books': sum_books,
        'sum_revenue': sum_revenue,
        'sum_cogs': sum_cogs,
        'royalties': roy,
        'profit': profit,
    }
    if request.method == 'POST':
        form = SalesperbookForm(request.POST)
        if form.is_valid():
            book = form.cleaned_data['book']
            if BookData.objects.filter(dpnum=book).exists():
                startdate = form.cleaned_data['startdate']
                enddate = form.cleaned_data['enddate']
                currency = form.cleaned_data['currency']
                isbn = BookData.objects.get(dpnum=book).isbn
                author = BookData.objects.get(dpnum=book).author_title
                title = BookData.objects.get(dpnum=book).title
                external_only = form.cleaned_data['external_only']
                bofi = bookfinancials(
                    book, startdate, enddate, currency, external_only)
                s_list, sum_books, sum_revenue, sum_cogs, profit, roy = bofi
                context = {
                    'form': form,
                    'errmsg': errmsg,
                    'external': external,
                    'book': book,
                    'createdate': createdate,
                    'startdate': startdate,
                    'enddate': enddate,
                    'currency': currency,
                    'isbn': isbn,
                    'author': author,
                    'title': title,
                    's_list': s_list,
                    'items': len(s_list),
                    'sum_books': sum_books,
                    'sum_revenue': sum_revenue,
                    'sum_cogs': sum_cogs,
                    'royalties': roy,
                    'profit': profit,
                }
                return render(request, 'launchpad/sales1.html', context)
            else:
                errmsg = 'Enter a valid number, please!'
                context = {
                    'form': form,
                    'errmsg': errmsg,
                    'external': external,
                    'book': book,
                    'createdate': createdate,
                    'startdate': startdate,
                    'enddate': enddate,
                    'currency': currency,
                    'isbn': isbn,
                    'author': author,
                    'title': title,
                    's_list': s_list,
                    'items': items,
                    'sum_books': sum_books,
                    'sum_revenue': sum_revenue,
                    'sum_cogs': sum_cogs,
                    'royalties': roy,
                    'profit': profit,
                }
                form = SalesperbookForm(request.POST)
                return render(request, 'launchpad/sales1.html', context)
    else:
        # First time rendering of form, GET
        form = SalesperbookForm()
    return render(request, 'launchpad/sales1.html', context)


@login_required(login_url='/admin/login/')
def cogs(request):
    """ Utility to check for missing COGS entries in journal entries.
    """

    pagetitle = 'Check for missing COGS entries in Journal sales items'
    m_cogs = []
    missing = Journal.objects.all().filter(cogs=0)\
        .filter(Q(code__xref=112) | Q(code__xref=114) | Q(code__xref=122)
                | Q(code__xref=124) | Q(code__xref=132) | Q(code__xref=134)
                | Q(code__xref=140) | Q(code__xref=142) | Q(code__xref=144))

    for m_item in missing:
        m_cogs.append(m_item)

    context = {
        'pagetitle': pagetitle,
        'm_cogs': m_cogs,
    }
    return render(request, 'launchpad/cogs.html', context)

```

pylint crashed with a ``AstroidError`` and with the following stacktrace:
```
Traceback (most recent call last):
  File "c:\Users\ulisp\.vscode\extensions\ms-python.pylint-2023.4.0\bundled\libs\pylint\lint\pylinter.py", line 798, in _lint_file
    check_astroid_module(module)
  File "c:\Users\ulisp\.vscode\extensions\ms-python.pylint-2023.4.0\bundled\libs\pylint\lint\pylinter.py", line 1067, in check_astroid_module
    retval = self._check_astroid_module(
  File "c:\Users\ulisp\.vscode\extensions\ms-python.pylint-2023.4.0\bundled\libs\pylint\lint\pylinter.py", line 1117, in _check_astroid_module
    walker.walk(node)
  File "c:\Users\ulisp\.vscode\extensions\ms-python.pylint-2023.4.0\bundled\libs\pylint\utils\ast_walker.py", line 96, in walk
    callback(astroid)
  File "c:\Users\ulisp\AppData\Local\Programs\Python\Python38\lib\site-packages\pylint_django\augmentations\__init__.py", line 739, in wrap_func
    return with_method(orig_method, *args, **kwargs)
  File "c:\Users\ulisp\AppData\Local\Programs\Python\Python38\lib\site-packages\pylint_django\augmentations\__init__.py", line 317, in ignore_import_warnings_for_related_fields
    consumer._atomic = ScopeConsumer(new_things, consumer.consumed, consumer.scope_type)  # pylint: disable=W0212
TypeError: __new__() missing 1 required positional argument: 'scope_type'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "c:\Users\ulisp\.vscode\extensions\ms-python.pylint-2023.4.0\bundled\libs\pylint\lint\pylinter.py", line 763, in _lint_files
    self._lint_file(fileitem, module, check_astroid_module)
  File "c:\Users\ulisp\.vscode\extensions\ms-python.pylint-2023.4.0\bundled\libs\pylint\lint\pylinter.py", line 800, in _lint_file
    raise astroid.AstroidError from e
astroid.exceptions.AstroidError
```

### Command used

```shell
opening any Django project file in VSCode
```

### Pylint output

```shell
c:\Users\ulisp\Documents\Computer\Projekte\djac22\launchpad\admin.py: Fatal error while checking 'c:\Users\ulisp\Documents\Computer\Projekte\djac22\launchpad\admin.py'. Please open an issue in our bug tracker so we address this. There is a pre-filled template that you can use in 'C:\Users\ulisp\AppData\Local\pylint\pylint\Cache\pylint-crash-2023-05-01-07-59-51.txt'.
```

### Expected behavior

Open file in VSCode without showing this error.

### Pylint version

```shell
pylint=2.16.2.
```

### OS / Environment

Windows11
VSCode 
Python 3.8.1

### Additional dependencies

appdirs==1.4.4
distlib==0.3.1
filelock==3.0.12
six==1.16.0
virtualenv==20.4.7

**Comment by DanielNoord** [comment]
This is an issue in `pylint-django`. Please report of there and make sure that you have installed their latest version!
