### ISSUE TITLE
crash caused by unimplemented code feature

### ISSUE THREAD

**Issue by Pippin555** [pylint-dev/pylint#8695]
### Bug description

I created a python class EntryExit that implements __enter__(...) and __exit__(...).
when I use 
     with EntryExit() as e_e:

I would assume that the variable e_e is instantiated, but that does not happen, e_e remains None

pylint crashes on this code
python causes an AttributeError 

see also the uploaded file

### Command used

```shell
.../pylint.exe tester.py
```

### Pylint output

```shell
Exception on node <Call l.44 at 0x1fd8c99fc80> in file 'C:\Users\hsalo\source\repos\Buku Pintar\2020\Python_312\tester\tester.py'
Traceback (most recent call last):
  File "C:\Users\hsalo\source\repos\Buku Pintar\2020\Python_312\tester\venv\Lib\site-packages\astroid\decorators.py", line 143, in raise_if_nothing_inferred
    yield next(generator)
          ^^^^^^^^^^^^^^^
StopIteration

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\hsalo\source\repos\Buku Pintar\2020\Python_312\tester\venv\Lib\site-packages\pylint\utils\ast_walker.py", line 91, in walk
    callback(astroid)
  File "C:\Users\hsalo\source\repos\Buku Pintar\2020\Python_312\tester\venv\Lib\site-packages\pylint\checkers\base\basic_checker.py", line 713, in visit_call
    if utils.is_terminating_func(node):
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\hsalo\source\repos\Buku Pintar\2020\Python_312\tester\venv\Lib\site-packages\pylint\checkers\utils.py", line 2202, in is_terminating_func
    return True
           ^^^^
  File "C:\Users\hsalo\source\repos\Buku Pintar\2020\Python_312\tester\venv\Lib\site-packages\astroid\nodes\node_ng.py", line 171, in infer
    yield from self._infer(context=context, **kwargs)
  File "C:\Users\hsalo\source\repos\Buku Pintar\2020\Python_312\tester\venv\Lib\site-packages\astroid\decorators.py", line 149, in raise_if_nothing_inferred
    raise InferenceError(
astroid.exceptions.InferenceError: StopIteration raised without any error information.
```

### Expected behavior

something about unsupported code or that the variable is None

### Pylint version

```shell
python 3.12 (also on version 3.11)
```

### OS / Environment

Windows, using Pycharm 2023.1.1

### Additional dependencies

none
[pylint-crash-2023-05-17-14-01-33.txt](https://github.com/pylint-dev/pylint/files/11497824/pylint-crash-2023-05-17-14-01-33.txt)

**Comment by Pippin555** [comment]
In the description the 'dunders' are missing for entry() and exit()

**Comment by DanielNoord** [comment]
Could you please paste the full content of `tester.py` wihtin a code block?
You can open one with "```"code"```", remove the "

**Comment by Pippin555** [comment]
I hope this gives you all information that you need. 
Environment: Pycharm 2023.1.2

pylint 2.17.4
astroid 2.15.5
Python 3.12.0a7 (tags/v3.12.0a7:b861ba4, Apr  4 2023, 16:33:41) [MSC v.1934 64 bit (AMD64)]

""#! python3.12
# coding: utf8

""" try out some python code """

__author__ = 'Sihir'  # noqa
__copyright__ = "© Sihir 2023-2023 all rights reserved"  # noqa

from sys import exit as _exit
from sys import version


class EntryExit:
    """ example class that can be used in a 'with' construction """

    def __init__(self):
        """ initialize the class """
        print("__init__")

    def __enter__(self):
        """ with is used"""
        print("__enter__")

    def function(self) -> str:
        """ example function """
        assert self
        return "I am alive!"

    def __exit__(self, e_type, e_value, t_back):
        """ class is disposed """
        print(e_type)
        print(e_value)
        print(t_back)
        print("__exit__")


def test_1():
    """ first test """
    print('1 ----')
    try:
        with EntryExit() as e_e:
            # this fails because e_e is None
            # message from code inspection: 'cannot find reference 'function' in 'None'
            print(e_e.function())
            pass
        e_e = None
        assert e_e is None
    except AttributeError as exc:
        print(f'Exception: {str(exc)}')


def test_2():
    """ second test """
    print('2 ----')
    # this succeeds:
    with (e_e := EntryExit()):
        print(e_e.function())

    e_e = None
    assert e_e is None


def test_3():
    """ third test """
    print('3 ----')
    e_e = EntryExit()
    with e_e:
        print(e_e.function())

    e_e = None
    assert e_e is None


def main() -> int:
    """ main entry """
    print(version)

    test_1()
    test_2()
    test_3()

    return 0


if __name__ == '__main__':
    _exit(main())
""

**Comment by Pierre-Sassoulas** [comment]
I cannot reproduce on python 3.10 nor 3.11, it seems it's specific to 3.12.

**Comment by jacobtylerwalls** [comment]
This is an upstream [issue](https://github.com/python/cpython/issues/103488) in Python 3.12.0a7 and was fixed in https://github.com/python/cpython/pull/103502.

Reproducer without pylint:
```python
def reraise_stop_iteration():
    try:
        yield 0
        yield next(iter(range(0)))
    except StopIteration as si:
        raise ValueError from si

gen = reraise_stop_iteration()

def run():
    try:
        for _ in gen:
            return True
    except ValueError:
        print('Caught!')

    return False

run()
run()
```

**Comment by Pippin555** [comment]
Thank you for your effort
