### ISSUE TITLE
Removing list elements in a for-loop causes a crash

### ISSUE THREAD

**Issue by xiaxinmeng** [pylint-dev/pylint#8738]
Removing list elements in a for-loop causes a crash. See the following example

pylint_example.py 
```
a = [1,1]

for i in a:
    if a.count(i) > 1:
        a.remove(i)
print(a)
```

### The expected behavior: 

Pylint does not crash. 

### The actual behavior:
```
>> pylint pylint_example.py
************* Module pylint_example
Desktop/pylint_example.py:19:0: C0303: Trailing whitespace (trailing-whitespace)
Desktop/pylint_example.py:20:0: C0304: Final newline missing (missing-final-newline)
Desktop/pylint_example.py:1:0: C0114: Missing module docstring (missing-module-docstring)
Exception on node <For l.16 at 0x7fdc0a021650> in file '/home/xxm/Desktop/pylint_example.py'
Traceback (most recent call last):
  File "/home/xxm/.local/lib/python3.11/site-packages/pylint/utils/ast_walker.py", line 91, in walk
    callback(astroid)
  File "/home/xxm/.local/lib/python3.11/site-packages/pylint/checkers/modified_iterating_checker.py", line 60, in visit_for
    self._modified_iterating_check_on_node_and_children(body_node, iter_obj)
  File "/home/xxm/.local/lib/python3.11/site-packages/pylint/checkers/modified_iterating_checker.py", line 68, in _modified_iterating_check_on_node_and_children
    self._modified_iterating_check_on_node_and_children(child, iter_obj)
  File "/home/xxm/.local/lib/python3.11/site-packages/pylint/checkers/modified_iterating_checker.py", line 66, in _modified_iterating_check_on_node_and_children
    self._modified_iterating_check(body_node, iter_obj)
  File "/home/xxm/.local/lib/python3.11/site-packages/pylint/checkers/modified_iterating_checker.py", line 96, in _modified_iterating_check
    args=(iter_obj._repr_name(),),
          ^^^^^^^^^^^^^^^^^^^
AttributeError: 'Name' object has no attribute '_repr_name'
Desktop/empirical_type_checker/bug_report/pylint_example.py:1:0: F0002: /home/xxm/Desktop/pylint_example.py: Fatal error while checking '/home/xxm/Desktop/pylint_example.py'. Please open an issue in our bug tracker so we address this. There is a pre-filled template that you can use in '/home/xxm/.cache/pylint/pylint-crash-2023-06-06-23-51-44.txt'. (astroid-error)

------------------------------------------------------------------
Your code has been rated at 0.00/10 (previous run: 0.00/10, +0.00)
```

### Test Environment:

Ubuntu 18.04,
CPython 3.11.3
Pylint: 3.0.0b1
astroid 3.0.0a3

**Comment by jacobtylerwalls** [comment]
Thanks for the report, but `pylint` main is not yet compatible with astroid 3.0.0a3. We're targeting 3.0.0a4, see blocked PR #8685.

@Pierre-Sassoulas do you mind issuing an astroid alpha to unblock #8685?

**Comment by Pierre-Sassoulas** [comment]
Sure, let's do it !
