### ISSUE TITLE
Unfound astroid.exceptions.InferenceError causes a crash

### ISSUE THREAD

**Issue by xiaxinmeng** [pylint-dev/pylint#8739]
The unfound attribute fset causes a fatal error. See the following example:

pylint_example.py
```
class C:
    @property
    def p(self) -> int:
        return 1

C.p.fset
```
#### The expected output:
Works normally.

#### The actual output:
```
>> pylint pylint_example.py
************* Module pylint_example
Desktop/pylint_example.py:19:0: C0303: Trailing whitespace (trailing-whitespace)
Desktop/pylint_example.py:50:0: C0304: Final newline missing (missing-final-newline)
Desktop/pylint_example.py:1:0: C0114: Missing module docstring (missing-module-docstring)
Desktop/pylint_example.py:43:0: C0115: Missing class docstring (missing-class-docstring)
Desktop/pylint_example.py:43:0: C0103: Class name "C" doesn't conform to PascalCase naming style (invalid-name)
Desktop/pylint_example.py:45:4: C0116: Missing function or method docstring (missing-function-docstring)
Desktop/pylint_example.py:45:4: C0103: Attribute name "p" doesn't conform to snake_case naming style (invalid-name)
Desktop/pylint_example.py:43:0: R0903: Too few public methods (1/2) (too-few-public-methods)
Desktop/pylint_example.py:49:0: W0104: Statement seems to have no effect (pointless-statement)
Exception on node <Attribute.fset l.49 at 0x7f230d51dd10> in file '/home/xxm/pylint_example.py'
Traceback (most recent call last):
  File "/home/xxm/.local/lib/python3.11/site-packages/pylint/utils/ast_walker.py", line 91, in walk
    callback(astroid)
  File "/home/xxm/.local/lib/python3.11/site-packages/pylint/checkers/typecheck.py", line 1123, in visit_attribute
    attr_nodes = owner.getattr(node.attrname)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/xxm/.local/lib/python3.11/site-packages/astroid/nodes/scoped_nodes/scoped_nodes.py", line 1269, in getattr
    found_attrs.append(self.special_attributes.lookup(name))
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/xxm/.local/lib/python3.11/site-packages/astroid/interpreter/objectmodel.py", line 132, in lookup
    return getattr(self, IMPL_PREFIX + name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/xxm/.local/lib/python3.11/site-packages/astroid/interpreter/objectmodel.py", line 985, in attr_fset
    raise InferenceError(
astroid.exceptions.InferenceError: Unable to find the setter of property p
Desktop/empirical_type_checker/bug_report/pylint_example.py:1:0: F0002: /home/xxm/Desktop/pylint_example.py: Fatal error while checking '/home/xxm/Desktop/pylint_example.py'. Please open an issue in our bug tracker so we address this. There is a pre-filled template that you can use in '/home/xxm/.cache/pylint/pylint-crash-2023-06-07-00-16-44.txt'. (astroid-error)
------------------------------------------------------------------
Your code has been rated at 0.00/10 (previous run: 0.00/10, +0.00)
```

#### Test Environment:
Ubuntu 18.04,
CPython 3.11.3
Pylint: 3.0.0b1
astroid 3.0.0a3

**Comment by nickdrozd** [comment]
@xiaxinmeng These crash reports are amazing! I had never heard of these property methods before. [From the docs](https://docs.python.org/3/library/functions.html?highlight=fset#property):

> fget is a function for getting an attribute value. fset is a function for setting an attribute value. fdel is a function for deleting an attribute value. And doc creates a docstring for the attribute.
