### ISSUE TITLE
Defining collections.namedtuple object trigger an AstroidError

### ISSUE THREAD

**Issue by xiaxinmeng** [pylint-dev/pylint#8746]
When creating a collections.namedtuple object like following, pylint report a fatal error.

pylint_example.py
```
from collections import namedtuple
names = ['\u00b5']
mu = namedtuple('mu', names)
```

The expected output:
This code can work well.

#### The actual output
```
************* Module pylint_example
Desktop/pylint_example.py:14:3: C0303: Trailing whitespace (trailing-whitespace)
Desktop/pylint_example.py:17:15: C0303: Trailing whitespace (trailing-whitespace)
Desktop/pylint_example.py:61:0: C0305: Trailing newlines (trailing-newlines)
Desktop/pylint_example.py:1:0: C0114: Missing module docstring (missing-module-docstring)
Exception on node <AssignName.mu l.28 at 0x7fd5575b15d0> in file '/home/xxm/Desktop/pylint_example.py'
Traceback (most recent call last):
  File "/home/xxm/.local/lib/python3.11/site-packages/astroid/inference_tip.py", line 54, in inner
    yield from _cache[func, node, context]
               ~~~~~~^^^^^^^^^^^^^^^^^^^^^
KeyError: (<function infer_named_tuple at 0x7fd55ab2d1c0>, <Call l.28 at 0x7fd5575b1810>, None)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/xxm/.local/lib/python3.11/site-packages/pylint/checkers/utils.py", line 1341, in safe_infer
    value = next(infer_gen)
            ^^^^^^^^^^^^^^^
  File "/home/xxm/.local/lib/python3.11/site-packages/astroid/nodes/node_ng.py", line 147, in infer
    yield from self._explicit_inference(
  File "/home/xxm/.local/lib/python3.11/site-packages/astroid/inference_tip.py", line 66, in inner
    func(node, context, **kwargs)
  File "/home/xxm/.local/lib/python3.11/site-packages/astroid/brain/brain_namedtuple_enum.py", line 270, in infer_named_tuple
    class_node.locals[attr] = fake.body[0].locals[attr]
                              ~~~~~~~~~~~~~~~~~~~^^^^^^
KeyError: 'µ'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/xxm/.local/lib/python3.11/site-packages/pylint/utils/ast_walker.py", line 91, in walk
    callback(astroid)
  File "/home/xxm/.local/lib/python3.11/site-packages/pylint/checkers/base/name_checker/checker.py", line 416, in visit_assignname
    inferred_assign_type = utils.safe_infer(assign_type.value)
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/xxm/.local/lib/python3.11/site-packages/pylint/checkers/utils.py", line 1345, in safe_infer
    raise AstroidError from e
astroid.exceptions.AstroidError
Desktop/empirical_type_checker/bug_report/pylint_example.py:1:0: F0002: /home/xxm/Desktop/pylint_example.py: Fatal error while checking '/home/xxm/Desktop/pylint_example.py'. Please open an issue in our bug tracker so we address this. There is a pre-filled template that you can use in '/home/xxm/.cache/pylint/pylint-crash-2023-06-07-13-17-53.txt'. (astroid-error)

------------------------------------------------------------------
Your code has been rated at 0.00/10 (previous run: 0.00/10, +0.00)
```

#### Test Environment:
pylint 3.0.0b1
astroid 3.0.0a5-dev0
Python 3.11.3

**Comment by ekanshul** [comment]
This no longer reproduces. With current `main` of pylint (4.1.0-dev0) and astroid (4.4.0-dev0),

```python
from collections import namedtuple
names = ['\u00b5']
mu = namedtuple('mu', names)
```

lints cleanly with no `astroid-error` (the non-ASCII field name is now handled), so this can probably be closed.
