### ISSUE TITLE
'from . import *'  causes an IndexError

### ISSUE THREAD

**Issue by xiaxinmeng** [pylint-dev/pylint#8749]
'from . import *' triggers an IndexError of pylint.

pylint_example.py:
```
print('hi')
from . import *
```

#### The expected output
No fatal error

#### The actual output:
```
************* Module pylint_example
Desktop/pylint_example.py:14:7: C0303: Trailing whitespace (trailing-whitespace)
Desktop/pylint_example.py:17:17: C0303: Trailing whitespace (trailing-whitespace)
Desktop/pylint_example.py:61:0: C0305: Trailing newlines (trailing-newlines)
Desktop/pylint_example.py:1:0: C0114: Missing module docstring (missing-module-docstring)
Desktop/pylint_example.py:1:0: W0401: Wildcard import  (wildcard-import)
Exception on node <ImportFrom l.1 at 0x7f8021eb4b10> in file '/home/xxm/Desktop/pylint_example.py'
Traceback (most recent call last):
  File "/home/xxm/.local/lib/python3.11/site-packages/pylint/utils/ast_walker.py", line 91, in walk
    callback(astroid)
  File "/home/xxm/.local/lib/python3.11/site-packages/pylint/checkers/imports.py", line 556, in visit_importfrom
    self._add_imported_module(node, imported_module.name)
  File "/home/xxm/.local/lib/python3.11/site-packages/pylint/checkers/imports.py", line 877, in _add_imported_module
    importedmodname = astroid.modutils.get_module_part(
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/xxm/.local/lib/python3.11/site-packages/astroid/modutils.py", line 433, in get_module_part
    while parts[starti] == "":  # for all further dots: change context
          ~~~~~^^^^^^^^
IndexError: list index out of range
Desktop/pylint_example.py:1:0: F0002: /home/xxm/Desktop/pylint_example.py: Fatal error while checking '/home/xxm/Desktop/pylint_example.py'. Please open an issue in our bug tracker so we address this. There is a pre-filled template that you can use in '/home/xxm/.cache/pylint/pylint-crash-2023-06-07-13-42-57.txt'. (astroid-error)

------------------------------------------------------------------
Your code has been rated at 0.00/10 (previous run: 0.00/10, +0.00)
```

Test Environment:
pylint 3.0.0b1
astroid 3.0.0a5-dev0
Python 3.11.3
Ubuntu 18.04

**Comment by xiaxinmeng** [comment]
Thanks, our team is currently developing a new fuzzer specifically designed to test static analysis tools like pylint and mypy. Although the tool is not yet fully complete, we are actively working on it. Once we are ready, we will open-source the tool on GitHub. We hope that these reported bugs will be helpful for the maintenance and improvement of pylint. Thanks again.

**Comment by xiaxinmeng** [comment]
This is a great suggestion. Currently, we have developed a simple prototype of the tool. I believe it would not be difficult to integrate it with an autoformatter's result by making a few modifications. Thank you for the suggestion! Currently, we are in the process of expanding the functionality of this tool. One of the key areas we are focusing on is the detection of behavior bugs, i.e, bugs that lead to unexpected behaviors. By enhancing the tool, we aim to provide more comprehensive bug detection capabilities.
