### ISSUE TITLE
no-argument call to copy.copy() crashes

### ISSUE THREAD

**Issue by jacobtylerwalls** [pylint-dev/pylint#8774]
### Bug description

```python
from copy import copy
copy()
```

### Configuration

```ini
n/a
```

### Command used

```shell
pylint a.py
```

### Pylint output

<details open>
    <summary>
        pylint crashed with a ``AstroidError`` and with the following stacktrace:
    </summary>

```
Traceback (most recent call last):
  File "/Users/user/pylint/pylint/lint/pylinter.py", line 788, in _lint_file
    check_astroid_module(module)
  File "/Users/user/pylint/pylint/lint/pylinter.py", line 1017, in check_astroid_module
    retval = self._check_astroid_module(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/user/pylint/pylint/lint/pylinter.py", line 1063, in _check_astroid_module
    walker.walk(node)
  File "/Users/user/pylint/pylint/utils/ast_walker.py", line 94, in walk
    self.walk(child)
  File "/Users/user/pylint/pylint/utils/ast_walker.py", line 94, in walk
    self.walk(child)
  File "/Users/user/pylint/pylint/utils/ast_walker.py", line 91, in walk
    callback(astroid)
  File "/Users/user/pylint/pylint/checkers/stdlib.py", line 563, in visit_call
    self._check_shallow_copy_environ(node)
  File "/Users/user/pylint/pylint/checkers/stdlib.py", line 514, in _check_shallow_copy_environ
    arg = utils.get_argument_from_call(node, position=0)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/user/pylint/pylint/checkers/utils.py", line 736, in get_argument_from_call
    raise NoSuchArgumentError
pylint.checkers.utils.NoSuchArgumentError

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/user/pylint/pylint/lint/pylinter.py", line 752, in _lint_files
    self._lint_file(fileitem, module, check_astroid_module)
  File "/Users/user/pylint/pylint/lint/pylinter.py", line 790, in _lint_file
    raise astroid.AstroidError from e
astroid.exceptions.AstroidError
```

</details>

### Expected behavior

no crash

### Pylint version

```shell
pylint 3.0.0b1
astroid 3.0.0a6-dev0
Python 3.11.2
```

**Comment by jacobtylerwalls** [comment]
Good first issue for someone. Example implementation to follow in #8728.

**Comment by mstva** [comment]
Hi @jacobtylerwalls, I am interested in this issue and would like to work on it, could I know what I need to know before working on it? Thanks

**Comment by mstva** [comment]
I reproduced it on my machine
