### ISSUE TITLE
Pylint crashes with an invalid TypeVar definition

### ISSUE THREAD

**Issue by yilei** [pylint-dev/pylint#8802]
### Bug description

Example code:

```python
from typing import TypeVar

MyType = TypeVar('My.Type')
```

### Command used

```shell
pylint a.py
```

### Pylint output

```shell
************* Module a
a.py:4:0: C0305: Trailing newlines (trailing-newlines)
a.py:1:0: C0114: Missing module docstring (missing-module-docstring)
Exception on node <AssignName.MyType l.3 at 0x7f9f93ce5360> in file 'a.py'
Traceback (most recent call last):
  File "astroid/inference_tip.py", line 33, in _inference_tip_cached
    result = _cache[func, node]
KeyError: (<function infer_typing_typevar_or_newtype at 0x7f9f9449c820>, <Call l.3 at 0x7f9f93ce55a0>)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "astroid/builder.py", line 181, in _data_build
    node, parser_module = _parse_string(data, type_comments=True)
  File "astroid/builder.py", line 484, in _parse_string
    parsed = parser_module.parse(data + "\n", type_comments=type_comments)
  File "astroid/_ast.py", line 50, in parse
    return parse_func(string)
  File "ast.py", line 50, in parse
    return compile(source, filename, mode, flags,
  File "<unknown>", line 10
    class My.Type(metaclass=Meta):
            ^
SyntaxError: invalid syntax

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "pylint/checkers/utils.py", line 1371, in safe_infer
    value = next(infer_gen)
  File "astroid/nodes/node_ng.py", line 161, in infer
    results = list(self._explicit_inference(self, context, **kwargs))
  File "astroid/inference_tip.py", line 40, in _inference_tip_cached
    result = _cache[func, node] = list(func(*args, **kwargs))
  File "astroid/brain/brain_typing.py", line 140, in infer_typing_typevar_or_newtype
    node = extract_node(TYPING_TYPE_TEMPLATE.format(typename))
  File "astroid/builder.py", line 450, in extract_node
    tree = parse(code, module_name=module_name)
  File "astroid/builder.py", line 307, in parse
    return builder.string_build(code, modname=module_name, path=path)
  File "astroid/builder.py", line 151, in string_build
    module, builder = self._data_build(data, modname, path)
  File "astroid/builder.py", line 183, in _data_build
    raise AstroidSyntaxError(
astroid.exceptions.AstroidSyntaxError: Parsing Python code failed:
invalid syntax (<unknown>, line 10)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "pylint/utils/ast_walker.py", line 91, in walk
    callback(astroid)
  File "pylint/checkers/base/name_checker/checker.py", line 416, in visit_assignname
    inferred_assign_type = utils.safe_infer(assign_type.value)
  File "pylint/checkers/utils.py", line 1375, in safe_infer
    raise AstroidError from e
astroid.exceptions.AstroidError
a.py:1:0: F0002: a.py: Fatal error while checking 'a.py'. Please open an issue in our bug tracker so we address this. There is a pre-filled template that you can use in '~/.cache/pylint/pylint-crash-2023-06-26-13-55-46.txt'. (astroid-error)

-----------------------------------
Your code has been rated at 0.00/10
```

### Expected behavior

It should not crash.

### Pylint version

```shell
pylint 2.17.4
astroid 2.15.5
Python 3.10.8 (main, Mar  9 2023, 10:11:52) [GCC 12.2.0]
```

**Comment by jacobtylerwalls** [comment]
Thanks for the report!

**Comment by mbyrnepr2** [comment]
I've pushed a potential fix for this. I think it isn't an invalid definition per se. Python and mypy are ok with it and in the case of mypy, it points out that the argument name does not match the variable name, which is what Pylint should do also.
Perhaps your debug output is because of the older version of Pylint - I haven't looked into that.
