### ISSUE TITLE
Crash when change file name

### ISSUE THREAD

**Issue by Chris112358** [pylint-dev/pylint#8818]
### Bug description

crash occures when changing the name of the file to sensor.py any other name works perfectly fine. Im currently try to develop for homeassistant.
[pylint-crash-2023-07-03-17-06-03.txt](https://github.com/pylint-dev/pylint/files/11939710/pylint-crash-2023-07-03-17-06-03.txt)

### Command used

```shell
I used the vs-code intern pylinter
```

### Pylint output

```shell
pylint crashed with a ``AstroidError`` and with the following stacktrace:

Traceback (most recent call last):
  File "/root/.vscode-server/extensions/ms-python.pylint-2023.4.0/bundled/libs/pylint/lint/pylinter.py", line 798, in _lint_file
    check_astroid_module(module)
  File "/root/.vscode-server/extensions/ms-python.pylint-2023.4.0/bundled/libs/pylint/lint/pylinter.py", line 1067, in check_astroid_module
    retval = self._check_astroid_module(
  File "/root/.vscode-server/extensions/ms-python.pylint-2023.4.0/bundled/libs/pylint/lint/pylinter.py", line 1117, in _check_astroid_module
    walker.walk(node)
  File "/root/.vscode-server/extensions/ms-python.pylint-2023.4.0/bundled/libs/pylint/utils/ast_walker.py", line 94, in walk
    self.walk(child)
  File "/root/.vscode-server/extensions/ms-python.pylint-2023.4.0/bundled/libs/pylint/utils/ast_walker.py", line 91, in walk
    callback(astroid)
  File "/workspaces/core/pylint/plugins/hass_enforce_type_hints.py", line 1658, in visit_functiondef
    self._check_function(node, match)
  File "/workspaces/core/pylint/plugins/hass_enforce_type_hints.py", line 1675, in _check_function
    if not _is_valid_type(expected_type, annotations[key]):
IndexError: list index out of range

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/root/.vscode-server/extensions/ms-python.pylint-2023.4.0/bundled/libs/pylint/lint/pylinter.py", line 763, in _lint_files
    self._lint_file(fileitem, module, check_astroid_module)
  File "/root/.vscode-server/extensions/ms-python.pylint-2023.4.0/bundled/libs/pylint/lint/pylinter.py", line 800, in _lint_file
    raise astroid.AstroidError from e
astroid.exceptions.AstroidError
```

### Expected behavior

should not crash on name change

### Pylint version

```shell
pylint 2.15.6
astroid 2.13.5
Python 3.9.12 (main, Apr  7 2022, 04:19:52)
```

**Comment by Pierre-Sassoulas** [comment]
Thank you for opening the issue. It seems the problem happens in a home assistant plugin:

https://github.com/home-assistant/core/blob/4581c3664879a848da111a2caa7dbeebebd1da71/pylint/plugins/hass_enforce_type_hints.py#L3164
