### ISSUE TITLE
Preferred way to find pylintrc in pylint 3

### ISSUE THREAD

**Issue by qi55wyqu** [pylint-dev/pylint#8862]
### Question

I've been using `pylint.config.PYLINTRC` in the init-hook of the pylintrc to set up the PYTHONPATH.
```
init-hook="
      import os, pathlib, pylint, sys
      testDir = pathlib.Path(pylint.config.PYLINTRC).resolve().parent.joinpath("test")
      sys.path.append(os.fspath(testDir))"
```
In pylint 3 this leads to an error
```
AttributeError: module 'pylint.config' has no attribute 'PYLINTRC'
```
This method was much more convenient and portable than setting the PYTHONPATH outside of pylint.
What is the preferred way to do this in pylint 3?

### Documentation for future user

Documentation, release notes

**Comment by qi55wyqu** [comment]
I set the init-hook in pylintrc and called
```
pylint --rcfile pylintrc  /path/to/file.py
```
but got an AttributeError.

I'm using python 3.11.4 with pylint 3.0.0a6.

**Comment by Pierre-Sassoulas** [comment]
Could you provide the stacktrace, please ?

**Comment by DanielNoord** [comment]
The constant was removed in https://github.com/pylint-dev/pylint/commit/3318aa0c5877abd9e9d2361f8a21b8880b7a052d#diff-24934165194ae0ca6e01c8e20fc7f7f24b54766260e02cac072c057a80cece49 following a deprecation period.

I don't really understand your use case, but can't you just do a `os.getcwd()` to get the directory name?

**Comment by Pierre-Sassoulas** [comment]
I understood now, remove the init-hook and use the rcfile option.

**Comment by qi55wyqu** [comment]
Stacktrace:
```Traceback (most recent call last):
  File "/home/USER/.local/share/virtualenvs/tmp.Tmyq3RRWpX-tOmAVYQd/bin/pylint", line 8, in <module>
    sys.exit(run_pylint())
             ^^^^^^^^^^^^
  File "/home/USER/.local/share/virtualenvs/tmp.Tmyq3RRWpX-tOmAVYQd/lib/python3.11/site-packages/pylint/__init__.py", line 34, in run_pylint
    PylintRun(argv or sys.argv[1:])
  File "/home/USER/.local/share/virtualenvs/tmp.Tmyq3RRWpX-tOmAVYQd/lib/python3.11/site-packages/pylint/lint/run.py", line 165, in __init__
    args = _config_initialization(
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/USER/.local/share/virtualenvs/tmp.Tmyq3RRWpX-tOmAVYQd/lib/python3.11/site-packages/pylint/config/config_initialization.py", line 50, in _config_initialization
    exec(utils._unquote(config_data["init-hook"]))  # pylint: disable=exec-used
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<string>", line 3, in <module>
AttributeError: module 'pylint.config' has no attribute 'PYLINTRC'
```


If I use `os.getcwd()` it only works when I'm in the same directory as the `pylintrc` but not when I run it from a different directory. 

If I remove the `init-hook`, I get `import-error`s because the `PYTHONPATH` is missing the directories that I added in the `init-hook`.
It only works if I export `PYTHONPATH` before calling pylint, which unfortunately is less convenient than setting everything up in the `init-hook`.

**Comment by DanielNoord** [comment]
I think this is actually a common use case? You might be in a directory where one of the parent directories has your `pylintrc` and your tests directory.
Using the file and adding the directory to your path seems like something people might want. Perhaps we should expose the finding of the config file as public api? We did previously.

**Comment by sauing** [comment]
This issue is observed while running flake8-pylint from pre-commit as additional dependencies for flake8. 
**flake8-pylint version**: 0.2.1
**flake8 version**: 6.0.0
**pre-commit**: 3.6.0 
**Stack Trace**: 
flake8...................................................................Failed
- hook id: flake8
- exit code: 1

Traceback (most recent call last):
  File "C:\Users\factory\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\factory\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "C:\Users\factory\.cache\pre-commit\repoujy51n3r\py_env-python3.10\Scripts\flake8.EXE\__main__.py", line 7, in <module>
  File "C:\Users\factory\.cache\pre-commit\repoujy51n3r\py_env-python3.10\lib\site-packages\flake8\main\cli.py", line 23, in main
    app.run(argv)
  File "C:\Users\factory\.cache\pre-commit\repoujy51n3r\py_env-python3.10\lib\site-packages\flake8\main\application.py", line 198, in run
    self._run(argv)
  File "C:\Users\factory\.cache\pre-commit\repoujy51n3r\py_env-python3.10\lib\site-packages\flake8\main\application.py", line 187, in _run
    self.run_checks()
  File "C:\Users\factory\.cache\pre-commit\repoujy51n3r\py_env-python3.10\lib\site-packages\flake8\main\application.py", line 103, in run_checks
    self.file_checker_manager.run()
  File "C:\Users\factory\.cache\pre-commit\repoujy51n3r\py_env-python3.10\lib\site-packages\flake8\checker.py", line 236, in run
    self.run_serial()
  File "C:\Users\factory\.cache\pre-commit\repoujy51n3r\py_env-python3.10\lib\site-packages\flake8\checker.py", line 214, in run_serial
    self.results = [
  File "C:\Users\factory\.cache\pre-commit\repoujy51n3r\py_env-python3.10\lib\site-packages\flake8\checker.py", line 219, in <listcomp>
    ).run_checks()
  File "C:\Users\factory\.cache\pre-commit\repoujy51n3r\py_env-python3.10\lib\site-packages\flake8\checker.py", line 524, in run_checks
    self.run_ast_checks()
  File "C:\Users\factory\.cache\pre-commit\repoujy51n3r\py_env-python3.10\lib\site-packages\flake8\checker.py", line 426, in run_ast_checks
    for (line_number, offset, text, _) in runner:
  File "C:\Users\factory\.cache\pre-commit\repoujy51n3r\py_env-python3.10\lib\site-packages\flake8_pylint\_plugin.py", line 92, in run
    Run([self.filename], reporter=reporter, exit=False)
  File "C:\Users\factory\.cache\pre-commit\repoujy51n3r\py_env-python3.10\lib\site-packages\pylint\lint\run.py", line 162, in __init__
    args = _config_initialization(
  File "C:\Users\factory\.cache\pre-commit\repoujy51n3r\py_env-python3.10\lib\site-packages\pylint\config\config_initialization.py", line 57, in _config_initialization
    exec(utils._unquote(config_data["init-hook"]))  # pylint: disable=exec-used
  File "<string>", line 2, in <module>
AttributeError: module 'pylint.config' has no attribute 'PYLINTRC'


**Yaml file**:
![image](https://github.com/pylint-dev/pylint/assets/31505607/05104210-30e7-4135-9be5-eeff6a440a32)

**Comment by DanielNoord** [comment]
@sauing Please update your `init-hook` to no longer reference `PYLINTRC`.

**Comment by sauing** [comment]
> @sauing Please update your `init-hook` to no longer reference `PYLINTRC`.

Thanks it works :)

**Comment by Pierre-Sassoulas** [comment]
In this case it seems we need to fix the Doc on stackoverflow too: https://github.com/pylint-dev/pylint/issues/9105#issuecomment-1984960910
