### ISSUE TITLE
Astroid Crash ``'AsStringVisitor' object has no attribute 'visit_partialfunction'``

### ISSUE THREAD

**Issue by chadhpaine** [pylint-dev/pylint#8881]
### Bug description

When parsing the following file:

```python
from functools import partial
from operator import ge

VALUE = 23.2
comp = lambda current_value, low, high: low < current_value <= high
print(next(value for comparator, value in {partial(ge, 0): 'No Data Available',
                                           **{partial(comp, low=f, high=s): f'>{f}% - {s}%'
                                              for f, s in [(0, 15), (15, 25), (25, 50)]}}.items()
           if comparator(VALUE)))  # prints ">15% - 25%"
```

pylint crashed with a ``AstroidError`` and with the following stacktrace:
```
Traceback (most recent call last):
  File ".\tools\python\Lib\site-packages\pylint\checkers\utils.py", line 1371, in safe_infer
    value = next(infer_gen)
            ^^^^^^^^^^^^^^^
  File ".\tools\python\Lib\site-packages\astroid\nodes\node_ng.py", line 171, in infer
    yield from self._infer(context=context, **kwargs)
  File ".\tools\python\Lib\site-packages\astroid\decorators.py", line 143, in raise_if_nothing_inferred
    yield next(generator)
          ^^^^^^^^^^^^^^^
  File ".\tools\python\Lib\site-packages\astroid\decorators.py", line 112, in wrapped
    for res in _func(node, context, **kwargs):
  File ".\tools\python\Lib\site-packages\astroid\inference.py", line 270, in infer_call
    for callee in self.func.infer(context):
  File ".\tools\python\Lib\site-packages\astroid\nodes\node_ng.py", line 184, in infer
    for i, result in enumerate(self._infer(context=context, **kwargs)):
  File ".\tools\python\Lib\site-packages\astroid\decorators.py", line 143, in raise_if_nothing_inferred
    yield next(generator)
          ^^^^^^^^^^^^^^^
  File ".\tools\python\Lib\site-packages\astroid\decorators.py", line 112, in wrapped
    for res in _func(node, context, **kwargs):
  File ".\tools\python\Lib\site-packages\astroid\inference.py", line 358, in infer_attribute
    for owner in self.expr.infer(context):
  File ".\tools\python\Lib\site-packages\astroid\nodes\node_ng.py", line 184, in infer
    for i, result in enumerate(self._infer(context=context, **kwargs)):
  File ".\tools\python\Lib\site-packages\astroid\inference.py", line 146, in infer_map
    items = _infer_map(self, context)
            ^^^^^^^^^^^^^^^^^^^^^^^^^
  File ".\tools\python\Lib\site-packages\astroid\inference.py", line 198, in _infer_map
    values = _update_with_replacement(values, {key: safe_value})
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File ".\tools\python\Lib\site-packages\astroid\inference.py", line 173, in _update_with_replacement
    string_map = {key.as_string(): (key, value) for key, value in combined_dict}
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File ".\tools\python\Lib\site-packages\astroid\inference.py", line 173, in <dictcomp>
    string_map = {key.as_string(): (key, value) for key, value in combined_dict}
                  ^^^^^^^^^^^^^^^
  File ".\tools\python\Lib\site-packages\astroid\nodes\node_ng.py", line 648, in as_string
    return AsStringVisitor()(self)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File ".\tools\python\Lib\site-packages\astroid\nodes\as_string.py", line 45, in __call__
    return node.accept(self).replace(DOC_NEWLINE, "\n")
           ^^^^^^^^^^^^^^^^^
  File ".\tools\python\Lib\site-packages\astroid\nodes\node_ng.py", line 251, in accept
    func = getattr(visitor, "visit_" + self.__class__.__name__.lower())
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'AsStringVisitor' object has no attribute 'visit_partialfunction'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File ".\tools\python\Lib\site-packages\pylint\lint\pylinter.py", line 811, in _lint_file
    check_astroid_module(module)
  File ".\tools\python\Lib\site-packages\pylint\lint\pylinter.py", line 1085, in check_astroid_module
    retval = self._check_astroid_module(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File ".\tools\python\Lib\site-packages\pylint\lint\pylinter.py", line 1135, in _check_astroid_module
    walker.walk(node)
  File ".\tools\python\Lib\site-packages\pylint\utils\ast_walker.py", line 94, in walk
    self.walk(child)
  File ".\tools\python\Lib\site-packages\pylint\utils\ast_walker.py", line 94, in walk
    self.walk(child)
  File ".\tools\python\Lib\site-packages\pylint\utils\ast_walker.py", line 94, in walk
    self.walk(child)
  [Previous line repeated 1 more time]
  File ".\tools\python\Lib\site-packages\pylint\utils\ast_walker.py", line 91, in walk
    callback(astroid)
  File ".\tools\python\Lib\site-packages\pylint\checkers\typecheck.py", line 2298, in visit_generatorexp
    self._check_iterable(gen.iter, check_async=gen.is_async)
  File ".\tools\python\Lib\site-packages\pylint\checkers\typecheck.py", line 2242, in _check_iterable
    inferred = safe_infer(node)
               ^^^^^^^^^^^^^^^^
  File ".\tools\python\Lib\site-packages\pylint\checkers\utils.py", line 1375, in safe_infer
    raise AstroidError from e
astroid.exceptions.AstroidError

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File ".\tools\python\Lib\site-packages\pylint\lint\pylinter.py", line 775, in _lint_files
    self._lint_file(fileitem, module, check_astroid_module)
  File ".\tools\python\Lib\site-packages\pylint\lint\pylinter.py", line 813, in _lint_file
    raise astroid.AstroidError from e
astroid.exceptions.AstroidError
```

### Command used

```shell
tools\python\python.exe -m pylint src/test_pylint/main.py
```

### Pylint output

```shell
************* Module main
src\test_pylint\main.py:1:0: C0114: Missing module docstring (missing-module-docstring)
src\test_pylint\main.py:5:7: C3001: Lambda expression assigned to a variable. Define a function using the "def" keyword instead. (unnecessary-lambda-assignment)
Exception on node <GeneratorExp l.6 at 0x2678f6c71d0> in file '.\src\test_pylint\main.py'
```

### Expected behavior

Pylint should not crash.

### Pylint version

```shell
pylint 2.17.4
astroid 2.15.6
Python 3.11.4 (tags/v3.11.4:d2340ef, Jun  7 2023, 05:45:37) [MSC v.1934 64 bit (AMD64)]
```

### OS / Environment

CYGWIN_NT-10.0-22621 3.4.7-1.x86_64 x86_64 on Microsoft Windows [Version 10.0.22621.1992]

EDIT: Example minimization and updating of relevant logs

**Comment by jacobtylerwalls** [comment]
Thanks for the reproducer!

**Comment by DanielNoord** [comment]
I have a fix locally. Just need some WiFi (somewhere next week) to push it :)

**Comment by Pierre-Sassoulas** [comment]
Daniel, I'm picturing you with your labtop in hands under a heavenly waterfall, or palm tree at the beach, or next to a 6500 year old sumarian funeral rock at the museum, and desperately trying to get some better reception and the little stream of mobile data that will able you to **merge that code to main** 😂 That's dedication ! (Also, try enjoying your holiday, pylint 3.0 can release 4 weeks late, you know)
