### ISSUE TITLE
Crash when using typing.cast

### ISSUE THREAD

**Issue by jerryc05** [pylint-dev/pylint#8916]
### Bug description

pylint this code:
```python
from typing import cast
cast(int,0)
```

### Configuration

```ini
default (None)
```

### Command used

```shell
pylint test.py
```

### Pylint output

```shell
************* Module ***
***.py:1:0: C0114: Missing module docstring (missing-module-docstring)
***.py:1:0: C0103: Module name "***" doesn't conform to snake_case naming style (invalid-name)
Exception on node <ImportFrom l.1 at 0x214235ba7b0> in file '***'
Traceback (most recent call last):
  File "***\Python\Python312\Lib\site-packages\pylint\checkers\imports.py", line 858, in _get_imported_module
    return importnode.do_import_module(modname)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "***\Python\Python312\Lib\site-packages\astroid\nodes\_base_nodes.py", line 146, in do_import_module
    return mymodule.import_module(
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "***\Python\Python312\Lib\site-packages\astroid\nodes\scoped_nodes\scoped_nodes.py", line 530, in import_module
    return AstroidManager().ast_from_module_name(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "***\Python\Python312\Lib\site-packages\astroid\manager.py", line 246, in ast_from_module_name
    return self.ast_from_file(found_spec.location, modname, fallback=False)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "***\Python\Python312\Lib\site-packages\astroid\manager.py", line 138, in ast_from_file
    return AstroidBuilder(self).file_build(filepath, modname)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "***\Python\Python312\Lib\site-packages\astroid\builder.py", line 144, in file_build
    module, builder = self._data_build(data, modname, path)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "***\Python\Python312\Lib\site-packages\astroid\builder.py", line 204, in _data_build
    module = builder.visit_module(node, modname, node_file, package)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "***\Python\Python312\Lib\site-packages\astroid\rebuilder.py", line 254, in visit_module
    [self.visit(child, newnode) for child in node.body],
     ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "***\Python\Python312\Lib\site-packages\astroid\rebuilder.py", line 609, in visit
    visit_method = getattr(self, visit_name)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'TreeRebuilder' object has no attribute 'visit_typealias'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "***\Python\Python312\Lib\site-packages\pylint\utils\ast_walker.py", line 91, in walk
    callback(astroid)
  File "***\Python\Python312\Lib\site-packages\pylint\checkers\imports.py", line 549, in visit_importfrom
    imported_module = self._get_imported_module(node, basename)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "***\Python\Python312\Lib\site-packages\pylint\checkers\imports.py", line 883, in _get_imported_module
    raise astroid.AstroidError from e
astroid.exceptions.AstroidError
***.py:1:0: F0002: ***.py: Fatal error while checking '***.py'. Please open an issue in our bug tracker so we address this. There is a pre-filled template that you can use in '***'. (astroid-error)

-----------------------------------
Your code has been rated at 0.00/10
```

### Expected behavior

no error

### Pylint version

```shell
pylint 2.17.5
astroid 2.15.6
Python 3.12.0b4 (tags/v3.12.0b4:97a6a41, Jul 11 2023, 13:49:15) [MSC v.1935 64 bit (AMD64)]
```

**Comment by mbyrnepr2** [comment]
Thanks @jerryc05 is there something else going on in your test module?

From the provided trace:
```python
Exception on node <ImportFrom l.1 at 0x214235ba7b0> in file '***'
```

**Comment by DanielNoord** [comment]
@jacobtylerwalls Is this something to block the beta on?

**Comment by jacobtylerwalls** [comment]
No, since the reported version is pylint 2.17.5.

@jerryc05 thanks for the report, but the support for running pylint on a Python 3.12 interpreter is not yet released--it only exists on the main branch.

Closing as a duplicate of #8782
