### ISSUE TITLE
pylint reporting error for pydantic module not exists

### ISSUE THREAD

**Issue by yinuu** [pylint-dev/pylint#8917]
#### base.py
```Python
from pydantic import BaseModel as PydanticBaseModel, Extra
from pydantic import ValidationError

class BaseModel(PydanticBaseModel):
    """BaseModel"""

    class Config:
        """Config Overwrite Pydantic default"""

        extra = Extra.forbid


class TestStub(BaseModel):
    """TestStub"""

    name: str
    age: int | None = None


if __name__ == "__main__":
    TestStub(**{"name": "human", "age": "ss"})
```

> output as follow: 
Traceback (most recent call last):
  File "/home/fruity-yin/workspace/wechat-app-project/app/src/model/base.py", line 21, in <module>
    TestStub(**{"name": "human", "age": "ss"})
  File "pydantic/main.py", line 341, in pydantic.main.BaseModel.__init__
pydantic.error_wrappers.ValidationError: 1 validation error for TestStub
age
  value is not a valid integer (type=type_error.integer)

it seems works well, but pylint report a error with msg:
> No name 'BaseModel' in module 'pydantic' (no-name-in-module)

### Command used

```shell
pylint app/src/model/base.py
```

### Pylint output

```shell
************* Module model.base
app/src/model/base.py:21:0: C0304: Final newline missing (missing-final-newline)
app/src/model/base.py:1:0: C0114: Missing module docstring (missing-module-docstring)
app/src/model/base.py:1:0: E0611: No name 'BaseModel' in module 'pydantic' (no-name-in-module)
app/src/model/base.py:7:4: R0903: Too few public methods (0/2) (too-few-public-methods)
app/src/model/base.py:4:0: R0903: Too few public methods (0/2) (too-few-public-methods)
app/src/model/base.py:13:0: R0903: Too few public methods (0/2) (too-few-public-methods)
app/src/model/base.py:2:0: W0611: Unused ValidationError imported from pydantic (unused-import)

------------------------------------------------------------------
Your code has been rated at 0.00/10 (previous run: 0.00/10, +0.00)
```

### Expected behavior

> No name 'BaseModel' in module 'pydantic' 

this error should not occur

### Pylint version

```shell
name         : pylint
 version      : 2.17.4
 description  : python code static checker

dependencies
 - astroid >=2.15.4,<=2.17.0-dev0
 - colorama >=0.4.5
 - dill >=0.3.6
 - isort >=4.2.5,<6
 - mccabe >=0.6,<0.8
 - platformdirs >=2.2.0
 - tomlkit >=0.10.1
```

### OS / Environment

Windows sub linux:
>  5.15.90.1-microsoft-standard-WSL2 

Python version:
> System
Platform:   linux
OS:         posix
Python:     3.11.1

### Additional dependencies

> pydantic==1.10.7

**Comment by mbyrnepr2** [comment]
Thanks @yinuu this requires an option to be passed:
```python
pylint  --extension-pkg-whitelist='pydantic' example.py
```

Duplicate of https://github.com/pylint-dev/pylint/issues/7486.
