### ISSUE TITLE
Pylint crashes with RuntimeError: dictionary changed size during iteration

### ISSUE THREAD

**Issue by matejsp** [pylint-dev/pylint#8928]
### Bug description

It seems that latest pylint crashes with dictionary change size during iteration.

### Command used

```shell
DJANGO_SETTINGS_MODULE=settings /opt/virtualenvs/py38/bin/pylint --recursive=y -j 8 --output-format=parseable *.py **/*.py
```

### Pylint output

```shell
Command used to do pylint: DJANGO_SETTINGS_MODULE=settings /opt/virtualenvs/py38/bin/pylint --recursive=y -j 8 --output-format=parseable *.py **/*.py 2> pylint_errors | grep -v "^************* "
Creating folders
Creating files
Found 0 pylint warnings on HEAD branch
Running pylint mode with zero pylint errors tolerance enabled
Exception on node <Import l.1 at 0x7ff21ec70f40> in file '/project/constants.py'
Traceback (most recent call last):
  File "/opt/virtualenvs/py38/lib64/python3.8/site-packages/pylint/checkers/imports.py", line 858, in _get_imported_module
    return importnode.do_import_module(modname)
  File "/opt/virtualenvs/py38/lib64/python3.8/site-packages/astroid/nodes/_base_nodes.py", line 146, in do_import_module
    return mymodule.import_module(
  File "/opt/virtualenvs/py38/lib64/python3.8/site-packages/astroid/nodes/scoped_nodes/scoped_nodes.py", line 530, in import_module
    return AstroidManager().ast_from_module_name(
  File "/opt/virtualenvs/py38/lib64/python3.8/site-packages/astroid/manager.py", line 246, in ast_from_module_name
    return self.ast_from_file(found_spec.location, modname, fallback=False)
  File "/opt/virtualenvs/py38/lib64/python3.8/site-packages/astroid/manager.py", line 138, in ast_from_file
    return AstroidBuilder(self).file_build(filepath, modname)
  File "/opt/virtualenvs/py38/lib64/python3.8/site-packages/astroid/builder.py", line 145, in file_build
    return self._post_build(module, builder, encoding)
  File "/opt/virtualenvs/py38/lib64/python3.8/site-packages/astroid/builder.py", line 169, in _post_build
    self.delayed_assattr(delayed)
  File "/opt/virtualenvs/py38/lib64/python3.8/site-packages/astroid/builder.py", line 240, in delayed_assattr
    for inferred in node.expr.infer():
  File "/opt/virtualenvs/py38/lib64/python3.8/site-packages/astroid/nodes/node_ng.py", line 171, in infer
    yield from self._infer(context=context, **kwargs)
  File "/opt/virtualenvs/py38/lib64/python3.8/site-packages/astroid/decorators.py", line 143, in raise_if_nothing_inferred
    yield next(generator)
  File "/opt/virtualenvs/py38/lib64/python3.8/site-packages/astroid/decorators.py", line 112, in wrapped
    for res in _func(node, context, **kwargs):
  File "/opt/virtualenvs/py38/lib64/python3.8/site-packages/astroid/bases.py", line 177, in _infer_stmts
    for inf in stmt.infer(context=context):
  File "/opt/virtualenvs/py38/lib64/python3.8/site-packages/astroid/nodes/node_ng.py", line 184, in infer
    for i, result in enumerate(self._infer(context=context, **kwargs)):
  File "/opt/virtualenvs/py38/lib64/python3.8/site-packages/astroid/decorators.py", line 143, in raise_if_nothing_inferred
    yield next(generator)
  File "/opt/virtualenvs/py38/lib64/python3.8/site-packages/astroid/decorators.py", line 112, in wrapped
    for res in _func(node, context, **kwargs):
  File "/opt/virtualenvs/py38/lib64/python3.8/site-packages/astroid/bases.py", line 177, in _infer_stmts
    for inf in stmt.infer(context=context):
  File "/opt/virtualenvs/py38/lib64/python3.8/site-packages/astroid/nodes/node_ng.py", line 184, in infer
    for i, result in enumerate(self._infer(context=context, **kwargs)):
  File "/opt/virtualenvs/py38/lib64/python3.8/site-packages/astroid/decorators.py", line 143, in raise_if_nothing_inferred
    yield next(generator)
  File "/opt/virtualenvs/py38/lib64/python3.8/site-packages/astroid/decorators.py", line 112, in wrapped
    for res in _func(node, context, **kwargs):
  File "/opt/virtualenvs/py38/lib64/python3.8/site-packages/astroid/inference.py", line 279, in infer_call
    yield from callee.infer_call_result(caller=self, context=callcontext)
  File "/opt/virtualenvs/py38/lib64/python3.8/site-packages/astroid/nodes/scoped_nodes/scoped_nodes.py", line 2291, in infer_call_result
    result = self._infer_type_call(caller, context)
  File "/opt/virtualenvs/py38/lib64/python3.8/site-packages/astroid/nodes/scoped_nodes/scoped_nodes.py", line 2242, in _infer_type_call
    name_node = next(caller.args[0].infer(context))
  File "/opt/virtualenvs/py38/lib64/python3.8/site-packages/astroid/nodes/node_ng.py", line 184, in infer
    for i, result in enumerate(self._infer(context=context, **kwargs)):
  File "/opt/virtualenvs/py38/lib64/python3.8/site-packages/astroid/decorators.py", line 143, in raise_if_nothing_inferred
    yield next(generator)
  File "/opt/virtualenvs/py38/lib64/python3.8/site-packages/astroid/decorators.py", line 112, in wrapped
    for res in _func(node, context, **kwargs):
  File "/opt/virtualenvs/py38/lib64/python3.8/site-packages/astroid/bases.py", line 177, in _infer_stmts
    for inf in stmt.infer(context=context):
  File "/opt/virtualenvs/py38/lib64/python3.8/site-packages/astroid/nodes/node_ng.py", line 184, in infer
    for i, result in enumerate(self._infer(context=context, **kwargs)):
  File "/opt/virtualenvs/py38/lib64/python3.8/site-packages/astroid/decorators.py", line 143, in raise_if_nothing_inferred
    yield next(generator)
  File "/opt/virtualenvs/py38/lib64/python3.8/site-packages/astroid/decorators.py", line 112, in wrapped
    for res in _func(node, context, **kwargs):
  File "/opt/virtualenvs/py38/lib64/python3.8/site-packages/astroid/bases.py", line 177, in _infer_stmts
    for inf in stmt.infer(context=context):
  File "/opt/virtualenvs/py38/lib64/python3.8/site-packages/astroid/nodes/node_ng.py", line 184, in infer
    for i, result in enumerate(self._infer(context=context, **kwargs)):
  File "/opt/virtualenvs/py38/lib64/python3.8/site-packages/astroid/decorators.py", line 143, in raise_if_nothing_inferred
    yield next(generator)
  File "/opt/virtualenvs/py38/lib64/python3.8/site-packages/astroid/decorators.py", line 112, in wrapped
    for res in _func(node, context, **kwargs):
  File "/opt/virtualenvs/py38/lib64/python3.8/site-packages/astroid/inference.py", line 270, in infer_call
    for callee in self.func.infer(context):
  File "/opt/virtualenvs/py38/lib64/python3.8/site-packages/astroid/nodes/node_ng.py", line 184, in infer
    for i, result in enumerate(self._infer(context=context, **kwargs)):
  File "/opt/virtualenvs/py38/lib64/python3.8/site-packages/astroid/decorators.py", line 143, in raise_if_nothing_inferred
    yield next(generator)
  File "/opt/virtualenvs/py38/lib64/python3.8/site-packages/astroid/decorators.py", line 112, in wrapped
    for res in _func(node, context, **kwargs):
  File "/opt/virtualenvs/py38/lib64/python3.8/site-packages/astroid/inference.py", line 358, in infer_attribute
    for owner in self.expr.infer(context):
  File "/opt/virtualenvs/py38/lib64/python3.8/site-packages/astroid/nodes/node_ng.py", line 184, in infer
    for i, result in enumerate(self._infer(context=context, **kwargs)):
  File "/opt/virtualenvs/py38/lib64/python3.8/site-packages/astroid/decorators.py", line 143, in raise_if_nothing_inferred
    yield next(generator)
  File "/opt/virtualenvs/py38/lib64/python3.8/site-packages/astroid/decorators.py", line 112, in wrapped
    for res in _func(node, context, **kwargs):
  File "/opt/virtualenvs/py38/lib64/python3.8/site-packages/astroid/bases.py", line 177, in _infer_stmts
    for inf in stmt.infer(context=context):
  File "/opt/virtualenvs/py38/lib64/python3.8/site-packages/astroid/nodes/node_ng.py", line 184, in infer
    for i, result in enumerate(self._infer(context=context, **kwargs)):
  File "/opt/virtualenvs/py38/lib64/python3.8/site-packages/astroid/decorators.py", line 143, in raise_if_nothing_inferred
    yield next(generator)
  File "/opt/virtualenvs/py38/lib64/python3.8/site-packages/astroid/decorators.py", line 112, in wrapped
    for res in _func(node, context, **kwargs):
  File "/opt/virtualenvs/py38/lib64/python3.8/site-packages/astroid/inference.py", line 304, in infer_import
    yield self.do_import_module(self.real_name(name))
  File "/opt/virtualenvs/py38/lib64/python3.8/site-packages/astroid/nodes/_base_nodes.py", line 146, in do_import_module
    return mymodule.import_module(
  File "/opt/virtualenvs/py38/lib64/python3.8/site-packages/astroid/nodes/scoped_nodes/scoped_nodes.py", line 530, in import_module
    return AstroidManager().ast_from_module_name(
  File "/opt/virtualenvs/py38/lib64/python3.8/site-packages/astroid/manager.py", line 221, in ast_from_module_name
    return self.ast_from_module(named_module, modname)
  File "/opt/virtualenvs/py38/lib64/python3.8/site-packages/astroid/manager.py", line 328, in ast_from_module
    return AstroidBuilder(self).module_build(module, modname)
  File "/opt/virtualenvs/py38/lib64/python3.8/site-packages/astroid/builder.py", line 101, in module_build
    node = self.inspect_build(module, modname=modname, path=path)
  File "/opt/virtualenvs/py38/lib64/python3.8/site-packages/astroid/raw_building.py", line 404, in inspect_build
    self.object_build(node, module)
  File "/opt/virtualenvs/py38/lib64/python3.8/site-packages/astroid/raw_building.py", line 455, in object_build
    attach_const_node(node, name, member)
  File "/opt/virtualenvs/py38/lib64/python3.8/site-packages/astroid/raw_building.py", line 78, in attach_const_node
    _attach_local_node(node, nodes.const_factory(value), name)
  File "/opt/virtualenvs/py38/lib64/python3.8/site-packages/astroid/nodes/node_classes.py", line 5641, in const_factory
    instance.postinit(_create_dict_items(value, instance))
  File "/opt/virtualenvs/py38/lib64/python3.8/site-packages/astroid/nodes/node_classes.py", line 5612, in _create_dict_items
    for key, value in values.items():
RuntimeError: dictionary changed size during iteration

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/opt/virtualenvs/py38/lib64/python3.8/site-packages/pylint/utils/ast_walker.py", line 91, in walk
    callback(astroid)
  File "/opt/virtualenvs/py38/lib64/python3.8/site-packages/pylint/checkers/imports.py", line 534, in visit_import
    imported_module = self._get_imported_module(node, name)
  File "/opt/virtualenvs/py38/lib64/python3.8/site-packages/pylint/checkers/imports.py", line 883, in _get_imported_module
    raise astroid.AstroidError from e
astroid.exceptions.AstroidError
Exception on node <Import l.4 at 0x7ff21ebada30> in file '/bitstamp/pair_constants.py'
Traceback (most recent call last):
  File "/opt/virtualenvs/py38/lib64/python3.8/site-packages/pylint/checkers/imports.py", line 858, in _get_imported_module
    return importnode.do_import_module(modname)
  File "/opt/virtualenvs/py38/lib64/python3.8/site-packages/astroid/nodes/_base_nodes.py", line 146, in do_import_module
    return mymodule.import_module(
  File "/opt/virtualenvs/py38/lib64/python3.8/site-packages/astroid/nodes/scoped_nodes/scoped_nodes.py", line 530, in import_module
    return AstroidManager().ast_from_module_name(
  File "/opt/virtualenvs/py38/lib64/python3.8/site-packages/astroid/manager.py", line 246, in ast_from_module_name
    return self.ast_from_file(found_spec.location, modname, fallback=False)
  File "/opt/virtualenvs/py38/lib64/python3.8/site-packages/astroid/manager.py", line 138, in ast_from_file
    return AstroidBuilder(self).file_build(filepath, modname)
  File "/opt/virtualenvs/py38/lib64/python3.8/site-packages/astroid/builder.py", line 145, in file_build
    return self._post_build(module, builder, encoding)
  File "/opt/virtualenvs/py38/lib64/python3.8/site-packages/astroid/builder.py", line 169, in _post_build
    self.delayed_assattr(delayed)
  File "/opt/virtualenvs/py38/lib64/python3.8/site-packages/astroid/builder.py", line 240, in delayed_assattr
    for inferred in node.expr.infer():
  File "/opt/virtualenvs/py38/lib64/python3.8/site-packages/astroid/nodes/node_ng.py", line 171, in infer
    yield from self._infer(context=context, **kwargs)
  File "/opt/virtualenvs/py38/lib64/python3.8/site-packages/astroid/decorators.py", line 143, in raise_if_nothing_inferred
    yield next(generator)
  File "/opt/virtualenvs/py38/lib64/python3.8/site-packages/astroid/decorators.py", line 112, in wrapped
    for res in _func(node, context, **kwargs):
  File "/opt/virtualenvs/py38/lib64/python3.8/site-packages/astroid/bases.py", line 177, in _infer_stmts
    for inf in stmt.infer(context=context):
  File "/opt/virtualenvs/py38/lib64/python3.8/site-packages/astroid/nodes/node_ng.py", line 184, in infer
    for i, result in enumerate(self._infer(context=context, **kwargs)):
  File "/opt/virtualenvs/py38/lib64/python3.8/site-packages/astroid/decorators.py", line 143, in raise_if_nothing_inferred
    yield next(generator)
  File "/opt/virtualenvs/py38/lib64/python3.8/site-packages/astroid/decorators.py", line 112, in wrapped
    for res in _func(node, context, **kwargs):
  File "/opt/virtualenvs/py38/lib64/python3.8/site-packages/astroid/bases.py", line 177, in _infer_stmts
    for inf in stmt.infer(context=context):
  File "/opt/virtualenvs/py38/lib64/python3.8/site-packages/astroid/nodes/node_ng.py", line 184, in infer
    for i, result in enumerate(self._infer(context=context, **kwargs)):
  File "/opt/virtualenvs/py38/lib64/python3.8/site-packages/astroid/decorators.py", line 143, in raise_if_nothing_inferred
    yield next(generator)
  File "/opt/virtualenvs/py38/lib64/python3.8/site-packages/astroid/decorators.py", line 112, in wrapped
    for res in _func(node, context, **kwargs):
  File "/opt/virtualenvs/py38/lib64/python3.8/site-packages/astroid/inference.py", line 279, in infer_call
    yield from callee.infer_call_result(caller=self, context=callcontext)
  File "/opt/virtualenvs/py38/lib64/python3.8/site-packages/astroid/nodes/scoped_nodes/scoped_nodes.py", line 2291, in infer_call_result
    result = self._infer_type_call(caller, context)
  File "/opt/virtualenvs/py38/lib64/python3.8/site-packages/astroid/nodes/scoped_nodes/scoped_nodes.py", line 2242, in _infer_type_call
    name_node = next(caller.args[0].infer(context))
  File "/opt/virtualenvs/py38/lib64/python3.8/site-packages/astroid/nodes/node_ng.py", line 184, in infer
    for i, result in enumerate(self._infer(context=context, **kwargs)):
  File "/opt/virtualenvs/py38/lib64/python3.8/site-packages/astroid/decorators.py", line 143, in raise_if_nothing_inferred
    yield next(generator)
  File "/opt/virtualenvs/py38/lib64/python3.8/site-packages/astroid/decorators.py", line 112, in wrapped
    for res in _func(node, context, **kwargs):
  File "/opt/virtualenvs/py38/lib64/python3.8/site-packages/astroid/bases.py", line 177, in _infer_stmts
    for inf in stmt.infer(context=context):
  File "/opt/virtualenvs/py38/lib64/python3.8/site-packages/astroid/nodes/node_ng.py", line 184, in infer
    for i, result in enumerate(self._infer(context=context, **kwargs)):
  File "/opt/virtualenvs/py38/lib64/python3.8/site-packages/astroid/decorators.py", line 143, in raise_if_nothing_inferred
    yield next(generator)
  File "/opt/virtualenvs/py38/lib64/python3.8/site-packages/astroid/decorators.py", line 112, in wrapped
    for res in _func(node, context, **kwargs):
  File "/opt/virtualenvs/py38/lib64/python3.8/site-packages/astroid/bases.py", line 177, in _infer_stmts
    for inf in stmt.infer(context=context):
  File "/opt/virtualenvs/py38/lib64/python3.8/site-packages/astroid/nodes/node_ng.py", line 184, in infer
    for i, result in enumerate(self._infer(context=context, **kwargs)):
  File "/opt/virtualenvs/py38/lib64/python3.8/site-packages/astroid/decorators.py", line 143, in raise_if_nothing_inferred
    yield next(generator)
  File "/opt/virtualenvs/py38/lib64/python3.8/site-packages/astroid/decorators.py", line 112, in wrapped
    for res in _func(node, context, **kwargs):
  File "/opt/virtualenvs/py38/lib64/python3.8/site-packages/astroid/inference.py", line 270, in infer_call
    for callee in self.func.infer(context):
  File "/opt/virtualenvs/py38/lib64/python3.8/site-packages/astroid/nodes/node_ng.py", line 184, in infer
    for i, result in enumerate(self._infer(context=context, **kwargs)):
  File "/opt/virtualenvs/py38/lib64/python3.8/site-packages/astroid/decorators.py", line 143, in raise_if_nothing_inferred
    yield next(generator)
  File "/opt/virtualenvs/py38/lib64/python3.8/site-packages/astroid/decorators.py", line 112, in wrapped
    for res in _func(node, context, **kwargs):
  File "/opt/virtualenvs/py38/lib64/python3.8/site-packages/astroid/inference.py", line 358, in infer_attribute
    for owner in self.expr.infer(context):
  File "/opt/virtualenvs/py38/lib64/python3.8/site-packages/astroid/nodes/node_ng.py", line 184, in infer
    for i, result in enumerate(self._infer(context=context, **kwargs)):
  File "/opt/virtualenvs/py38/lib64/python3.8/site-packages/astroid/decorators.py", line 143, in raise_if_nothing_inferred
    yield next(generator)
  File "/opt/virtualenvs/py38/lib64/python3.8/site-packages/astroid/decorators.py", line 112, in wrapped
    for res in _func(node, context, **kwargs):
  File "/opt/virtualenvs/py38/lib64/python3.8/site-packages/astroid/bases.py", line 177, in _infer_stmts
    for inf in stmt.infer(context=context):
  File "/opt/virtualenvs/py38/lib64/python3.8/site-packages/astroid/nodes/node_ng.py", line 184, in infer
    for i, result in enumerate(self._infer(context=context, **kwargs)):
  File "/opt/virtualenvs/py38/lib64/python3.8/site-packages/astroid/decorators.py", line 143, in raise_if_nothing_inferred
    yield next(generator)
  File "/opt/virtualenvs/py38/lib64/python3.8/site-packages/astroid/decorators.py", line 112, in wrapped
    for res in _func(node, context, **kwargs):
  File "/opt/virtualenvs/py38/lib64/python3.8/site-packages/astroid/inference.py", line 304, in infer_import
    yield self.do_import_module(self.real_name(name))
  File "/opt/virtualenvs/py38/lib64/python3.8/site-packages/astroid/nodes/_base_nodes.py", line 146, in do_import_module
    return mymodule.import_module(
  File "/opt/virtualenvs/py38/lib64/python3.8/site-packages/astroid/nodes/scoped_nodes/scoped_nodes.py", line 530, in import_module
    return AstroidManager().ast_from_module_name(
  File "/opt/virtualenvs/py38/lib64/python3.8/site-packages/astroid/manager.py", line 221, in ast_from_module_name
    return self.ast_from_module(named_module, modname)
  File "/opt/virtualenvs/py38/lib64/python3.8/site-packages/astroid/manager.py", line 328, in ast_from_module
    return AstroidBuilder(self).module_build(module, modname)
  File "/opt/virtualenvs/py38/lib64/python3.8/site-packages/astroid/builder.py", line 101, in module_build
    node = self.inspect_build(module, modname=modname, path=path)
  File "/opt/virtualenvs/py38/lib64/python3.8/site-packages/astroid/raw_building.py", line 404, in inspect_build
    self.object_build(node, module)
  File "/opt/virtualenvs/py38/lib64/python3.8/site-packages/astroid/raw_building.py", line 455, in object_build
    attach_const_node(node, name, member)
  File "/opt/virtualenvs/py38/lib64/python3.8/site-packages/astroid/raw_building.py", line 78, in attach_const_node
    _attach_local_node(node, nodes.const_factory(value), name)
  File "/opt/virtualenvs/py38/lib64/python3.8/site-packages/astroid/nodes/node_classes.py", line 5641, in const_factory
    instance.postinit(_create_dict_items(value, instance))
  File "/opt/virtualenvs/py38/lib64/python3.8/site-packages/astroid/nodes/node_classes.py", line 5612, in _create_dict_items
    for key, value in values.items():
RuntimeError: dictionary changed size during iteration

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/opt/virtualenvs/py38/lib64/python3.8/site-packages/pylint/utils/ast_walker.py", line 91, in walk
    callback(astroid)
  File "/opt/virtualenvs/py38/lib64/python3.8/site-packages/pylint/checkers/imports.py", line 534, in visit_import
    imported_module = self._get_imported_module(node, name)
  File "/opt/virtualenvs/py38/lib64/python3.8/site-packages/pylint/checkers/imports.py", line 883, in _get_imported_module
    raise astroid.AstroidError from e
astroid.exceptions.AstroidError
concurrent.futures.process._RemoteTraceback: 
"""
Traceback (most recent call last):
  File "/opt/virtualenvs/py38/lib64/python3.8/site-packages/pylint/lint/pylinter.py", line 854, in _check_file
    check_astroid_module(ast_node)
  File "/opt/virtualenvs/py38/lib64/python3.8/site-packages/pylint/lint/pylinter.py", line 1085, in check_astroid_module
    retval = self._check_astroid_module(
  File "/opt/virtualenvs/py38/lib64/python3.8/site-packages/pylint/lint/pylinter.py", line 1135, in _check_astroid_module
    walker.walk(node)
  File "/opt/virtualenvs/py38/lib64/python3.8/site-packages/pylint/utils/ast_walker.py", line 94, in walk
    self.walk(child)
  File "/opt/virtualenvs/py38/lib64/python3.8/site-packages/pylint/utils/ast_walker.py", line 91, in walk
    callback(astroid)
  File "/opt/virtualenvs/py38/lib64/python3.8/site-packages/pylint/checkers/imports.py", line 534, in visit_import
    imported_module = self._get_imported_module(node, name)
  File "/opt/virtualenvs/py38/lib64/python3.8/site-packages/pylint/checkers/imports.py", line 883, in _get_imported_module
    raise astroid.AstroidError from e
astroid.exceptions.AstroidError

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/lib64/python3.8/concurrent/futures/process.py", line 239, in _process_worker
    r = call_item.fn(*call_item.args, **call_item.kwargs)
  File "/usr/lib64/python3.8/concurrent/futures/process.py", line 198, in _process_chunk
    return [fn(*args) for args in chunk]
  File "/usr/lib64/python3.8/concurrent/futures/process.py", line 198, in <listcomp>
    return [fn(*args) for args in chunk]
  File "/opt/virtualenvs/py38/lib64/python3.8/site-packages/pylint/lint/parallel.py", line 76, in _worker_check_single_file
    _worker_linter.check_single_file_item(file_item)
  File "/opt/virtualenvs/py38/lib64/python3.8/site-packages/pylint/lint/pylinter.py", line 763, in check_single_file_item
    self._check_file(self.get_ast, check_astroid_module, file)
  File "/opt/virtualenvs/py38/lib64/python3.8/site-packages/pylint/lint/pylinter.py", line 856, in _check_file
    raise astroid.AstroidError from e
astroid.exceptions.AstroidError
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/opt/virtualenvs/py38/bin/pylint", line 8, in <module>
    sys.exit(run_pylint())
  File "/opt/virtualenvs/py38/lib64/python3.8/site-packages/pylint/__init__.py", line 36, in run_pylint
    PylintRun(argv or sys.argv[1:])
  File "/opt/virtualenvs/py38/lib64/python3.8/site-packages/pylint/lint/run.py", line 215, in __init__
    linter.check(args)
  File "/opt/virtualenvs/py38/lib64/python3.8/site-packages/pylint/lint/pylinter.py", line 693, in check
    check_parallel(
  File "/opt/virtualenvs/py38/lib64/python3.8/site-packages/pylint/lint/parallel.py", line 158, in check_parallel
    for (
  File "/usr/lib64/python3.8/concurrent/futures/process.py", line 484, in _chain_from_iterable_of_lists
    for element in iterable:
  File "/usr/lib64/python3.8/concurrent/futures/_base.py", line 619, in result_iterator
    yield fs.pop().result()
  File "/usr/lib64/python3.8/concurrent/futures/_base.py", line 444, in result
    return self.__get_result()
  File "/usr/lib64/python3.8/concurrent/futures/_base.py", line 389, in __get_result
    raise self._exception
astroid.exceptions.AstroidError
Pylint should not crash while checking code, please fix incompatibilities.
```

### Expected behavior

It should not crash

### Pylint version

```shell
pylint 2.17.5
astroid 2.15.6
Python 3.8.16 (default, Mar 10 2023, 03:07:48) 
[GCC 7.3.1 20180712 (Red Hat 7.3.1-15)]
```

### OS / Environment

Amazon Linux 2

**Comment by jacobtylerwalls** [comment]
Thanks for the report. This is the second time it's been reported, so I'll close as a duplicate and retitle the original report. Unfortunately, no one knows how to reproduce the issue. Can you share the import statement on line 1 of `project/constants.py` that is failing? Thank you!
