### ISSUE TITLE
Get astroid.exceptions.InferenceError trying to call object() method from dict item

### ISSUE THREAD

**Issue by aledotdev** [pylint-dev/pylint#8963]
### Bug description

Got an error when a I run pylint for unittest with mocks
It looks like `astroid` has problems with the attr `objects` in a dict item

Fails:
```python
from unittest import mock
def test_pylint_error():
    with mock.patch.multiple("test_user", User=mock.DEFAULT) as mocks:
        mocks["User"].objects().get.return_value = "123"
```

Works:
```python
from unittest import mock
def test_pylint_error():
    with mock.patch.multiple("test_user", User=mock.DEFAULT) as mocks:
        User_mock = mocks["User"]
        User_mock.objects().get.return_value = "123"
```

### Command used

```shell
pylint ./test_pylint.py
```

### Pylint output

```shell
Exception on node <Attribute.objects l.5 at 0x7fcaa07d29b0> in file '/code/test_ppp.py'
Traceback (most recent call last):
  File "/code/envs/ds/lib/python3.10/site-packages/astroid/inference.py", line 450, in infer_subscript
    assigned = value.getitem(index_value, context)
  File "/code/envs/ds/lib/python3.10/site-packages/astroid/nodes/node_classes.py", line 2474, in getitem
    raise AstroidIndexError(index)
astroid.exceptions.AstroidIndexError: <unprintable AstroidIndexError object>

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/code/envs/ds/lib/python3.10/site-packages/pylint/utils/ast_walker.py", line 91, in walk
    callback(astroid)
  File "/code/envs/ds/lib/python3.10/site-packages/pylint_plugin_utils/__init__.py", line 55, in augment_func
    augmentation(chain, node)
  File "/code/envs/ds/lib/python3.10/site-packages/pylint_plugin_utils/__init__.py", line 144, in do_suppress
    if test_func(node):
  File "/code/envs/ds/lib/python3.10/site-packages/pylint_mongoengine/utils.py", line 115, in node_is_default_qs
    for cls in base_cls.inferred():
  File "/code/envs/ds/lib/python3.10/site-packages/astroid/nodes/node_ng.py", line 613, in inferred
    return list(self.infer())
  File "/code/envs/ds/lib/python3.10/site-packages/astroid/nodes/node_ng.py", line 171, in infer
    yield from self._infer(context=context, **kwargs)
  File "/code/envs/ds/lib/python3.10/site-packages/astroid/decorators.py", line 143, in raise_if_nothing_inferred
    yield next(generator)
  File "/code/envs/ds/lib/python3.10/site-packages/astroid/decorators.py", line 112, in wrapped
    for res in _func(node, context, **kwargs):
  File "/code/envs/ds/lib/python3.10/site-packages/astroid/inference.py", line 458, in infer_subscript
    raise InferenceError(node=self, context=context) from exc
astroid.exceptions.InferenceError: Inference failed for <Subscript l.5 at 0x7fcaa07d2980>.
************* Module test_ppp
test_ppp.py:1:0: F0002: test_ppp.py: Fatal error while checking 'test_ppp.py'. Please open an issue in our bug tracker so we address this. There is a pre-filled template that you can use in '/.cache/pylint/pylint-crash-2023-08-18-16-27-38.txt'. (astroid-error)

--------------------------------------------------------------------
Your code has been rated at 0.00/10 (previous run: 10.00/10, -10.00)
```

### Expected behavior

Your code has been rated at 10.00/10 (previous run: 0.00/10, +10.00)

### Pylint version

```shell
- Python 3.10.9
- astroid==2.15.6
- pylint==2.17.5
- pylint-ignore==2021.1024
- pylint-mongoengine==0.4.0
- pylint-plugin-utils==0.6
```

### OS / Environment

Description:	Ubuntu 22.04.3 LTS
Release:	22.04
Codename:	jammy

**Comment by Pierre-Sassoulas** [comment]
Thank you for opening the issue. I cannot reproduce this, either on main or using 2.17.5:
```
pylint 2.17.5
astroid 2.15.6
Python 3.10.12 (main, Jun 11 2023, 05:26:28) [GCC 11.4.0]
```
```
$ pip3 freeze|grep pylint
-e git+ssh://git@github.com/pylint-dev/pylint.git@fe161df35f639e0ded268426d50551d174c6bd13#egg=pylint
pylint-ignore==2021.1024
pylint-mongoengine==0.4.0
pylint-plugin-utils==0.6
```
Would you mind testing if the problem still happens for you using the latest release (3.0.0a7) ?
