### ISSUE TITLE
Pylint installation fails after the recent release

### ISSUE THREAD

**Issue by Alexander-Serov** [pylint-dev/pylint#9105]
### Bug description

```python
Pre-commit hook with pylint that has been working previously is not failing with the new pylint version released:


pylint...................................................................Failed
- hook id: pylint
- exit code: 1
Traceback (most recent call last):
  File "/builds/project/venv/bin/pylint", line 8, in <module>
    sys.exit(run_pylint())
  File "/builds/buynomics/project/venv/lib/python3.8/site-packages/pylint/__init__.py", line 34, in run_pylint
    PylintRun(argv or sys.argv[1:])
  File "/builds/project/venv/lib/python3.8/site-packages/pylint/lint/run.py", line 162, in __init__
    args = _config_initialization(
  File "/builds/project/venv/lib/python3.8/site-packages/pylint/config/config_initialization.py", line 57, in _config_initialization
    exec(utils._unquote(config_data["init-hook"]))  # pylint: disable=exec-used
  File "<string>", line 1, in <module>
ImportError: cannot import name 'find_pylintrc' from 'pylint.config' (/builds/project/venv/lib/python3.8/site-packages/pylint/config/__init__.py)
Traceback (most recent call last):
  File "/builds/project/venv/bin/pylint", line 8, in <module>
    sys.exit(run_pylint())
  File "/builds/project/venv/lib/python3.8/site-packages/pylint/__init__.py", line 34, in run_pylint
    PylintRun(argv or sys.argv[1:])
  File "/builds/project/venv/lib/python3.8/site-packages/pylint/lint/run.py", line 162, in __init__
    args = _config_initialization(
  File "/builds/project/venv/lib/python3.8/site-packages/pylint/config/config_initialization.py", line 57, in _config_initialization
    exec(utils._unquote(config_data["init-hook"]))  # pylint: disable=exec-used
  File "<string>", line 1, in <module>
ImportError: cannot import name 'find_pylintrc' from 'pylint.config' (/builds/project/venv/lib/python3.8/site-packages/pylint/config/__init__.py)
```

Downgrading to pylint==2.17 solves the problem.
```


### Configuration

```ini
The configuration has not changed from the previous version. My pre-commit configuration:


  - repo: local
    hooks:
      - id: pylint
        name: pylint
        entry: pylint
        language: system
        types: [python]
        args: [--errors-only]
```
```


### Command used

```shell
pre-commit run pylint
```

### Pylint output

```python
Not starting, see above
```

### Expected behavior

Same behavior as in 2.17

### Pylint version

```shell
pylint 3.0.0
astroid 3.0.0
python 3.8
```

### OS / Environment

Linux / Macos

**Comment by Alexander-Serov** [comment]
@Pierre-Sassoulas Do you think it could be related to your recent 3.0.0 release?

**Comment by Alexander-Serov** [comment]
> Hi @Alexander-Serov 👋
> 
> The release notes are a bit long, but it's in there 😉 :
> 
> > Following a deprecation period, pylint.config.PYLINTRC was removed.
> > Use the pylint.config.find_default_config_files generator instead.
> 
> Duplicate of #8862

Thanks for identifying it fast. So just to be sure I understood the discussion in the other thread correctly: the .pylintrc has been deprecated and one should migrate the config to `pyproject.toml` instead, right?

**Comment by jacobtylerwalls** [comment]
> Thanks for identifying it fast. So just to be sure I understood the discussion in the other thread correctly: the .pylintrc has been deprecated and one should migrate the config to pyproject.toml instead, right?

Ah, no! rc files are still fine. You can provide an exact path or rely on the discovery in the order given [here](https://pylint.readthedocs.io/en/stable/user_guide/usage/run.html#command-line-options).

**Comment by Alexander-Serov** [comment]
Thanks, @jacobtylerwalls, it does.

**Comment by jacobtylerwalls** [comment]
cc/ @DanielNoord for future, it's occurring to me now that pre-commit hooks probably swallow deprecation warnings. Not sure what to make of that, just hadn't thought of that before.

**Comment by DanielNoord** [comment]
Yeah, makes sense. The amount of plugin related issues also seems to confirm this..

Good call on changing the name, let's hope people find these issues before opening new ones.

**Comment by genzgd** [comment]
This is a byproduct of the approach for setting the sys/PYTHONPATH recommended here:  https://stackoverflow.com/questions/1899436/pylint-unable-to-import-error-how-to-set-pythonpath.  A "best practices" approach for this problem should probably be highly visible somewhere here in this Github repo.
