### ISSUE TITLE
Python 3.12 - ValueError: generator already executing

### ISSUE THREAD

**Issue by sivel** [pylint-dev/pylint#9138]
### Bug description

It seems that with a combination of a commit to astroid, and a change in Python 3.12, I am getting a `ValueError: generator already executing`.

* https://github.com/pylint-dev/astroid/commit/c5352d53bc728816836a217428cac2eb305a0d55
* https://github.com/python/cpython/commit/6968f9e4d3593610b60c1140f04de275ff40cd41

Unfortunately, despite about 12 hours of trying, I don't have a simple reproducer, and this will involve running pylint against https://github.com/ansible/ansible

I've logged here instead of directly against astroid, as I was not able to find an easy way to cause the error with astroid alone.

### Configuration

```ini
N/A
```

### Command used

```shell
git clone git@github.com:ansible/ansible.git
cd ansible
python3.12 -m pylint lib/ansible/playbook/base.py > /dev/null
```

### Pylint output

```python
Traceback (most recent call last):
  File ".../astroid/astroid/decorators.py", line 104, in inner
    yield from generator
ValueError: generator already executing
```

If I insert additional debugging into astroid, to use `traceback.print_stack()` when that `ValueError` happens, I see something like:

<details>
<summary>Traceback...</summary>
<p>

```
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File ".../lib/python3.12/site-packages/pylint/__main__.py", line 10, in <module>
    pylint.run_pylint()
  File ".../lib/python3.12/site-packages/pylint/__init__.py", line 34, in run_pylint
    PylintRun(argv or sys.argv[1:])
  File ".../lib/python3.12/site-packages/pylint/lint/run.py", line 211, in __init__
    linter.check(args)
  File ".../lib/python3.12/site-packages/pylint/lint/pylinter.py", line 704, in check
    self._lint_files(ast_per_fileitem, check_astroid_module)
  File ".../lib/python3.12/site-packages/pylint/lint/pylinter.py", line 752, in _lint_files
    self._lint_file(fileitem, module, check_astroid_module)
  File ".../lib/python3.12/site-packages/pylint/lint/pylinter.py", line 788, in _lint_file
    check_astroid_module(module)
  File ".../lib/python3.12/site-packages/pylint/lint/pylinter.py", line 1017, in check_astroid_module
    retval = self._check_astroid_module(
  File ".../lib/python3.12/site-packages/pylint/lint/pylinter.py", line 1069, in _check_astroid_module
    walker.walk(node)
  File ".../lib/python3.12/site-packages/pylint/utils/ast_walker.py", line 94, in walk
    self.walk(child)
  File ".../lib/python3.12/site-packages/pylint/utils/ast_walker.py", line 94, in walk
    self.walk(child)
  File ".../lib/python3.12/site-packages/pylint/utils/ast_walker.py", line 94, in walk
    self.walk(child)
  File ".../lib/python3.12/site-packages/pylint/utils/ast_walker.py", line 91, in walk
    callback(astroid)
  File ".../lib/python3.12/site-packages/pylint/checkers/typecheck.py", line 1440, in visit_call
    called, implicit_args, callable_name = _determine_callable(called)
  File ".../lib/python3.12/site-packages/pylint/checkers/typecheck.py", line 636, in _determine_callable
    new = callable_obj.local_attr("__new__")[-1]
  File ".../astroid/astroid/nodes/scoped_nodes/scoped_nodes.py", line 2327, in local_attr
    class_node = next(self.local_attr_ancestors(name, context), None)
  File ".../astroid/astroid/nodes/scoped_nodes/scoped_nodes.py", line 2279, in local_attr_ancestors
    ancestors: Iterable[ClassDef] = self.mro(context)[1:]
  File ".../astroid/astroid/nodes/scoped_nodes/scoped_nodes.py", line 2924, in mro
    return self._compute_mro(context=context)
  File ".../astroid/astroid/nodes/scoped_nodes/scoped_nodes.py", line 2893, in _compute_mro
    inferred_bases = list(self._inferred_bases(context=context))
  File ".../astroid/astroid/nodes/scoped_nodes/scoped_nodes.py", line 2873, in _inferred_bases
    baseobj = next(
  File ".../astroid/astroid/decorators.py", line 56, in wrapped
    yield res
  File ".../astroid/astroid/bases.py", line 181, in _infer_stmts
    yield inf
  File ".../astroid/astroid/nodes/node_ng.py", line 175, in infer
    yield result
  File ".../astroid/astroid/decorators.py", line 56, in wrapped
    yield res
  File ".../astroid/astroid/bases.py", line 181, in _infer_stmts
    yield inf
  File ".../astroid/astroid/nodes/node_ng.py", line 175, in infer
    yield result
  File ".../astroid/astroid/decorators.py", line 56, in wrapped
    yield res
  File ".../astroid/astroid/bases.py", line 181, in _infer_stmts
    yield inf
  File ".../astroid/astroid/nodes/node_ng.py", line 175, in infer
    yield result
  File ".../astroid/astroid/decorators.py", line 56, in wrapped
    yield res
  File ".../astroid/astroid/nodes/node_ng.py", line 175, in infer
    yield result
  File ".../astroid/astroid/decorators.py", line 107, in inner
    traceback.print_stack(file=sys.stderr)
```

</p>
</details>

### Expected behavior

No traceback

### Pylint version

```shell
astroid 3.0.0
pylint 3.0.1
Python 3.12.0
```

### OS / Environment

N/A

### Additional dependencies

```
N/A
```

**Comment by sivel** [comment]
Based on my very non-expert research, it seems that due to using `cls.is_subclass_of('eum.Enum')` has caused `.ancestors()` to be called and `.infer()`, and that is somehow interfering with the ability to compute the mro in `_compute_mro` which also calls `.infer()`.  As to exactly how, I'm at a little bit of a loss.

**Comment by jacobtylerwalls** [comment]
Thanks for the report. I've seen this from time to time. Do you have any sense of the severity of this issue?

**Comment by sivel** [comment]
This is preventing us from upgrading to pylint 3, as well as switching our default python version to py3.12.  This not only affects the CI for ansible/ansible, but content authors using our `ansible-test` tooling.

It will also cause issues with the ability for Fedora (or other distros switching to python3.12 as their default) to package ansible, due to Fedora 39 needing to include pylint 3 as a result of their inclusion of Python 3.12.  As such, ansible-test installed from their packages will be partially unusable.

**Comment by jacobtylerwalls** [comment]
Thanks for the extra details. I was wondering if the error was thrown only in object finalization after pylint's main program finishes. Obviously we need to clean it up either way, but this sounds more serious than the error I'd seen from time to time before.

**Comment by sivel** [comment]
The exception output is interspersed in the normal output from pylint.  So it doesn't seem necessarily to happen at the very end.  I'm unsure exactly the internal timing of things, it could be in object finalization, but it doesn't seem to be after the main program finishes.

```
[SNIP]
lib/ansible/playbook/base.py:435:12: W0201: Attribute '_ds' defined outside __init__ (attribute-defined-outside-init)
lib/ansible/playbook/base.py:716:0: C0115: Missing class docstring (missing-class-docstring)
Traceback (most recent call last):
  File "/Users/sivel/projects/ansibledev/astroid/astroid/decorators.py", line 104, in inner
    yield from generator
ValueError: generator already executing
lib/ansible/playbook/base.py:739:58: E1101: Module 'ansible.constants' has no 'ANY_ERRORS_FATAL' member (no-member)
lib/ansible/playbook/base.py:741:48: E1101: Module 'ansible.constants' has no 'TASK_TIMEOUT' member (no-member)
[SNIP]
```

**Comment by nickdrozd** [comment]
I don't know if it's of any use, but here's a whittled-down version of that `base.py` file that reproduces the error:

```python
from ansible.plugins.loader import action_loader

class FieldAttributeBase:
    def _load_module_defaults(self):
        resolved_action = self._resolve_action()
        if resolved_action:
            validated_defaults_dict[resolved_action] = defaults

        if True:
            resolved_action = self._resolve_action()
            if resolved_action:
                validated_defaults_dict[resolved_action] = defaults

    def _resolve_action(self):
        prefer = action_loader.find_plugin_with_context()

        if prefer.resolved:
            return prefer.resolved_fqcn
```

**Comment by nitzmahone** [comment]
Yeah, at least cuts down on the signal/noise ratio while beating on it- thanks!

**Comment by nickdrozd** [comment]
Here is an even smaller reproducer. It doesn't import anything else from the library, but it still has to be linted from inside the library (replacing `base.py`) for the `ValueError` to surface.

I think an inference around `importlib` is ultimately the source of the problem.

```python
# pylint: disable = line-too-long, missing-function-docstring, missing-module-docstring, missing-class-docstring, too-few-public-methods

# pylint: disable = no-member, using-constant-test, protected-access, attribute-defined-outside-init, undefined-variable

from importlib import import_module


class PluginLoadContext:
    @property
    def resolved_fqcn(self):
        if True:
            return None

        return self._resolved_fqcn


class PluginLoader:
    def find_plugin_with_context(self):
        _ = import_module('asdf').__file__

        if self._load_module_source():
            self._module_cache[None] = None

        self._load_config_defs()

        self._display_plugin_load()

        if self._plugin_instance_cache:
            self._plugin_instance_cache[None] = self._plugin_instance_cache[None]

        self._load_config_defs()

        if self.undefined:
            __import__()

        PluginLoadContext()._resolved_fqcn = undefined

        resolved_action = self._resolve_action()

        if resolved_action:
            {}[resolved_action] = None

        return PluginLoadContext()

    def _resolve_action(self):
        prefer = PluginLoader().find_plugin_with_context()

        if prefer.resolved:
            return prefer.resolved_fqcn

        return None
```

After all the disables, Pylint gives this 10/10, even with the `ValueError`.

**Comment by nitzmahone** [comment]
We've updated our CI to use a (hopefully temporary) plugin that installs a custom `sys.unraisablehook` on 3.12+ to mask this specific issue (while delegating anything else to the previous unraisablehook).

After spending the majority of the past several days digging pretty deeply into this (including hacking a bunch of instrumentation into CPython's `genobject.c`), I still think it's ultimately a 3.12 regression around generator finalization/close when a `yield from` is involved. Even with the minimized repro that @nickdrozd posted yesterday (thanks again!), it still requires evaluation under the context of the Ansible codebase to manifest the issue, so the resultant wad of subgenerators is quite deep and difficult to navigate (the "needle in a stack of needles" problem, since there are *so* many of them involved in the run, most of which behave normally and are very short-lived). There's also an awful lot of caching involved in astroid- disabling nearly any of it "fixes" the repro, so it might also be possible that a generator instance is sneaking into one of those caches, or somehow being aliased in a way that causes the problem, but it seems like that would also manifest under < 3.12.

Once I hacked in enough instrumentation to be able to roughly correlate the C-side generator wakeups to their associated Python frames, it appears that the issue is around a re-entrant C-side wakeup that's kicked off when a particular abandoned `Attribute._infer` generator (decorated with `path_wrapper` and `raise_if_nothing_inferred`) gets finalized. With this repro, the `raise_if_nothing_inferred` layer sits at its second-stage `yield from` when finalized, which has [special handling in `gen_close`](https://github.com/python/cpython/blob/v3.12.0/Objects/genobject.c#L389-L391)- it directly marks that generator as executing, then calls the [`gen_close_iter` helper](https://github.com/python/cpython/blob/v3.12.0/Objects/genobject.c#L313-L317) to close down the subgenerator. That kicks off a very deep chain of closes and finalizations, one of which ultimately tries to do a re-entrant `gen_close` on the same generator instance from the top of the chain. Since the finalization/close frame eval stuff is deeply recursive, the `"generator `ValueError` is indeed correct. The thing I've been struggling to figure out is if this is a bug in:
* the GC/finalizer - any change that even *slightly* defers that generator's life "fixes" the problem
* Python's generator close/wind-down code - the possibility of a re-entrant close doesn't appear to have been accounted for in the multiple places that mark the generator `FRAME_EXECUTING`
* new 3.12 generator optimizations (eg `FOR_ITER_GEN`; possibly a subtle refcount issue)
* astroid - with the many layers of caching and decorator magic happening, it's not out of the realm of possibility that a generator reference is being shared in a way that causes finalization issues that were only exposed by behavior changes in 3.12

Anyway, I need to get back to other work, but I might come back to it at some point- I just can't squash the feeling that  there's a serious issue lurking here...

**Comment by jacobtylerwalls** [comment]
Thanks for the deep dive.

> There's also an awful lot of caching involved in astroid- disabling nearly any of it "fixes" the repro

I'm willing to try this, even if there's a python 3.12 issue that could be reported upstream. Specifically I think we can revert pylint-dev/astroid@0d4f73d. I'll see what the pylint primer tool says about that.

**Comment by matejsp** [comment]
We also got hit by this issue. Really annoying. We introduced another plugin for fixing this issue based on:
https://github.com/ansible/ansible/pull/81953/files#diff-6f76ad123895780c325b531bbaf0f55837bd3c6f10838b9c164ca67247179982

Is there any chance to somehow fix this? Maybe even hacking with the solution provided by Ansible. Pylint is just unstable and useless out of the box for us with latest python.

**Comment by cdce8p** [comment]
Spend some time bisecting cpython today to figure out when the error first appeared. This is what I've got so far
- `3.12.0a1` was fine (no errors)
- `3.12.0a2` started to raise `InferenceError: StopIteration raised without any error information`. Further bisecting shows that the issue first appears after https://github.com/python/cpython/pull/98772 was merged.
- This continues all the way till `3.12.0a6`. For `3.12.0b1` it changed to the `ValueError` we see today.
Again bisecting that points to https://github.com/python/cpython/pull/103502

I haven't had time yet to look at these PRs in more detail. Wanted to post this here in case someone might be interested.
For testing I used the example from @nickdrozd above: https://github.com/pylint-dev/pylint/issues/9138#issuecomment-1760176964 and modified the current astroid [`master`](https://github.com/pylint-dev/astroid/commit/07419f0d8ef254f203b7f2b15141b6df23939519) slightly. In `rebuilder.py`, I added `PY312_PLUS = False` after the imports.

This was the full error between `a2` and `b1`
```py
Exception on node <Call l.21 at 0xffffadfd9910> in file '/usr/src/test.py'
Traceback (most recent call last):
  File "/usr/astroid/astroid/decorators.py", line 90, in inner
    yield next(generator)
          ^^^^^^^^^^^^^^^
StopIteration

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/src/pylint/utils/ast_walker.py", line 91, in walk
    callback(astroid)
  File "/usr/src/pylint/checkers/base/basic_checker.py", line 708, in visit_call
    if utils.is_terminating_func(node):
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/pylint/checkers/utils.py", line 2165, in is_terminating_func
    return True
           ^^^^
  File "/usr/astroid/astroid/nodes/node_ng.py", line 170, in infer
    for i, result in enumerate(self._infer(context=context, **kwargs)):
  File "/usr/astroid/astroid/decorators.py", line 95, in inner
    raise InferenceError(
astroid.exceptions.InferenceError: StopIteration raised without any error information.
```

**Comment by cdce8p** [comment]
> Just at a glance, I'd be a little surprised if the dict materialization change actually fixed whatever the problem was, since it doesn't appear to be related to the generator bits at all. It's more likely that pylint/astroid are positively affected by that 3.13 change in other ways, so the timing/circumstances improve just enough that the known reproducers go away (just as they do when other changes around caching or whatever are made).

Seems you're right. I just tested pylint with `3.13` alpha version on a larger code base, [Home Assistant](https://github.com/home-assistant/core). Just without any other dependencies as some aren't compatible yet.

On `3.12.2` I would see anywhere from 1 to 3 (with dependencies) `ValueErrors`. Those actually increase to 3 (without) for `3.13.0a1`. The materialization change I mentioned above is included there, so it doesn't do much overall.

For `3.13.0a2` till `3.13.0a4` I don't see any errors though. Of course it would be great if it would be possible to test with all dependencies to see if they are gone for good, but we'll have to wait a few months for that.

@nitzmahone I would be interested if you can reproduce that for `Ansible`. If that's the case there might still be a commit in between `a1` and `a2` that does fix it. It would then just be a question to bisect it again.

**Comment by cdce8p** [comment]
Did some more bisecting today. At least for Home Assistant the change that does appear to fix all ValueErrors seems to be
- https://github.com/python/cpython/pull/111069

Also tested cherry-picking it onto 3.12 which did also work.

**Comment by iritkatriel** [comment]
> Did some more bisecting today. At least for Home Assistant the change that does appear to fix all ValueErrors seems to be
> 
> * [gh-100762: Fix optimization in gen_close  python/cpython#111069](https://github.com/python/cpython/pull/111069)
> 
> Also tested cherry-picking it onto 3.12 which did also work.

I've now backported it to 3.12.

**Comment by cdce8p** [comment]
Thanks a lot @iritkatriel! I've ran some more tests and the issue seems to be truly gone now.

**Comment by nitzmahone** [comment]
> @nitzmahone I would be interested if you can reproduce that for Ansible. 

On the plus side, no issues running on 3.13.0a4 with Ansible's codebase (and our `sys.unraiseablehook` masker disabled), but owing to the underlying issue's fragile Heisenbug nature, I'm also no longer seeing the issue under 3.12.1, either... :neutral_face: 

Cautiously optimistic that the CPython upstream fix takes care of this one everywhere- once 3.12.3+ is widely available, we'll kill off our masking plugin and hope that's the end of it.

Thanks everyone!

**Comment by cdce8p** [comment]
Thanks @nitzmahone 👍🏻

I went ahead and opened #9454 to include the `sys.unraisablehook` overwrite in the pylint code base. It's scoped just for the affected Python versions.

**Comment by fake-name** [comment]
I'm seeing this issue in current pylint/astroid still:

```
Exception ignored in: <generator object _infer_attribute at 0x000002BF411CBBC0>
Traceback (most recent call last):
  File "C:\Python310\lib\site-packages\astroid\nodes\node_classes.py", line 1107, in _infer_attribute
    yield from owner.igetattr(node.attrname, context)
ValueError: generator already executing

```

This is with:

```
astroid==3.2.2
pylint==3.2.4
```

**Comment by jacobtylerwalls** [comment]
This is an issue as of Python 3.12.5 again after https://github.com/python/cpython/pull/120467.

**Comment by jacobtylerwalls** [comment]
The amount of effort required to fix this is unknown. In the meantime, you could pin to Python 3.12.4.

**Comment by matejsp** [comment]
Amazon linux 2023 comes with only Python 3.12.6 now so we cannot pin it to 3.12.4. Alpine 3.20 uses 3.12.7. And I cannot install older one.

Does 3.12.7 solve the issue?

**Comment by matejsp** [comment]
Any update on this? I see some code in https://github.com/pylint-dev/pylint/blob/main/pylint/__init__.py
```
if (3, 12, 0) <= sys.version_info[:3] < (3, 12, 3):
    sys.unraisablehook = _catch_valueerror
```

We use 3.12.8 and it still have the same issue. Can we expand the version ?

**Comment by jacobtylerwalls** [comment]
Yes, I would accept a PR that adds 3.12.5+ to that if guard.

**Comment by nedbat** [comment]
I occasionally see a similar error. It non-deterministic, not on 3.12, and might be a different place:
```
Exception ignored in: <generator object ClassDef.igetattr at 0x10d88ee40>
Traceback (most recent call last):
  File "/Users/ned/coverage/trunk/.tox/lint/lib/python3.9/site-packages/astroid/nodes/scoped_nodes/scoped_nodes.py", line 2547, in igetattr
    yield from function.infer_call_result(
  File "/Users/ned/coverage/trunk/.tox/lint/lib/python3.9/site-packages/astroid/nodes/scoped_nodes/scoped_nodes.py", line 1658, in infer_call_result
    yield from returnnode.value.infer(context)
ValueError: generator already executing
```

**Comment by jacobtylerwalls** [comment]
Reported in 3.14.0rc1 in #10470

**Comment by matejsp** [comment]
Nice to see this fixed.

But it is enabled for all versions not only for 3.12. Is this expected?

```
if (3, 12, 0) <= sys.version_info[:3] < (3, 12, 3) or sys.version_info >= (3, 12, 5):
```

So even 3.13 and 3.14 is covered by this? @jacobtylerwalls. Maybe it should be just for 3.12 ?

**Comment by DanielNoord** [comment]
As @jacobtylerwalls links above, it was also reported to happen in the RC1 of 3.14.

At this point I think we should stop the whack-a-mole and just apply it to all versions expect for those we know to be fixed. This is what @jacobtylerwalls's PR achieves.

**Comment by jacobtylerwalls** [comment]
I think 3.13 is affected also, judging from the https://github.com/python/cpython/pull/120467 that was cherry-picked to 3.12.5.

**Comment by jacobtylerwalls** [comment]
Reopening since we need to add a pytest skip given that we "lucked" into a consistent reproducer just now on CI 😿
