### ISSUE TITLE
Crash ```` Crash on python 3.12, with "Astroid-error"

### ISSUE THREAD

**Issue by alex-l-m** [pylint-dev/pylint#9244]
### Bug description

```python
When parsing the following file:

<!--
 If sharing the code is not an option, please state so,
 but providing only the stacktrace would still be helpful.
 -->


from os.path import exists
from itertools import batched
from pandas import read_csv
import pandas as pd
from rdkit.Chem.rdmolfiles import MolFromMolFile, MolFromSmarts, MolToSmiles
from rdkit.Chem.Draw import MolToImage, MolsToGridImage
from fragment import fragment
from shutil import copyfile

energies = read_csv("vasp_reliable_plqy.csv")

mols = []
legends = []
smiles_seen = set()
for row in energies.itertuples():
    # Read PLQY which will either be a missing value (in which case it should
    # be recorded as None) or a floating point number
    if pd.isna(row.plqy):
        plqy = None
    else:
        plqy = float(row.plqy)
    # Read wavelength similarly
    if pd.isna(row.wavelength):
        wavelength = None
    else:
        wavelength = float(row.wavelength)
    # Skip it if wavelength is low or missing; and if plqy is nonmissing and
    # low. I want to include stuff where PLQY is not yet known, but not
    # necessarily wavelength
    plqy_cutoff = 0.89
    wavelength_cutoff = 450
    if (wavelength is None or wavelength < wavelength_cutoff) or \
            (plqy is not None and plqy < plqy_cutoff):
        continue
    # Wavelength and PLQY labels (strings for display)
    # Wavelength is just wavelength as given, but with units
    # PLQY is either PLQY rounded to two digits, or "Not finished"
    wavelength_label = f"{round(int(row.wavelength))} nm"
    plqy_label = f"{row.plqy:.2}" if plqy is not None else "Not finished"
    display_label = f"λ={wavelength_label}\nφ={plqy_label}"
    inpath = f"substitutions/{row.mol_id}.mol"
    copyfile(inpath, f"top_mols/{row.mol_id}.mol")
    if not exists(inpath):
        continue
    mol = MolFromMolFile(inpath)
    smiles = MolToSmiles(mol)
    if smiles in smiles_seen:
        continue
    smiles_seen.add(smiles)
    ligand = fragment(mol)[0]
    ligand.RemoveAllConformers()
    mols.append(ligand)
    legends.append(wavelength_string)

b = 24
for i, (mol_batch, legend_batch) \
    in enumerate(zip(batched(mols, b), batched(legends, b))):
    img = MolsToGridImage(mol_batch, legends = legend_batch, molsPerRow = 2)
    img.save(f"images/vasp_batch_{i}.png")



pylint crashed with a ``AstroidError`` and with the following stacktrace:
```
Traceback (most recent call last):
  File "/home/alexlm/miniconda3/envs/chem/lib/python3.12/site-packages/pylint/checkers/utils.py", line 1370, in safe_infer
    value = next(infer_gen)
            ^^^^^^^^^^^^^^^
  File "/home/alexlm/miniconda3/envs/chem/lib/python3.12/site-packages/astroid/nodes/node_ng.py", line 171, in infer
    yield from self._infer(context=context, **kwargs)
  File "/home/alexlm/miniconda3/envs/chem/lib/python3.12/site-packages/astroid/decorators.py", line 142, in raise_if_nothing_inferred
    yield next(generator)
          ^^^^^^^^^^^^^^^
  File "/home/alexlm/miniconda3/envs/chem/lib/python3.12/site-packages/astroid/decorators.py", line 111, in wrapped
    for res in _func(node, context, **kwargs):
  File "/home/alexlm/miniconda3/envs/chem/lib/python3.12/site-packages/astroid/bases.py", line 176, in _infer_stmts
    for inf in stmt.infer(context=context):  # type: ignore[union-attr]
  File "/home/alexlm/miniconda3/envs/chem/lib/python3.12/site-packages/astroid/nodes/node_ng.py", line 184, in infer
    for i, result in enumerate(self._infer(context=context, **kwargs)):
  File "/home/alexlm/miniconda3/envs/chem/lib/python3.12/site-packages/astroid/decorators.py", line 142, in raise_if_nothing_inferred
    yield next(generator)
          ^^^^^^^^^^^^^^^
  File "/home/alexlm/miniconda3/envs/chem/lib/python3.12/site-packages/astroid/decorators.py", line 111, in wrapped
    for res in _func(node, context, **kwargs):
  File "/home/alexlm/miniconda3/envs/chem/lib/python3.12/site-packages/astroid/bases.py", line 176, in _infer_stmts
    for inf in stmt.infer(context=context):  # type: ignore[union-attr]
  File "/home/alexlm/miniconda3/envs/chem/lib/python3.12/site-packages/astroid/nodes/node_ng.py", line 184, in infer
    for i, result in enumerate(self._infer(context=context, **kwargs)):
  File "/home/alexlm/miniconda3/envs/chem/lib/python3.12/site-packages/astroid/decorators.py", line 142, in raise_if_nothing_inferred
    yield next(generator)
          ^^^^^^^^^^^^^^^
  File "/home/alexlm/miniconda3/envs/chem/lib/python3.12/site-packages/astroid/decorators.py", line 111, in wrapped
    for res in _func(node, context, **kwargs):
  File "/home/alexlm/miniconda3/envs/chem/lib/python3.12/site-packages/astroid/bases.py", line 176, in _infer_stmts
    for inf in stmt.infer(context=context):  # type: ignore[union-attr]
  File "/home/alexlm/miniconda3/envs/chem/lib/python3.12/site-packages/astroid/nodes/node_ng.py", line 184, in infer
    for i, result in enumerate(self._infer(context=context, **kwargs)):
  File "/home/alexlm/miniconda3/envs/chem/lib/python3.12/site-packages/astroid/decorators.py", line 142, in raise_if_nothing_inferred
    yield next(generator)
          ^^^^^^^^^^^^^^^
  File "/home/alexlm/miniconda3/envs/chem/lib/python3.12/site-packages/astroid/decorators.py", line 111, in wrapped
    for res in _func(node, context, **kwargs):
  File "/home/alexlm/miniconda3/envs/chem/lib/python3.12/site-packages/astroid/bases.py", line 176, in _infer_stmts
    for inf in stmt.infer(context=context):  # type: ignore[union-attr]
  File "/home/alexlm/miniconda3/envs/chem/lib/python3.12/site-packages/astroid/nodes/node_ng.py", line 184, in infer
    for i, result in enumerate(self._infer(context=context, **kwargs)):
  File "/home/alexlm/miniconda3/envs/chem/lib/python3.12/site-packages/astroid/decorators.py", line 142, in raise_if_nothing_inferred
    yield next(generator)
          ^^^^^^^^^^^^^^^
  File "/home/alexlm/miniconda3/envs/chem/lib/python3.12/site-packages/astroid/decorators.py", line 111, in wrapped
    for res in _func(node, context, **kwargs):
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/alexlm/miniconda3/envs/chem/lib/python3.12/site-packages/astroid/inference.py", line 334, in infer_import_from
    module = self.do_import_module()
             ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/alexlm/miniconda3/envs/chem/lib/python3.12/site-packages/astroid/nodes/_base_nodes.py", line 146, in do_import_module
    return mymodule.import_module(
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/alexlm/miniconda3/envs/chem/lib/python3.12/site-packages/astroid/nodes/scoped_nodes/scoped_nodes.py", line 527, in import_module
    return AstroidManager().ast_from_module_name(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/alexlm/miniconda3/envs/chem/lib/python3.12/site-packages/astroid/manager.py", line 232, in ast_from_module_name
    return self.ast_from_file(found_spec.location, modname, fallback=False)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/alexlm/miniconda3/envs/chem/lib/python3.12/site-packages/astroid/manager.py", line 124, in ast_from_file
    return AstroidBuilder(self).file_build(filepath, modname)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/alexlm/miniconda3/envs/chem/lib/python3.12/site-packages/astroid/builder.py", line 145, in file_build
    return self._post_build(module, builder, encoding)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/alexlm/miniconda3/envs/chem/lib/python3.12/site-packages/astroid/builder.py", line 173, in _post_build
    module = self._manager.visit_transforms(module)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/alexlm/miniconda3/envs/chem/lib/python3.12/site-packages/astroid/manager.py", line 95, in visit_transforms
    return self._transform.visit(node)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/alexlm/miniconda3/envs/chem/lib/python3.12/site-packages/astroid/transforms.py", line 89, in visit
    return self._visit(module)
           ^^^^^^^^^^^^^^^^^^^
  File "/home/alexlm/miniconda3/envs/chem/lib/python3.12/site-packages/astroid/transforms.py", line 54, in _visit
    visited = self._visit_generic(value)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/alexlm/miniconda3/envs/chem/lib/python3.12/site-packages/astroid/transforms.py", line 61, in _visit_generic
    return [self._visit_generic(child) for child in node]
            ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/alexlm/miniconda3/envs/chem/lib/python3.12/site-packages/astroid/transforms.py", line 67, in _visit_generic
    return self._visit(node)
           ^^^^^^^^^^^^^^^^^
  File "/home/alexlm/miniconda3/envs/chem/lib/python3.12/site-packages/astroid/transforms.py", line 57, in _visit
    return self._transform(node)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/alexlm/miniconda3/envs/chem/lib/python3.12/site-packages/astroid/transforms.py", line 38, in _transform
    if predicate is None or predicate(node):
                            ^^^^^^^^^^^^^^^
  File "/home/alexlm/miniconda3/envs/chem/lib/python3.12/site-packages/astroid/brain/brain_namedtuple_enum.py", line 613, in _is_enum_subclass
    for klass in cls.mro()
                 ^^^^^^^^^
  File "/home/alexlm/miniconda3/envs/chem/lib/python3.12/site-packages/astroid/nodes/scoped_nodes/scoped_nodes.py", line 3043, in mro
    return self._compute_mro(context=context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/alexlm/miniconda3/envs/chem/lib/python3.12/site-packages/astroid/nodes/scoped_nodes/scoped_nodes.py", line 3012, in _compute_mro
    inferred_bases = list(self._inferred_bases(context=context))
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/alexlm/miniconda3/envs/chem/lib/python3.12/site-packages/astroid/nodes/scoped_nodes/scoped_nodes.py", line 2995, in _inferred_bases
    baseobj = next(
              ^^^^^
  File "/home/alexlm/miniconda3/envs/chem/lib/python3.12/site-packages/astroid/nodes/scoped_nodes/scoped_nodes.py", line 2995, in <genexpr>
    baseobj = next(
                  ^
  File "/home/alexlm/miniconda3/envs/chem/lib/python3.12/site-packages/astroid/nodes/node_ng.py", line 184, in infer
    for i, result in enumerate(self._infer(context=context, **kwargs)):
  File "/home/alexlm/miniconda3/envs/chem/lib/python3.12/site-packages/astroid/decorators.py", line 142, in raise_if_nothing_inferred
    yield next(generator)
          ^^^^^^^^^^^^^^^
  File "/home/alexlm/miniconda3/envs/chem/lib/python3.12/site-packages/astroid/decorators.py", line 111, in wrapped
    for res in _func(node, context, **kwargs):
  File "/home/alexlm/miniconda3/envs/chem/lib/python3.12/site-packages/astroid/bases.py", line 176, in _infer_stmts
    for inf in stmt.infer(context=context):  # type: ignore[union-attr]
  File "/home/alexlm/miniconda3/envs/chem/lib/python3.12/site-packages/astroid/nodes/node_ng.py", line 184, in infer
    for i, result in enumerate(self._infer(context=context, **kwargs)):
  File "/home/alexlm/miniconda3/envs/chem/lib/python3.12/site-packages/astroid/decorators.py", line 142, in raise_if_nothing_inferred
    yield next(generator)
          ^^^^^^^^^^^^^^^
  File "/home/alexlm/miniconda3/envs/chem/lib/python3.12/site-packages/astroid/decorators.py", line 111, in wrapped
    for res in _func(node, context, **kwargs):
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/alexlm/miniconda3/envs/chem/lib/python3.12/site-packages/astroid/inference.py", line 334, in infer_import_from
    module = self.do_import_module()
             ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/alexlm/miniconda3/envs/chem/lib/python3.12/site-packages/astroid/nodes/_base_nodes.py", line 146, in do_import_module
    return mymodule.import_module(
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/alexlm/miniconda3/envs/chem/lib/python3.12/site-packages/astroid/nodes/scoped_nodes/scoped_nodes.py", line 527, in import_module
    return AstroidManager().ast_from_module_name(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/alexlm/miniconda3/envs/chem/lib/python3.12/site-packages/astroid/manager.py", line 232, in ast_from_module_name
    return self.ast_from_file(found_spec.location, modname, fallback=False)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/alexlm/miniconda3/envs/chem/lib/python3.12/site-packages/astroid/manager.py", line 124, in ast_from_file
    return AstroidBuilder(self).file_build(filepath, modname)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/alexlm/miniconda3/envs/chem/lib/python3.12/site-packages/astroid/builder.py", line 144, in file_build
    module, builder = self._data_build(data, modname, path)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/alexlm/miniconda3/envs/chem/lib/python3.12/site-packages/astroid/builder.py", line 204, in _data_build
    module = builder.visit_module(node, modname, node_file, package)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/alexlm/miniconda3/envs/chem/lib/python3.12/site-packages/astroid/rebuilder.py", line 254, in visit_module
    [self.visit(child, newnode) for child in node.body],
     ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/alexlm/miniconda3/envs/chem/lib/python3.12/site-packages/astroid/rebuilder.py", line 603, in visit
    visit_method = getattr(self, visit_name)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'TreeRebuilder' object has no attribute 'visit_typealias'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/alexlm/miniconda3/envs/chem/lib/python3.12/site-packages/pylint/lint/pylinter.py", line 798, in _lint_file
    check_astroid_module(module)
  File "/home/alexlm/miniconda3/envs/chem/lib/python3.12/site-packages/pylint/lint/pylinter.py", line 1067, in check_astroid_module
    retval = self._check_astroid_module(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/alexlm/miniconda3/envs/chem/lib/python3.12/site-packages/pylint/lint/pylinter.py", line 1117, in _check_astroid_module
    walker.walk(node)
  File "/home/alexlm/miniconda3/envs/chem/lib/python3.12/site-packages/pylint/utils/ast_walker.py", line 94, in walk
    self.walk(child)
  File "/home/alexlm/miniconda3/envs/chem/lib/python3.12/site-packages/pylint/utils/ast_walker.py", line 91, in walk
    callback(astroid)
  File "/home/alexlm/miniconda3/envs/chem/lib/python3.12/site-packages/pylint/checkers/refactoring/refactoring_checker.py", line 1520, in visit_assign
    self._append_context_managers_to_stack(node)
  File "/home/alexlm/miniconda3/envs/chem/lib/python3.12/site-packages/pylint/checkers/refactoring/refactoring_checker.py", line 1572, in _append_context_managers_to_stack
    inferred = utils.safe_infer(value.func)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/alexlm/miniconda3/envs/chem/lib/python3.12/site-packages/pylint/checkers/utils.py", line 1374, in safe_infer
    raise AstroidError from e
astroid.exceptions.AstroidError

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/alexlm/miniconda3/envs/chem/lib/python3.12/site-packages/pylint/lint/pylinter.py", line 763, in _lint_files
    self._lint_file(fileitem, module, check_astroid_module)
  File "/home/alexlm/miniconda3/envs/chem/lib/python3.12/site-packages/pylint/lint/pylinter.py", line 800, in _lint_file
    raise astroid.AstroidError from e
astroid.exceptions.AstroidError
```
```

### Command used

```shell
pylint make_vasp_images.py
```

### Pylint output

```python
Given in main body
```

### Expected behavior

Expected not to crash

### Pylint version

```shell
pylint 2.16.2
astroid 2.14.2
Python 3.12.0 | packaged by conda-forge | (main, Oct  3 2023, 08:43:22) [GCC 12.3.0]
```

### OS / Environment

"cat /etc/issue" yields "Pop!_OS 22.04 LTS \n \l". Whatever terminal comes with PopOS! Using Python 3.12.0 in a conda environment. Python was installed from conda-forge.

**Comment by jacobtylerwalls** [comment]
Python 3.12 is only supported on pylint 3 or higher. Feel free to reopen if you can reproduce after upgrading.

**Comment by alex-l-m** [comment]
I see. I've upgraded to pylint 3.0.2 and have no more problems.
