### ISSUE TITLE
Astroid crashes with Duplicates found in MROs after upgrading to pylint 3 and Python 3.12

### ISSUE THREAD

**Issue by z4m0** [pylint-dev/pylint#9254]
### Bug description

```python
Astroid crashes with `Duplicates found in MROs` after upgrading to pylint 3 and Python 3.12. Additionally the traceback is not hidden when `astroid-errors` is disabled. The same code works well in pylint/astroid 2

Can't provide the exact code. But there are some generics and protocols involved.


@dataclass(kw_only=True, slots=True)
class SpecializedListRecords(Records[MySchema, Metadata]]):
   ...

@dataclass(kw_only=True, slots=True)
class Records(SerializableDataStructure[B, M], Protocol[S, M]): 
   ...

class SerializableDataStructure(Protocol[S, M]):
   ...
```

### Command used

```shell
pre-commit run pylint --all-files
```

### Pylint output

```python
Traceback (most recent call last):
  File "/my-repo/.venv/lib/python3.12/site-packages/pylint/lint/pylinter.py", line 976, in get_ast
    return MANAGER.ast_from_file(filepath, modname, source=True)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/my-repo/.venv/lib/python3.12/site-packages/astroid/manager.py", line 151, in ast_from_file
    return AstroidBuilder(self).file_build(filepath, modname)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/my-repo/.venv/lib/python3.12/site-packages/astroid/builder.py", line 140, in file_build
    return self._post_build(module, builder, encoding)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/my-repo/.venv/lib/python3.12/site-packages/astroid/builder.py", line 168, in _post_build
    module = self._manager.visit_transforms(module)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/my-repo/.venv/lib/python3.12/site-packages/astroid/manager.py", line 114, in visit_transforms
    return self._transform.visit(node)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/my-repo/.venv/lib/python3.12/site-packages/astroid/transforms.py", line 151, in visit
    return self._visit(node)
           ^^^^^^^^^^^^^^^^^
  File "/my-repo/.venv/lib/python3.12/site-packages/astroid/transforms.py", line 81, in _visit
    visited = self._visit_generic(value)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/my-repo/.venv/lib/python3.12/site-packages/astroid/transforms.py", line 112, in _visit_generic
    return [self._visit_generic(child) for child in node]
            ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/my-repo/.venv/lib/python3.12/site-packages/astroid/transforms.py", line 118, in _visit_generic
    return self._visit(node)
           ^^^^^^^^^^^^^^^^^
  File "/my-repo/.venv/lib/python3.12/site-packages/astroid/transforms.py", line 84, in _visit
    return self._transform(node)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/my-repo/.venv/lib/python3.12/site-packages/astroid/transforms.py", line 66, in _transform
    ret = transform_func(node)
          ^^^^^^^^^^^^^^^^^^^^
  File "/my-repo/.venv/lib/python3.12/site-packages/astroid/brain/brain_dataclasses.py", line 84, in dataclass_transform
    init_str = _generate_dataclass_init(
               ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/my-repo/.venv/lib/python3.12/site-packages/astroid/brain/brain_dataclasses.py", line 249, in _generate_dataclass_init
    prev_pos_only_store, prev_kw_only_store = _find_arguments_from_base_classes(node)
                                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/my-repo/.venv/lib/python3.12/site-packages/astroid/brain/brain_dataclasses.py", line 174, in _find_arguments_from_base_classes
    for base in reversed(node.mro()):
                         ^^^^^^^^^^
  File "/my-repo/.venv/lib/python3.12/site-packages/astroid/nodes/scoped_nodes/scoped_nodes.py", line 2922, in mro
    return self._compute_mro(context=context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/my-repo/.venv/lib/python3.12/site-packages/astroid/nodes/scoped_nodes/scoped_nodes.py", line 2910, in _compute_mro
    unmerged_mro = clean_duplicates_mro(unmerged_mro, self, context)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/my-repo/.venv/lib/python3.12/site-packages/astroid/nodes/scoped_nodes/scoped_nodes.py", line 153, in clean_duplicates_mro
    raise DuplicateBasesError(
astroid.exceptions.DuplicateBasesError: Duplicates found in MROs (SpecializedListRecords), (Records, SerializableDataStructure, Protocol, Protocol, object), (Records) for <ClassDef.SpecializedListRecords l.44 at 0x....>.

```

### Expected behavior

Should not crash or at least be able to hide the tracebacks

### Pylint version

```shell
pylint 3.0.2
astroid 3.0.1
Python 3.12.0
```

### OS / Environment

Mac OS and Linux

**Comment by DanielNoord** [comment]
Please provide code that reproduces it. I tried with
```python
from dataclasses import dataclass
from typing import Protocol, TypeVar

S = TypeVar("S")
M = TypeVar("M")
B = TypeVar("B")


@dataclass(kw_only=True, slots=True)
class SpecializedListRecords(Records[MySchema, Metadata]):
    ...


@dataclass(kw_only=True, slots=True)
class Records(SerializableDataStructure[B, M], Protocol[S, M]):
    ...


class SerializableDataStructure(Protocol[S, M]):
    ...

```

But that doesn't work.
