### ISSUE TITLE
Code Analysis crashes when astropy.coordinates.SkyCoord is imported (within Spyder)

### ISSUE THREAD

**Issue by tstolarczyk** [pylint-dev/pylint#9260]
### Bug description

```python
Analysing a module in spyder 5.4 leads to a crash reported in the pylint log file, due to :
:code:`from   astropy.coordinates import SkyCoord`
The module imports many other modules and functions but this one only causes the crash (i.e. if this import is commented the analysis goes well).

The script can be found here :
https://github.com/tstolarczyk/SoHAPPy/blob/master/dataset_tools.py
```

### Configuration

```ini
Windows 10
conda 22.11.1
python 3.7.0
spyder 5.4.0
pylint 2.16.2

astropy 4.1

Note that I am using a Windows (not conda) based spyder installation, pointing to the required python.exe of my anaconda environment. I have checked that both astropy and pylint versions are the same in my base and development environment.
```

### Command used

```shell
pylint ran from within spyder.
```

### Pylint output

```python
pylint crashed with a ``AstroidError`` and with the following stacktrace:
```
Traceback (most recent call last):
  File "C:\Users\stolar\AppData\Local\Programs\Spyder\pkgs\astroid\inference_tip.py", line 38, in _inference_tip_cached
    result = _cache[func, node]
KeyError: (<function infer_named_tuple at 0x0000025BDD245F70>, <Call l.305 at 0x25beb6af6d0>)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\stolar\AppData\Local\Programs\Spyder\pkgs\pylint\checkers\imports.py", line 798, in _get_imported_module
    return importnode.do_import_module(modname)
  File "C:\Users\stolar\AppData\Local\Programs\Spyder\pkgs\astroid\nodes\_base_nodes.py", line 148, in do_import_module
    return mymodule.import_module(
  File "C:\Users\stolar\AppData\Local\Programs\Spyder\pkgs\astroid\nodes\scoped_nodes\scoped_nodes.py", line 522, in import_module
    return AstroidManager().ast_from_module_name(absmodname)
  File "C:\Users\stolar\AppData\Local\Programs\Spyder\pkgs\astroid\manager.py", line 209, in ast_from_module_name
    return self.ast_from_file(found_spec.location, modname, fallback=False)
  File "C:\Users\stolar\AppData\Local\Programs\Spyder\pkgs\astroid\manager.py", line 118, in ast_from_file
    return AstroidBuilder(self).file_build(filepath, modname)
  File "C:\Users\stolar\AppData\Local\Programs\Spyder\pkgs\astroid\builder.py", line 135, in file_build
    return self._post_build(module, builder, encoding)
  File "C:\Users\stolar\AppData\Local\Programs\Spyder\pkgs\astroid\builder.py", line 154, in _post_build
    self.add_from_names_to_locals(from_node)
  File "C:\Users\stolar\AppData\Local\Programs\Spyder\pkgs\astroid\builder.py", line 210, in add_from_names_to_locals
    imported = node.do_import_module()
  File "C:\Users\stolar\AppData\Local\Programs\Spyder\pkgs\astroid\nodes\_base_nodes.py", line 148, in do_import_module
    return mymodule.import_module(
  File "C:\Users\stolar\AppData\Local\Programs\Spyder\pkgs\astroid\nodes\scoped_nodes\scoped_nodes.py", line 522, in import_module
    return AstroidManager().ast_from_module_name(absmodname)
  File "C:\Users\stolar\AppData\Local\Programs\Spyder\pkgs\astroid\manager.py", line 209, in ast_from_module_name
    return self.ast_from_file(found_spec.location, modname, fallback=False)
  File "C:\Users\stolar\AppData\Local\Programs\Spyder\pkgs\astroid\manager.py", line 118, in ast_from_file
    return AstroidBuilder(self).file_build(filepath, modname)
  File "C:\Users\stolar\AppData\Local\Programs\Spyder\pkgs\astroid\builder.py", line 135, in file_build
    return self._post_build(module, builder, encoding)
  File "C:\Users\stolar\AppData\Local\Programs\Spyder\pkgs\astroid\builder.py", line 161, in _post_build
    module = self._manager.visit_transforms(module)
  File "C:\Users\stolar\AppData\Local\Programs\Spyder\pkgs\astroid\manager.py", line 95, in visit_transforms
    return self._transform.visit(node)
  File "C:\Users\stolar\AppData\Local\Programs\Spyder\pkgs\astroid\transforms.py", line 89, in visit
    return self._visit(module)
  File "C:\Users\stolar\AppData\Local\Programs\Spyder\pkgs\astroid\transforms.py", line 54, in _visit
    visited = self._visit_generic(value)
  File "C:\Users\stolar\AppData\Local\Programs\Spyder\pkgs\astroid\transforms.py", line 61, in _visit_generic
    return [self._visit_generic(child) for child in node]
  File "C:\Users\stolar\AppData\Local\Programs\Spyder\pkgs\astroid\transforms.py", line 61, in <listcomp>
    return [self._visit_generic(child) for child in node]
  File "C:\Users\stolar\AppData\Local\Programs\Spyder\pkgs\astroid\transforms.py", line 67, in _visit_generic
    return self._visit(node)
  File "C:\Users\stolar\AppData\Local\Programs\Spyder\pkgs\astroid\transforms.py", line 57, in _visit
    return self._transform(node)
  File "C:\Users\stolar\AppData\Local\Programs\Spyder\pkgs\astroid\transforms.py", line 38, in _transform
    if predicate is None or predicate(node):
  File "C:\Users\stolar\AppData\Local\Programs\Spyder\pkgs\astroid\brain\brain_namedtuple_enum.py", line 586, in _is_enum_subclass
    for klass in cls.mro()
  File "C:\Users\stolar\AppData\Local\Programs\Spyder\pkgs\astroid\nodes\scoped_nodes\scoped_nodes.py", line 3062, in mro
    return self._compute_mro(context=context)
  File "C:\Users\stolar\AppData\Local\Programs\Spyder\pkgs\astroid\nodes\scoped_nodes\scoped_nodes.py", line 3031, in _compute_mro
    inferred_bases = list(self._inferred_bases(context=context))
  File "C:\Users\stolar\AppData\Local\Programs\Spyder\pkgs\astroid\nodes\scoped_nodes\scoped_nodes.py", line 3014, in _inferred_bases
    baseobj = next(
  File "C:\Users\stolar\AppData\Local\Programs\Spyder\pkgs\astroid\nodes\scoped_nodes\scoped_nodes.py", line 3014, in <genexpr>
    baseobj = next(
  File "C:\Users\stolar\AppData\Local\Programs\Spyder\pkgs\astroid\nodes\node_ng.py", line 182, in infer
    for i, result in enumerate(self._infer(context=context, **kwargs)):
  File "C:\Users\stolar\AppData\Local\Programs\Spyder\pkgs\astroid\decorators.py", line 140, in raise_if_nothing_inferred
    yield next(generator)
  File "C:\Users\stolar\AppData\Local\Programs\Spyder\pkgs\astroid\decorators.py", line 109, in wrapped
    for res in _func(node, context, **kwargs):
  File "C:\Users\stolar\AppData\Local\Programs\Spyder\pkgs\astroid\bases.py", line 165, in _infer_stmts
    for inf in stmt.infer(context=context):  # type: ignore[union-attr]
  File "C:\Users\stolar\AppData\Local\Programs\Spyder\pkgs\astroid\nodes\node_ng.py", line 182, in infer
    for i, result in enumerate(self._infer(context=context, **kwargs)):
  File "C:\Users\stolar\AppData\Local\Programs\Spyder\pkgs\astroid\decorators.py", line 140, in raise_if_nothing_inferred
    yield next(generator)
  File "C:\Users\stolar\AppData\Local\Programs\Spyder\pkgs\astroid\decorators.py", line 109, in wrapped
    for res in _func(node, context, **kwargs):
  File "C:\Users\stolar\AppData\Local\Programs\Spyder\pkgs\astroid\bases.py", line 165, in _infer_stmts
    for inf in stmt.infer(context=context):  # type: ignore[union-attr]
  File "C:\Users\stolar\AppData\Local\Programs\Spyder\pkgs\astroid\nodes\node_ng.py", line 159, in infer
    results = list(self._explicit_inference(self, context, **kwargs))
  File "C:\Users\stolar\AppData\Local\Programs\Spyder\pkgs\astroid\inference_tip.py", line 45, in _inference_tip_cached
    result = _cache[func, node] = list(func(*args, **kwargs))
  File "C:\Users\stolar\AppData\Local\Programs\Spyder\pkgs\astroid\brain\brain_namedtuple_enum.py", line 201, in infer_named_tuple
    rename = next(call_site.infer_argument(func, "rename", context)).bool_value()
  File "C:\Users\stolar\AppData\Local\Programs\Spyder\pkgs\astroid\arguments.py", line 177, in infer_argument
    if len(self.positional_arguments) > len(funcnode.args.args):
TypeError: object of type 'Uninferable' has no len()

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\stolar\AppData\Local\Programs\Spyder\pkgs\pylint\lint\pylinter.py", line 790, in _lint_file
    check_astroid_module(module)
  File "C:\Users\stolar\AppData\Local\Programs\Spyder\pkgs\pylint\lint\pylinter.py", line 1060, in check_astroid_module
    retval = self._check_astroid_module(
  File "C:\Users\stolar\AppData\Local\Programs\Spyder\pkgs\pylint\lint\pylinter.py", line 1110, in _check_astroid_module
    walker.walk(node)
  File "C:\Users\stolar\AppData\Local\Programs\Spyder\pkgs\pylint\utils\ast_walker.py", line 93, in walk
    self.walk(child)
  File "C:\Users\stolar\AppData\Local\Programs\Spyder\pkgs\pylint\utils\ast_walker.py", line 90, in walk
    callback(astroid)
  File "C:\Users\stolar\AppData\Local\Programs\Spyder\pkgs\pylint\checkers\imports.py", line 502, in visit_importfrom
    imported_module = self._get_imported_module(node, basename)
  File "C:\Users\stolar\AppData\Local\Programs\Spyder\pkgs\pylint\checkers\imports.py", line 823, in _get_imported_module
    raise astroid.AstroidError from e
astroid.exceptions.AstroidError

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\stolar\AppData\Local\Programs\Spyder\pkgs\pylint\lint\pylinter.py", line 755, in _lint_files
    self._lint_file(fileitem, module, check_astroid_module)
  File "C:\Users\stolar\AppData\Local\Programs\Spyder\pkgs\pylint\lint\pylinter.py", line 792, in _lint_file
    raise astroid.AstroidError from e
astroid.exceptions.AstroidError
```
```

### Expected behavior

The analysis should go well, which it does as soon as the "faulty" import is commented

### Pylint version

```shell
pylint 2.16.2
astroid 2.14.2
Python 3.7.0 | packaged by conda-forge | (default, Nov 12 2018, 20:47:31) [MSC v.1900 64 bit (AMD64)]
```

### OS / Environment

Windows 10, DELL laptop, I9, RAM 64Gb

### Additional dependencies

```python
This is probably useless:

aioftp @ file:///home/conda/feedstock_root/build_artifacts/aioftp_1594306619770/work
aiohttp @ file:///C:/b/abs_c4zmy2l696/croot/aiohttp_1670009573673/work
aiosignal @ file:///tmp/build/80754af9/aiosignal_1637843061372/work
alabaster==0.7.12
anyio @ file:///C:/ci/anyio_1644463705902/work/dist
argon2-cffi @ file:///opt/conda/conda-bld/argon2-cffi_1645000214183/work
argon2-cffi-bindings @ file:///C:/ci/argon2-cffi-bindings_1644569848815/work
astroid @ file:///C:/b/abs_d4lg3_taxn/croot/astroid_1676904351456/work
astroplan==0.8
astropy @ file:///D:/bld/astropy_1605117643502/work
async-timeout @ file:///C:/b/abs_43ozhz2a8g/croots/recipe/async-timeout_1664876362767/work
asynctest==0.13.0
attrs @ file:///C:/b/abs_09s3y775ra/croot/attrs_1668696195628/work
Babel @ file:///C:/b/abs_a2shv_3tqi/croot/babel_1671782804377/work
backcall @ file:///home/ktietz/src/ci/backcall_1611930011877/work
beautifulsoup4 @ file:///C:/ci/beautifulsoup4_1650292996413/work
bleach @ file:///opt/conda/conda-bld/bleach_1641577558959/work
Brotli @ file:///C:/Windows/Temp/abs_63l7912z0e/croots/recipe/brotli-split_1659616056886/work
certifi @ file:///C:/b/abs_85o_6fm0se/croot/certifi_1671487778835/work/certifi
cffi @ file:///C:/b/abs_49n3v2hyhr/croot/cffi_1670423218144/work
charset-normalizer @ file:///tmp/build/80754af9/charset-normalizer_1630003229654/work
Click==7.0
cloudpickle @ file:///tmp/build/80754af9/cloudpickle_1632508026186/work
colorama @ file:///C:/b/abs_a9ozq0l032/croot/colorama_1672387194846/work
commonmark @ file:///Users/ktietz/demo/mc3/conda-bld/commonmark_1630649545323/work
corner==2.0.1
cycler @ file:///tmp/build/80754af9/cycler_1637851556182/work
Cython @ file:///D:/bld/cython_1659102065258/work
debugpy @ file:///D:/bld/debugpy_1660619187469/work
decorator @ file:///opt/conda/conda-bld/decorator_1643638310831/work
defusedxml @ file:///tmp/build/80754af9/defusedxml_1615228127516/work
dill @ file:///C:/b/abs_42h_07z1yj/croot/dill_1667919550096/work
docutils @ file:///C:/ci/docutils_1620828194019/work
emcee==2.2.1
entrypoints @ file:///C:/ci/entrypoints_1649926659561/work
fastjsonschema @ file:///C:/Users/BUILDE~1/AppData/Local/Temp/abs_ebruxzvd08/croots/recipe/python-fastjsonschema_1661376484940/work
flit_core @ file:///opt/conda/conda-bld/flit-core_1644941570762/work/source/flit_core
frozenlist @ file:///C:/b/abs_2bb5uzghsi/croot/frozenlist_1670004511812/work
future @ file:///C:/b/abs_3dcibf18zi/croot/future_1677599891380/work
gammapy @ file:///D:/bld/gammapy_1622906234378/work
h5py @ file:///C:/ci/h5py_1659089886851/work
idna @ file:///C:/b/abs_bdhbebrioa/croot/idna_1666125572046/work
imagesize @ file:///C:/Windows/TEMP/abs_3cecd249-3fc4-4bfc-b80b-bb227b0d701en12vqzot/croots/recipe/imagesize_1657179501304/work
iminuit==1.3.8
importlib-metadata @ file:///C:/ci/importlib-metadata_1648562631189/work
importlib-resources @ file:///tmp/build/80754af9/importlib_resources_1625135880749/work
ipykernel @ file:///D:/bld/ipykernel_1666723449132/work
ipython @ file:///D:/bld/ipython_1651240762678/work
ipython-genutils @ file:///tmp/build/80754af9/ipython_genutils_1606773439826/work
ipywidgets @ file:///tmp/build/80754af9/ipywidgets_1634143127070/work
isort==5.11.5
jedi @ file:///C:/ci/jedi_1644297241925/work
Jinja2 @ file:///C:/b/abs_7cdis66kl9/croot/jinja2_1666908141852/work
json5 @ file:///tmp/build/80754af9/json5_1624432770122/work
jsonschema @ file:///C:/b/abs_6ccs97j_l8/croot/jsonschema_1676558690963/work
jupyter @ file:///C:/Windows/TEMP/abs_56xfdi__li/croots/recipe/jupyter_1659349053177/work
jupyter-console @ file:///C:/b/abs_e8gx0csskd/croot/jupyter_console_1671541918848/work
jupyter-server @ file:///C:/b/abs_1cfi3__jl8/croot/jupyter_server_1671707636383/work
jupyter_client @ file:///C:/b/abs_d8fk_kz9zk/croot/jupyter_client_1676330195659/work
jupyter_core @ file:///D:/bld/jupyter_core_1658332454038/work
jupyterlab @ file:///C:/b/abs_513jt6yy74/croot/jupyterlab_1675354138043/work
jupyterlab-pygments @ file:///tmp/build/80754af9/jupyterlab_pygments_1601490720602/work
jupyterlab-widgets @ file:///tmp/build/80754af9/jupyterlab_widgets_1609884341231/work
jupyterlab_server @ file:///C:/b/abs_d1z_g1swc8/croot/jupyterlab_server_1677153204814/work
kiwisolver @ file:///C:/b/abs_88mdhvtahm/croot/kiwisolver_1672387921783/work
lazy-object-proxy @ file:///C:/ci/lazy-object-proxy_1616529290879/work
MarkupSafe @ file:///C:/ci/markupsafe_1654508076077/work
matplotlib @ file:///C:/ci/matplotlib-base_1592401131947/work
matplotlib-inline @ file:///C:/ci/matplotlib-inline_1661934089728/work
mccabe @ file:///opt/conda/conda-bld/mccabe_1644221741721/work
mistune @ file:///C:/ci/mistune_1594373272338/work
mkl-service==2.3.0
multidict @ file:///C:/b/abs_6cx_8w3cv2/croot/multidict_1665674238352/work
naima @ file:///D:/bld/naima_1605102643994/work
nbclassic @ file:///C:/b/abs_d0_ze5q0j2/croot/nbclassic_1676902914817/work
nbclient @ file:///C:/ci/nbclient_1650308542913/work
nbconvert @ file:///C:/ci/nbconvert_1649759177374/work
nbformat @ file:///C:/b/abs_85_3g7dkt4/croot/nbformat_1670352343720/work
nbsphinx==0.8.11
nest-asyncio @ file:///C:/b/abs_3a_4jsjlqu/croot/nest-asyncio_1672387322800/work
notebook @ file:///C:/b/abs_ca13hqvuzw/croot/notebook_1668179888546/work
notebook_shim @ file:///C:/b/abs_ebfczttg6x/croot/notebook-shim_1668160590914/work
numpy @ file:///D:/bld/numpy_1604946150193/work
numpydoc @ file:///C:/b/abs_cfdd4zxbga/croot/numpydoc_1668085912100/work
packaging @ file:///C:/b/abs_cfsup8ur87/croot/packaging_1671697442297/work
pandas @ file:///D:/bld/pandas_1614698123791/work
pandocfilters @ file:///opt/conda/conda-bld/pandocfilters_1643405455980/work
parfive @ file:///home/conda/feedstock_root/build_artifacts/parfive_1599752703759/work
parso @ file:///opt/conda/conda-bld/parso_1641458642106/work
pickleshare @ file:///tmp/build/80754af9/pickleshare_1606932040724/work
pkgutil_resolve_name @ file:///C:/Users/BUILDE~1/AppData/Local/Temp/abs_81wm45v3kb/croots/recipe/pkgutil-resolve-name_1661463352381/work
platformdirs @ file:///C:/b/abs_73cc5cz_1u/croots/recipe/platformdirs_1662711386458/work
ply==3.11
prometheus-client @ file:///C:/Windows/TEMP/abs_ab9nx8qb08/croots/recipe/prometheus_client_1659455104602/work
prompt-toolkit @ file:///C:/b/abs_6coz5_9f2s/croot/prompt-toolkit_1672387908312/work
psutil @ file:///C:/Windows/Temp/abs_b2c2fd7f-9fd5-4756-95ea-8aed74d0039flsd9qufz/croots/recipe/psutil_1656431277748/work
pycparser @ file:///tmp/build/80754af9/pycparser_1636541352034/work
pydantic==1.2
Pygments @ file:///opt/conda/conda-bld/pygments_1644249106324/work
pylint @ file:///C:/b/abs_83sq99jc8i/croot/pylint_1676919922167/work
pyparsing @ file:///C:/Users/BUILDE~1/AppData/Local/Temp/abs_7f_7lba6rl/croots/recipe/pyparsing_1661452540662/work
PyQt5==5.15.7
PyQt5-sip @ file:///C:/Windows/Temp/abs_d7gmd2jg8i/croots/recipe/pyqt-split_1659273064801/work/pyqt_sip
pyrsistent @ file:///C:/ci/pyrsistent_1636093257833/work
PySocks @ file:///C:/ci/pysocks_1594394709107/work
python-dateutil @ file:///tmp/build/80754af9/python-dateutil_1626374649649/work
pytz @ file:///C:/b/abs_22fofvpn1x/croot/pytz_1671698059864/work
pywin32==305.1
pywinpty @ file:///C:/b/abs_73vshmevwq/croot/pywinpty_1677609966356/work/target/wheels/pywinpty-2.0.10-cp37-none-win_amd64.whl
PyYAML==5.2
pyzmq @ file:///C:/ci/pyzmq_1657597757589/work
qtconsole @ file:///C:/b/abs_5bap7f8n0t/croot/qtconsole_1674008444833/work
QtPy @ file:///C:/ci/qtpy_1662015131946/work
recommonmark @ file:///home/conda/feedstock_root/build_artifacts/recommonmark_1608240755822/work
regions @ file:///D:/bld/regions_1622824224753/work
requests @ file:///home/conda/feedstock_root/build_artifacts/requests_1661872987712/work
scipy==1.4.1
seaborn @ file:///C:/b/abs_68ltdkoyoo/croot/seaborn_1673479199997/work
Send2Trash @ file:///tmp/build/80754af9/send2trash_1632406701022/work
sip @ file:///C:/Windows/Temp/abs_b8fxd17m2u/croots/recipe/sip_1659012372737/work
six @ file:///tmp/build/80754af9/six_1644875935023/work
sniffio @ file:///C:/ci/sniffio_1614030522573/work
snowballstemmer @ file:///tmp/build/80754af9/snowballstemmer_1637937080595/work
soupsieve @ file:///C:/b/abs_fasraqxhlv/croot/soupsieve_1666296394662/work
Sphinx @ file:///home/conda/feedstock_root/build_artifacts/sphinx_1655452194084/work
sphinx-automodapi @ file:///home/conda/feedstock_root/build_artifacts/sphinx-automodapi_1670961004613/work
sphinx-rtd-theme @ file:///home/conda/feedstock_root/build_artifacts/sphinx_rtd_theme_1670867610925/work
sphinxcontrib-applehelp @ file:///home/ktietz/src/ci/sphinxcontrib-applehelp_1611920841464/work
sphinxcontrib-devhelp @ file:///home/ktietz/src/ci/sphinxcontrib-devhelp_1611920923094/work
sphinxcontrib-htmlhelp @ file:///tmp/build/80754af9/sphinxcontrib-htmlhelp_1623945626792/work
sphinxcontrib-jsmath @ file:///home/ktietz/src/ci/sphinxcontrib-jsmath_1611920942228/work
sphinxcontrib-qthelp @ file:///home/ktietz/src/ci/sphinxcontrib-qthelp_1611921055322/work
sphinxcontrib-serializinghtml @ file:///tmp/build/80754af9/sphinxcontrib-serializinghtml_1624451540180/work
spyder-kernels @ file:///D:/bld/spyder-kernels_1680544940746/work
terminado @ file:///C:/b/abs_25nakickad/croot/terminado_1671751845491/work
testpath @ file:///C:/Windows/TEMP/abs_23c7fa33-cbb9-46dc-b7c5-590c38e2de3d4bmbngal/croots/recipe/testpath_1655908553202/work
toml @ file:///tmp/build/80754af9/toml_1616166611790/work
tomli @ file:///C:/Windows/TEMP/abs_ac109f85-a7b3-4b4d-bcfd-52622eceddf0hy332ojo/croots/recipe/tomli_1657175513137/work
tomlkit @ file:///C:/Windows/TEMP/abs_3296qo9v6b/croots/recipe/tomlkit_1658946894808/work
tornado @ file:///C:/ci/tornado_1662476933490/work
tqdm @ file:///C:/b/abs_0axbz66qik/croots/recipe/tqdm_1664392691071/work
traitlets @ file:///C:/b/abs_e5m_xjjl94/croot/traitlets_1671143896266/work
typed-ast @ file:///C:/ci/typed-ast_1624953789477/work
typing_extensions @ file:///C:/b/abs_89eui86zuq/croot/typing_extensions_1669923792806/work
urllib3 @ file:///home/conda/feedstock_root/build_artifacts/urllib3_1695649846578/work
wcwidth @ file:///Users/ktietz/demo/mc3/conda-bld/wcwidth_1629357192024/work
webencodings==0.5.1
websocket-client @ file:///C:/ci/websocket-client_1614804293275/work
widgetsnbextension @ file:///C:/ci/widgetsnbextension_1645009553925/work
win-inet-pton @ file:///C:/ci/win_inet_pton_1605306165655/work
wincertstore==0.2
wrapt @ file:///C:/Windows/Temp/abs_7c3dd407-1390-477a-b542-fd15df6a24085_diwiza/croots/recipe/wrapt_1657814452175/work
yarl @ file:///C:/Users/BUILDE~1/AppData/Local/Temp/abs_e5nlunspj6/croots/recipe/yarl_1661437086516/work
zipp @ file:///C:/b/abs_b9jfdr908q/croot/zipp_1672387552360/work
(gpy0.18.2) PS J:\My Documents\CTA_Analysis\GRB paper\SoHAPPy>
```

**Comment by jacobtylerwalls** [comment]
Hi @tstolarczyk. We're not maintaining pylint 2 any more. Can you reproduce on pylint 3? Thanks in advance.
