### ISSUE TITLE
Crash AttributeError: 'TreeRebuilder' object has no attribute 'visit_typealias'

### ISSUE THREAD

**Issue by matlads** [pylint-dev/pylint#9276]
### Bug description

Sharing the code is not an option, but the stacktrace is provided.

pylint crashed with a ``AstroidError`` and with the following stacktrace:

```
Traceback (most recent call last):
  File "/Users/martin/.virtualenvs/tmcg-services/lib/python3.12/site-packages/pylint/checkers/imports.py", line 858, in _get_imported_module
    return importnode.do_import_module(modname)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/martin/.virtualenvs/tmcg-services/lib/python3.12/site-packages/astroid/nodes/_base_nodes.py", line 146, in do_import_module
    return mymodule.import_module(
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/martin/.virtualenvs/tmcg-services/lib/python3.12/site-packages/astroid/nodes/scoped_nodes/scoped_nodes.py", line 530, in import_module
    return AstroidManager().ast_from_module_name(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/martin/.virtualenvs/tmcg-services/lib/python3.12/site-packages/astroid/manager.py", line 246, in ast_from_module_name
    return self.ast_from_file(found_spec.location, modname, fallback=False)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/martin/.virtualenvs/tmcg-services/lib/python3.12/site-packages/astroid/manager.py", line 138, in ast_from_file
    return AstroidBuilder(self).file_build(filepath, modname)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/martin/.virtualenvs/tmcg-services/lib/python3.12/site-packages/astroid/builder.py", line 144, in file_build
    module, builder = self._data_build(data, modname, path)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/martin/.virtualenvs/tmcg-services/lib/python3.12/site-packages/astroid/builder.py", line 204, in _data_build
    module = builder.visit_module(node, modname, node_file, package)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/martin/.virtualenvs/tmcg-services/lib/python3.12/site-packages/astroid/rebuilder.py", line 254, in visit_module
    [self.visit(child, newnode) for child in node.body],
     ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/martin/.virtualenvs/tmcg-services/lib/python3.12/site-packages/astroid/rebuilder.py", line 609, in visit
    visit_method = getattr(self, visit_name)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'TreeRebuilder' object has no attribute 'visit_typealias'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/martin/.virtualenvs/tmcg-services/lib/python3.12/site-packages/pylint/lint/pylinter.py", line 811, in _lint_file
    check_astroid_module(module)
  File "/Users/martin/.virtualenvs/tmcg-services/lib/python3.12/site-packages/pylint/lint/pylinter.py", line 1085, in check_astroid_module
    retval = self._check_astroid_module(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/martin/.virtualenvs/tmcg-services/lib/python3.12/site-packages/pylint/lint/pylinter.py", line 1135, in _check_astroid_module
    walker.walk(node)
  File "/Users/martin/.virtualenvs/tmcg-services/lib/python3.12/site-packages/pylint/utils/ast_walker.py", line 94, in walk
    self.walk(child)
  File "/Users/martin/.virtualenvs/tmcg-services/lib/python3.12/site-packages/pylint/utils/ast_walker.py", line 91, in walk
    callback(astroid)
  File "/Users/martin/.virtualenvs/tmcg-services/lib/python3.12/site-packages/pylint/checkers/imports.py", line 549, in visit_importfrom
    imported_module = self._get_imported_module(node, basename)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/martin/.virtualenvs/tmcg-services/lib/python3.12/site-packages/pylint/checkers/imports.py", line 883, in _get_imported_module
    raise astroid.AstroidError from e
astroid.exceptions.AstroidError

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/martin/.virtualenvs/tmcg-services/lib/python3.12/site-packages/pylint/lint/pylinter.py", line 775, in _lint_files
    self._lint_file(fileitem, module, check_astroid_module)
  File "/Users/martin/.virtualenvs/tmcg-services/lib/python3.12/site-packages/pylint/lint/pylinter.py", line 813, in _lint_file
    raise astroid.AstroidError from e
astroid.exceptions.AstroidError
```

### Command used

```shell
prospector clinic/views.py
```

### Pylint output

```python
pylint: astroid-error / /Users/martin/Work/tmcg/tmcg-services/clinic/views.py: Fatal error while checking '/Users/martin/Work/tmcg/tmcg-services/clinic/views.py'. Please open an issue in our bug tracker so we address this. There is a pre-filled template that you can use in '/Users/martin/Library/Caches/pylint/pylint-crash-2023-12-02-03-07-31.txt'.
```

### Expected behavior

.

### Pylint version

```shell
pylint 2.17.7
astroid 2.15.8
Python 3.12.0 (main, Oct  2 2023, 12:03:24) [Clang 15.0.0 (clang-1500.0.40.1)]
```

### OS / Environment

macosx 14.1.1 (23B81)

### Additional dependencies

```python
pylint-django==2.5.3
```

**Comment by jacobtylerwalls** [comment]
Python 3.12 is only supported on pylint 3+

**Comment by Pierre-Sassoulas** [comment]
Maybe we could release a 2.17.x with a warning that it does not support python 3.12 ? We have a lot of issues opened for this.

**Comment by jacobtylerwalls** [comment]
I'm not too worried about it. I'd rather reinforce the practice that users attempt to reproduce issues on latest.
