### ISSUE TITLE
Crash - on windows - pylint crashed with a ``AstroidError`` - UnicodeEncodeError: 'charmap' codec can't encode characters in position

### ISSUE THREAD

**Issue by sarzamas** [pylint-dev/pylint#9277]
\U0001f4a5 Needs triage \U0001f4e5

When parsing the following ``.py`` file: https://github.com/sarzamas/pytest_rest_example_pets/blob/main/tests/pet/conftest.py

### OS / Environment
GitHub Actions for this public project
Runner - latest  (Windows)

### Command used

```shell
pylint $(git ls-files '*.py')
```

### Pylint output

<details open>
    <summary>
        pylint crashed with a ``AstroidError`` and with the following stacktrace:
    </summary>

```python
Traceback (most recent call last):
  File "C:\hostedtoolcache\windows\Python\3.12.0\x64\Lib\site-packages\pylint\lint\pylinter.py", line 788, in _lint_file
    check_astroid_module(module)
  File "C:\hostedtoolcache\windows\Python\3.12.0\x64\Lib\site-packages\pylint\lint\pylinter.py", line 1017, in check_astroid_module
    retval = self._check_astroid_module(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\hostedtoolcache\windows\Python\3.12.0\x64\Lib\site-packages\pylint\lint\pylinter.py", line 1067, in _check_astroid_module
    token_checker.process_tokens(tokens)
  File "C:\hostedtoolcache\windows\Python\3.12.0\x64\Lib\site-packages\pylint\checkers\misc.py", line [142](https://github.com/sarzamas/pytest_rest_example_pets/actions/runs/7075711476/job/19258131799#step:8:143), in process_tokens
    self.add_message(
  File "C:\hostedtoolcache\windows\Python\3.12.0\x64\Lib\site-packages\pylint\checkers\base_checker.py", line 153, in add_message
    self.linter.add_message(
  File "C:\hostedtoolcache\windows\Python\3.12.0\x64\Lib\site-packages\pylint\lint\pylinter.py", line 1262, in add_message
    self._add_one_message(
  File "C:\hostedtoolcache\windows\Python\3.12.0\x64\Lib\site-packages\pylint\lint\pylinter.py", line 1220, in _add_one_message
    self.reporter.handle_message(
  File "C:\hostedtoolcache\windows\Python\3.12.0\x64\Lib\site-packages\pylint\reporters\text.py", line 255, in handle_message
    self.write_message(msg)
  File "C:\hostedtoolcache\windows\Python\3.12.0\x64\Lib\site-packages\pylint\reporters\text.py", line 154, in write_message
    self.writeln(self._fixed_template.format(**self_dict))
  File "C:\hostedtoolcache\windows\Python\3.12.0\x64\Lib\site-packages\pylint\reporters\base_reporter.py", line 45, in writeln
    print(string, file=self.out)
  File "C:\hostedtoolcache\windows\Python\3.12.0\x64\Lib\site-packages\colorama\ansitowin32.py", line 177, in write
    self.write_and_convert(text)
  File "C:\hostedtoolcache\windows\Python\3.12.0\x64\Lib\site-packages\colorama\ansitowin32.py", line 202, in write_and_convert
    self.write_plain_text(text, cursor, start)
  File "C:\hostedtoolcache\windows\Python\3.12.0\x64\Lib\site-packages\colorama\ansitowin32.py", line 210, in write_plain_text
    self.wrapped.write(text[start:end])
  File "C:\hostedtoolcache\windows\Python\3.12.0\x64\Lib\encodings\cp1252.py", line 19, in encode
    return codecs.charmap_encode(input,self.errors,encoding_table)[0]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
UnicodeEncodeError: 'charmap' codec can't encode characters in position 10-17: character maps to <undefined>

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\hostedtoolcache\windows\Python\3.12.0\x64\Lib\site-packages\pylint\lint\pylinter.py", line 752, in _lint_files
    self._lint_file(fileitem, module, check_astroid_module)
  File "C:\hostedtoolcache\windows\Python\3.12.0\x64\Lib\site-packages\pylint\lint\pylinter.py", line 790, in _lint_file
    raise astroid.AstroidError from e
astroid.exceptions.AstroidError

```

</details>

### Expected behavior

No crash.

### Pylint version

```shell
pylint 3.0.2
astroid 3.0.1
Python 3.12.0 (tags/v3.12.0:0fb18b0, Oct  2 2023, 13:03:39) [MSC v.1935 64 bit (AMD64)]
```

### OS / Environment

win32 (Windows)

**Comment by jhaneyrf** [comment]
Since I had a similar error today with Pylint 4.0.3 and this thing says "Needs investigation", I thought I'd add what I've discovered.

I am also on a Windows machine, and I use GitBash for most of my work. I got the UnicodeEncodeError when I tried to run the following command in a GitBash window: `find . -name "*.py" -exec pylint {} + > pylint_output.txt`. However, when I ran it without directing the output to a file, pylint successfully ran to completion.

The spot where the error is occurring is when it's reporting similar code blocks in different files. I guess one of those code blocks has a character that can't be converted from UTF-8 to cp1252. For some reason, that encoder is the one that gets chosen when output is directed to a file but a different encoder is chosen when the output goes directly to the GitBash terminal.

If you think this should be a separate issue, please let me know.

**Comment by jhaneyrf** [comment]
One last update, when I set the --output option instead of using the Unix redirect operator, it also runs to completion.
