### ISSUE TITLE
prettier bombs out in pre-commit config

### ISSUE THREAD

**Issue by jacobtylerwalls** [pylint-dev/pylint#9300]
Can we downgrade prettier?

```
prettier.................................................................Failed
- hook id: prettier
- exit code: 1

ReferenceError: EventTarget is not defined
    at file:///Users/jwalls/.cache/pre-commit/repob1p97h4u/node_env-system/lib/node_modules/prettier/node_modules/webworker-shim/dist/node.js:16:26
    at ModuleJob.run (internal/modules/esm/module_job.js:170:25)
    at async Loader.import (internal/modules/esm/loader.js:178:24)
    at async makePrettier (file:///Users/jwalls/.cache/pre-commit/repob1p97h4u/node_env-system/lib/node_modules/prettier/node_modules/@prettier/cli/dist/prettier.js:4:34)
    at async run (file:///Users/jwalls/.cache/pre-commit/repob1p97h4u/node_env-system/lib/node_modules/prettier/node_modules/@prettier/cli/dist/index.js:39:22)
    at async Bin.run (file:///Users/jwalls/.cache/pre-commit/repob1p97h4u/node_env-system/lib/node_modules/prettier/node_modules/tiny-bin/dist/objects/bin.js:66:13)
```

**Comment by Pierre-Sassoulas** [comment]
Yeah, maybe upgrading to an alpha wasn't such a bright idea after all 😅

**Comment by Pierre-Sassoulas** [comment]
https://github.com/prettier/prettier/releases/tag/3.1.1 went out yesterday, not available yet on the mirror, let's wait a little maybe ? Or if it's a big blocker then 3.1.0 would do.
