### ISSUE TITLE
Crash with astroid-error

### ISSUE THREAD

**Issue by snowingsea** [pylint-dev/pylint#9348]
### Bug description

```python
When parsing the following file:

<!--
 If sharing the code is not an option, please state so,
 but providing only the stacktrace would still be helpful.
 -->


import time
import akshare

stock_individual_info_em_df = akshare.stock_individual_info_em()
time.strptime(str(stock_individual_info_em_df['value'][3]), '%Y%m%d')



pylint crashed with a ``AstroidError`` and with the following stacktrace:
```
Traceback (most recent call last):
  File "/usr/local/Caskroom/miniconda/base/envs/trident/lib/python3.12/site-packages/pylint/checkers/utils.py", line 1370, in safe_infer
    value = next(infer_gen)
            ^^^^^^^^^^^^^^^
  File "/usr/local/Caskroom/miniconda/base/envs/trident/lib/python3.12/site-packages/astroid/nodes/node_ng.py", line 171, in infer
    yield from self._infer(context=context, **kwargs)
  File "/usr/local/Caskroom/miniconda/base/envs/trident/lib/python3.12/site-packages/astroid/decorators.py", line 142, in raise_if_nothing_inferred
    yield next(generator)
          ^^^^^^^^^^^^^^^
  File "/usr/local/Caskroom/miniconda/base/envs/trident/lib/python3.12/site-packages/astroid/decorators.py", line 111, in wrapped
    for res in _func(node, context, **kwargs):
  File "/usr/local/Caskroom/miniconda/base/envs/trident/lib/python3.12/site-packages/astroid/inference.py", line 279, in infer_call
    yield from callee.infer_call_result(caller=self, context=callcontext)
  File "/usr/local/Caskroom/miniconda/base/envs/trident/lib/python3.12/site-packages/astroid/nodes/scoped_nodes/scoped_nodes.py", line 1733, in infer_call_result
    yield from returnnode.value.infer(context)
  File "/usr/local/Caskroom/miniconda/base/envs/trident/lib/python3.12/site-packages/astroid/nodes/node_ng.py", line 184, in infer
    for i, result in enumerate(self._infer(context=context, **kwargs)):
  File "/usr/local/Caskroom/miniconda/base/envs/trident/lib/python3.12/site-packages/astroid/decorators.py", line 142, in raise_if_nothing_inferred
    yield next(generator)
          ^^^^^^^^^^^^^^^
  File "/usr/local/Caskroom/miniconda/base/envs/trident/lib/python3.12/site-packages/astroid/decorators.py", line 111, in wrapped
    for res in _func(node, context, **kwargs):
  File "/usr/local/Caskroom/miniconda/base/envs/trident/lib/python3.12/site-packages/astroid/bases.py", line 176, in _infer_stmts
    for inf in stmt.infer(context=context):  # type: ignore[union-attr]
  File "/usr/local/Caskroom/miniconda/base/envs/trident/lib/python3.12/site-packages/astroid/nodes/node_ng.py", line 184, in infer
    for i, result in enumerate(self._infer(context=context, **kwargs)):
  File "/usr/local/Caskroom/miniconda/base/envs/trident/lib/python3.12/site-packages/astroid/decorators.py", line 142, in raise_if_nothing_inferred
    yield next(generator)
          ^^^^^^^^^^^^^^^
  File "/usr/local/Caskroom/miniconda/base/envs/trident/lib/python3.12/site-packages/astroid/decorators.py", line 111, in wrapped
    for res in _func(node, context, **kwargs):
  File "/usr/local/Caskroom/miniconda/base/envs/trident/lib/python3.12/site-packages/astroid/bases.py", line 176, in _infer_stmts
    for inf in stmt.infer(context=context):  # type: ignore[union-attr]
  File "/usr/local/Caskroom/miniconda/base/envs/trident/lib/python3.12/site-packages/astroid/nodes/node_ng.py", line 184, in infer
    for i, result in enumerate(self._infer(context=context, **kwargs)):
  File "/usr/local/Caskroom/miniconda/base/envs/trident/lib/python3.12/site-packages/astroid/decorators.py", line 142, in raise_if_nothing_inferred
    yield next(generator)
          ^^^^^^^^^^^^^^^
  File "/usr/local/Caskroom/miniconda/base/envs/trident/lib/python3.12/site-packages/astroid/decorators.py", line 111, in wrapped
    for res in _func(node, context, **kwargs):
  File "/usr/local/Caskroom/miniconda/base/envs/trident/lib/python3.12/site-packages/astroid/inference.py", line 426, in infer_subscript
    for value in self.value.infer(context):
  File "/usr/local/Caskroom/miniconda/base/envs/trident/lib/python3.12/site-packages/astroid/nodes/node_ng.py", line 184, in infer
    for i, result in enumerate(self._infer(context=context, **kwargs)):
  File "/usr/local/Caskroom/miniconda/base/envs/trident/lib/python3.12/site-packages/astroid/decorators.py", line 142, in raise_if_nothing_inferred
    yield next(generator)
          ^^^^^^^^^^^^^^^
  File "/usr/local/Caskroom/miniconda/base/envs/trident/lib/python3.12/site-packages/astroid/decorators.py", line 111, in wrapped
    for res in _func(node, context, **kwargs):
  File "/usr/local/Caskroom/miniconda/base/envs/trident/lib/python3.12/site-packages/astroid/bases.py", line 176, in _infer_stmts
    for inf in stmt.infer(context=context):  # type: ignore[union-attr]
  File "/usr/local/Caskroom/miniconda/base/envs/trident/lib/python3.12/site-packages/astroid/nodes/node_ng.py", line 184, in infer
    for i, result in enumerate(self._infer(context=context, **kwargs)):
  File "/usr/local/Caskroom/miniconda/base/envs/trident/lib/python3.12/site-packages/astroid/decorators.py", line 142, in raise_if_nothing_inferred
    yield next(generator)
          ^^^^^^^^^^^^^^^
  File "/usr/local/Caskroom/miniconda/base/envs/trident/lib/python3.12/site-packages/astroid/decorators.py", line 111, in wrapped
    for res in _func(node, context, **kwargs):
  File "/usr/local/Caskroom/miniconda/base/envs/trident/lib/python3.12/site-packages/astroid/bases.py", line 176, in _infer_stmts
    for inf in stmt.infer(context=context):  # type: ignore[union-attr]
  File "/usr/local/Caskroom/miniconda/base/envs/trident/lib/python3.12/site-packages/astroid/nodes/node_ng.py", line 184, in infer
    for i, result in enumerate(self._infer(context=context, **kwargs)):
  File "/usr/local/Caskroom/miniconda/base/envs/trident/lib/python3.12/site-packages/astroid/decorators.py", line 142, in raise_if_nothing_inferred
    yield next(generator)
          ^^^^^^^^^^^^^^^
  File "/usr/local/Caskroom/miniconda/base/envs/trident/lib/python3.12/site-packages/astroid/decorators.py", line 111, in wrapped
    for res in _func(node, context, **kwargs):
  File "/usr/local/Caskroom/miniconda/base/envs/trident/lib/python3.12/site-packages/astroid/inference.py", line 279, in infer_call
    yield from callee.infer_call_result(caller=self, context=callcontext)
  File "/usr/local/Caskroom/miniconda/base/envs/trident/lib/python3.12/site-packages/astroid/nodes/scoped_nodes/scoped_nodes.py", line 2265, in infer_call_result
    if self.is_subtype_of("builtins.type", context) and len(caller.args) == 3:
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/Caskroom/miniconda/base/envs/trident/lib/python3.12/site-packages/astroid/nodes/scoped_nodes/scoped_nodes.py", line 2213, in is_subtype_of
    return any(anc.qname() == type_name for anc in self.ancestors(context=context))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/Caskroom/miniconda/base/envs/trident/lib/python3.12/site-packages/astroid/nodes/scoped_nodes/scoped_nodes.py", line 2213, in <genexpr>
    return any(anc.qname() == type_name for anc in self.ancestors(context=context))
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/Caskroom/miniconda/base/envs/trident/lib/python3.12/site-packages/astroid/nodes/scoped_nodes/scoped_nodes.py", line 2387, in ancestors
    for grandpa in baseobj.ancestors(recurs=True, context=context):
  File "/usr/local/Caskroom/miniconda/base/envs/trident/lib/python3.12/site-packages/astroid/nodes/scoped_nodes/scoped_nodes.py", line 2374, in ancestors
    for baseobj in stmt.infer(context):
  File "/usr/local/Caskroom/miniconda/base/envs/trident/lib/python3.12/site-packages/astroid/nodes/node_ng.py", line 184, in infer
    for i, result in enumerate(self._infer(context=context, **kwargs)):
  File "/usr/local/Caskroom/miniconda/base/envs/trident/lib/python3.12/site-packages/astroid/decorators.py", line 142, in raise_if_nothing_inferred
    yield next(generator)
          ^^^^^^^^^^^^^^^
  File "/usr/local/Caskroom/miniconda/base/envs/trident/lib/python3.12/site-packages/astroid/decorators.py", line 111, in wrapped
    for res in _func(node, context, **kwargs):
  File "/usr/local/Caskroom/miniconda/base/envs/trident/lib/python3.12/site-packages/astroid/inference.py", line 358, in infer_attribute
    for owner in self.expr.infer(context):
  File "/usr/local/Caskroom/miniconda/base/envs/trident/lib/python3.12/site-packages/astroid/nodes/node_ng.py", line 184, in infer
    for i, result in enumerate(self._infer(context=context, **kwargs)):
  File "/usr/local/Caskroom/miniconda/base/envs/trident/lib/python3.12/site-packages/astroid/decorators.py", line 142, in raise_if_nothing_inferred
    yield next(generator)
          ^^^^^^^^^^^^^^^
  File "/usr/local/Caskroom/miniconda/base/envs/trident/lib/python3.12/site-packages/astroid/decorators.py", line 111, in wrapped
    for res in _func(node, context, **kwargs):
  File "/usr/local/Caskroom/miniconda/base/envs/trident/lib/python3.12/site-packages/astroid/bases.py", line 176, in _infer_stmts
    for inf in stmt.infer(context=context):  # type: ignore[union-attr]
  File "/usr/local/Caskroom/miniconda/base/envs/trident/lib/python3.12/site-packages/astroid/nodes/node_ng.py", line 184, in infer
    for i, result in enumerate(self._infer(context=context, **kwargs)):
  File "/usr/local/Caskroom/miniconda/base/envs/trident/lib/python3.12/site-packages/astroid/decorators.py", line 142, in raise_if_nothing_inferred
    yield next(generator)
          ^^^^^^^^^^^^^^^
  File "/usr/local/Caskroom/miniconda/base/envs/trident/lib/python3.12/site-packages/astroid/decorators.py", line 111, in wrapped
    for res in _func(node, context, **kwargs):
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/Caskroom/miniconda/base/envs/trident/lib/python3.12/site-packages/astroid/inference.py", line 341, in infer_import_from
    stmts = module.getattr(name, ignore_locals=module is self.root())
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/Caskroom/miniconda/base/envs/trident/lib/python3.12/site-packages/astroid/nodes/scoped_nodes/scoped_nodes.py", line 412, in getattr
    result = [self.import_module(name, relative_only=True)]
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/Caskroom/miniconda/base/envs/trident/lib/python3.12/site-packages/astroid/nodes/scoped_nodes/scoped_nodes.py", line 527, in import_module
    return AstroidManager().ast_from_module_name(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/Caskroom/miniconda/base/envs/trident/lib/python3.12/site-packages/astroid/manager.py", line 232, in ast_from_module_name
    return self.ast_from_file(found_spec.location, modname, fallback=False)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/Caskroom/miniconda/base/envs/trident/lib/python3.12/site-packages/astroid/manager.py", line 124, in ast_from_file
    return AstroidBuilder(self).file_build(filepath, modname)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/Caskroom/miniconda/base/envs/trident/lib/python3.12/site-packages/astroid/builder.py", line 145, in file_build
    return self._post_build(module, builder, encoding)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/Caskroom/miniconda/base/envs/trident/lib/python3.12/site-packages/astroid/builder.py", line 169, in _post_build
    self.delayed_assattr(delayed)
  File "/usr/local/Caskroom/miniconda/base/envs/trident/lib/python3.12/site-packages/astroid/builder.py", line 240, in delayed_assattr
    for inferred in node.expr.infer():
  File "/usr/local/Caskroom/miniconda/base/envs/trident/lib/python3.12/site-packages/astroid/nodes/node_ng.py", line 171, in infer
    yield from self._infer(context=context, **kwargs)
  File "/usr/local/Caskroom/miniconda/base/envs/trident/lib/python3.12/site-packages/astroid/decorators.py", line 142, in raise_if_nothing_inferred
    yield next(generator)
          ^^^^^^^^^^^^^^^
  File "/usr/local/Caskroom/miniconda/base/envs/trident/lib/python3.12/site-packages/astroid/decorators.py", line 111, in wrapped
    for res in _func(node, context, **kwargs):
  File "/usr/local/Caskroom/miniconda/base/envs/trident/lib/python3.12/site-packages/astroid/inference.py", line 358, in infer_attribute
    for owner in self.expr.infer(context):
  File "/usr/local/Caskroom/miniconda/base/envs/trident/lib/python3.12/site-packages/astroid/nodes/node_ng.py", line 184, in infer
    for i, result in enumerate(self._infer(context=context, **kwargs)):
  File "/usr/local/Caskroom/miniconda/base/envs/trident/lib/python3.12/site-packages/astroid/decorators.py", line 142, in raise_if_nothing_inferred
    yield next(generator)
          ^^^^^^^^^^^^^^^
  File "/usr/local/Caskroom/miniconda/base/envs/trident/lib/python3.12/site-packages/astroid/decorators.py", line 111, in wrapped
    for res in _func(node, context, **kwargs):
  File "/usr/local/Caskroom/miniconda/base/envs/trident/lib/python3.12/site-packages/astroid/bases.py", line 176, in _infer_stmts
    for inf in stmt.infer(context=context):  # type: ignore[union-attr]
  File "/usr/local/Caskroom/miniconda/base/envs/trident/lib/python3.12/site-packages/astroid/nodes/node_ng.py", line 184, in infer
    for i, result in enumerate(self._infer(context=context, **kwargs)):
  File "/usr/local/Caskroom/miniconda/base/envs/trident/lib/python3.12/site-packages/astroid/decorators.py", line 142, in raise_if_nothing_inferred
    yield next(generator)
          ^^^^^^^^^^^^^^^
  File "/usr/local/Caskroom/miniconda/base/envs/trident/lib/python3.12/site-packages/astroid/decorators.py", line 111, in wrapped
    for res in _func(node, context, **kwargs):
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/Caskroom/miniconda/base/envs/trident/lib/python3.12/site-packages/astroid/inference.py", line 1152, in infer_assign
    stmts = list(self.assigned_stmts(context=context))
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/Caskroom/miniconda/base/envs/trident/lib/python3.12/site-packages/astroid/protocols.py", line 398, in _arguments_infer_argname
    functype = self.parent.type
               ^^^^^^^^^^^^^^^^
  File "/usr/local/Caskroom/miniconda/base/envs/trident/lib/python3.12/functools.py", line 995, in __get__
    val = self.func(instance)
          ^^^^^^^^^^^^^^^^^^^
  File "/usr/local/Caskroom/miniconda/base/envs/trident/lib/python3.12/site-packages/astroid/nodes/scoped_nodes/scoped_nodes.py", line 1510, in type
    for inferred in node.infer():
  File "/usr/local/Caskroom/miniconda/base/envs/trident/lib/python3.12/site-packages/astroid/nodes/node_ng.py", line 171, in infer
    yield from self._infer(context=context, **kwargs)
  File "/usr/local/Caskroom/miniconda/base/envs/trident/lib/python3.12/site-packages/astroid/decorators.py", line 142, in raise_if_nothing_inferred
    yield next(generator)
          ^^^^^^^^^^^^^^^
  File "/usr/local/Caskroom/miniconda/base/envs/trident/lib/python3.12/site-packages/astroid/decorators.py", line 111, in wrapped
    for res in _func(node, context, **kwargs):
  File "/usr/local/Caskroom/miniconda/base/envs/trident/lib/python3.12/site-packages/astroid/bases.py", line 176, in _infer_stmts
    for inf in stmt.infer(context=context):  # type: ignore[union-attr]
  File "/usr/local/Caskroom/miniconda/base/envs/trident/lib/python3.12/site-packages/astroid/nodes/node_ng.py", line 184, in infer
    for i, result in enumerate(self._infer(context=context, **kwargs)):
  File "/usr/local/Caskroom/miniconda/base/envs/trident/lib/python3.12/site-packages/astroid/decorators.py", line 142, in raise_if_nothing_inferred
    yield next(generator)
          ^^^^^^^^^^^^^^^
  File "/usr/local/Caskroom/miniconda/base/envs/trident/lib/python3.12/site-packages/astroid/decorators.py", line 111, in wrapped
    for res in _func(node, context, **kwargs):
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/Caskroom/miniconda/base/envs/trident/lib/python3.12/site-packages/astroid/inference.py", line 334, in infer_import_from
    module = self.do_import_module()
             ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/Caskroom/miniconda/base/envs/trident/lib/python3.12/site-packages/astroid/nodes/_base_nodes.py", line 146, in do_import_module
    return mymodule.import_module(
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/Caskroom/miniconda/base/envs/trident/lib/python3.12/site-packages/astroid/nodes/scoped_nodes/scoped_nodes.py", line 527, in import_module
    return AstroidManager().ast_from_module_name(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/Caskroom/miniconda/base/envs/trident/lib/python3.12/site-packages/astroid/manager.py", line 232, in ast_from_module_name
    return self.ast_from_file(found_spec.location, modname, fallback=False)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/Caskroom/miniconda/base/envs/trident/lib/python3.12/site-packages/astroid/manager.py", line 124, in ast_from_file
    return AstroidBuilder(self).file_build(filepath, modname)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/Caskroom/miniconda/base/envs/trident/lib/python3.12/site-packages/astroid/builder.py", line 144, in file_build
    module, builder = self._data_build(data, modname, path)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/Caskroom/miniconda/base/envs/trident/lib/python3.12/site-packages/astroid/builder.py", line 204, in _data_build
    module = builder.visit_module(node, modname, node_file, package)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/Caskroom/miniconda/base/envs/trident/lib/python3.12/site-packages/astroid/rebuilder.py", line 254, in visit_module
    [self.visit(child, newnode) for child in node.body],
     ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/Caskroom/miniconda/base/envs/trident/lib/python3.12/site-packages/astroid/rebuilder.py", line 603, in visit
    visit_method = getattr(self, visit_name)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'TreeRebuilder' object has no attribute 'visit_typealias'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/Caskroom/miniconda/base/envs/trident/lib/python3.12/site-packages/pylint/lint/pylinter.py", line 798, in _lint_file
    check_astroid_module(module)
  File "/usr/local/Caskroom/miniconda/base/envs/trident/lib/python3.12/site-packages/pylint/lint/pylinter.py", line 1067, in check_astroid_module
    retval = self._check_astroid_module(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/Caskroom/miniconda/base/envs/trident/lib/python3.12/site-packages/pylint/lint/pylinter.py", line 1117, in _check_astroid_module
    walker.walk(node)
  File "/usr/local/Caskroom/miniconda/base/envs/trident/lib/python3.12/site-packages/pylint/utils/ast_walker.py", line 94, in walk
    self.walk(child)
  File "/usr/local/Caskroom/miniconda/base/envs/trident/lib/python3.12/site-packages/pylint/utils/ast_walker.py", line 94, in walk
    self.walk(child)
  File "/usr/local/Caskroom/miniconda/base/envs/trident/lib/python3.12/site-packages/pylint/utils/ast_walker.py", line 91, in walk
    callback(astroid)
  File "/usr/local/Caskroom/miniconda/base/envs/trident/lib/python3.12/site-packages/pylint/checkers/base/name_checker/checker.py", line 416, in visit_assignname
    inferred_assign_type = utils.safe_infer(assign_type.value)
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/Caskroom/miniconda/base/envs/trident/lib/python3.12/site-packages/pylint/checkers/utils.py", line 1374, in safe_infer
    raise AstroidError from e
astroid.exceptions.AstroidError

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/Caskroom/miniconda/base/envs/trident/lib/python3.12/site-packages/pylint/lint/pylinter.py", line 763, in _lint_files
    self._lint_file(fileitem, module, check_astroid_module)
  File "/usr/local/Caskroom/miniconda/base/envs/trident/lib/python3.12/site-packages/pylint/lint/pylinter.py", line 800, in _lint_file
    raise astroid.AstroidError from e
astroid.exceptions.AstroidError
```
```

### Command used

```shell
pylint test.py
```

### Pylint output

```python
crashed.
```

### Expected behavior

not crash

### Pylint version

```shell
pylint 2.16.2
astroid 2.14.2
Python 3.12.1 | packaged by conda-forge | (main, Dec 23 2023, 08:05:03) [Clang 16.0.6 ]
```

### OS / Environment

MacOS

**Comment by jacobtylerwalls** [comment]
Python 3.12 is only supported by pylint 3.
