### ISSUE TITLE
Binary distribution is too old that out of support in deb.debian.org

### ISSUE THREAD

**Issue by ChenPi11** [pylint-dev/pylint#9370]
### Bug description

Binary distribution is too old that it is out of support.
After I installed the pylint in Debian. It raised this exception:

```
Traceback (most recent call last):
  File "/usr/bin/pylint", line 8, in <module>
    sys.exit(run_pylint())
             ^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/pylint/__init__.py", line 36, in run_pylint
    PylintRun(argv or sys.argv[1:])
  File "/usr/lib/python3/dist-packages/pylint/lint/run.py", line 157, in __init__
    linter.load_default_plugins()
  File "/usr/lib/python3/dist-packages/pylint/lint/pylinter.py", line 369, in load_default_plugins
    checkers.initialize(self)
  File "/usr/lib/python3/dist-packages/pylint/checkers/__init__.py", line 136, in initialize
    register_plugins(linter, __path__[0])
  File "/usr/lib/python3/dist-packages/pylint/utils/utils.py", line 204, in register_plugins
    module = modutils.load_module_from_file(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/astroid/modutils.py", line 235, in load_module_from_file
    return load_module_from_modpath(modpath)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/astroid/modutils.py", line 220, in load_module_from_modpath
    return load_module_from_name(".".join(parts))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/astroid/modutils.py", line 194, in load_module_from_name
    module = importlib.import_module(dotted_name)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/usr/lib/python3/dist-packages/pylint/checkers/refactoring/__init__.py", line 16, in <module>
    from pylint.checkers.refactoring.refactoring_checker import RefactoringChecker
  File "/usr/lib/python3/dist-packages/pylint/checkers/refactoring/refactoring_checker.py", line 36, in <module>
    nodes.TryExcept, nodes.TryFinally, nodes.While, nodes.For, nodes.If
    ^^^^^^^^^^^^^^^
AttributeError: module 'astroid.nodes' has no attribute 'TryExcept'
```
I tkink the binary distribution of pylint in too old in deb.debian.org. The current version is 3.0.x but the version in Debian is 2.17.4 now.

### Command used

```shell
apt show pylint
```

### Pylint output

```python
Package: pylint
Version: 2.17.4-1
Priority: optional
Section: python
Maintainer: Sandro Tosi <morph@debian.org>
Installed-Size: 2,096 kB
Depends: python3-astroid (>= 2.15.4), python3-isort (<< 6), python3-logilab-common (>= 0.19.0), python3-setuptools, python3-dill (>= 0.3.6) | python3 (<< 3.11), python3-dill (>= 0.3.6) | python3 (>> 3.11), python3-isort (>= 4.2.5), python3-mccabe, python3-platformdirs (>= 2.2.0), python3-tomli | python3 (>> 3.11), python3-tomlkit, python3-typing-extensions (>= 3.10.0) | python3 (>> 3.10), python3:any
Recommends: python3-tk
Suggests: pylint-doc
Breaks: python3-pylint-django (<< 2.0), python3-pylint-plugin-utils (<< 0.4), python3-pytest-pylint (<< 0.10)
Homepage: https://pylint.pycqa.org/
Tag: devel::debugger, devel::lang:python, implemented-in::python,
 interface::commandline, role::program, use::checking,
 works-with::software:source
Download-Size: 343 kB
APT-Manual-Installed: yes
APT-Sources: https://deb.debian.org/debian sid/main amd64 Packages
Description: Python 3 code static checker and UML diagram generator
 Pylint is a Python source code analyzer which looks for programming
 errors, helps enforcing a coding standard and sniffs for some code
 smells (as defined in Martin Fowler's Refactoring book)
 .
 Pylint can be seen as another PyChecker since nearly all tests you
 can do with PyChecker can also be done with Pylint. However, Pylint
 offers some more features, like checking length of lines of code,
 checking if variable names are well-formed according to your coding
 standard, or checking if declared interfaces are truly implemented,
 and much more.
 .
 Additionally, it is possible to write plugins to add your own checks.
 .
 The package also ships the following additional commands:
 .
   * pyreverse: an UML diagram generator
   * symilar: an independent similarities checker
   * epylint: Emacs and Flymake compatible Pylint
```

### Expected behavior

Update to latest version.

### Pylint version

```shell
2.17.4
```

### OS / Environment

Debian

**Comment by opk12** [comment]
Just a heads up, if your org does not trust pip's broken security model, that pylint is up-to-date and working in Sid now (v3.0.3). Sid is the future Stable's staging area, where you can monitor the temporary pkg dependency mismatches. You can ping the maintainers to update the package, on the mailing list or IRC.  https://wiki.debian.org/Python#Maintainers
