### ISSUE TITLE
astroid.node Attribute Error

### ISSUE THREAD

**Issue by nullsurface** [pylint-dev/pylint#9411]
### Bug description

```python
After updating all packages with xbps, python3-pylint threw the attribute error below. After reinstalling pylint, this error still occurs.
```

### Command used

```shell
pylint
```

### Pylint output

```python
Traceback (most recent call last):
  File "/usr/bin/pylint", line 8, in <module>
    sys.exit(run_pylint())
             ^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/pylint/__init__.py", line 36, in run_pylint
    PylintRun(argv or sys.argv[1:])
  File "/usr/lib/python3.12/site-packages/pylint/lint/run.py", line 157, in __init__
    linter.load_default_plugins()
  File "/usr/lib/python3.12/site-packages/pylint/lint/pylinter.py", line 369, in load_default_plugins
    checkers.initialize(self)
  File "/usr/lib/python3.12/site-packages/pylint/checkers/__init__.py", line 136, in initialize
    register_plugins(linter, __path__[0])
  File "/usr/lib/python3.12/site-packages/pylint/utils/utils.py", line 204, in register_plugins
    module = modutils.load_module_from_file(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/astroid/modutils.py", line 235, in load_module_from_file
    return load_module_from_modpath(modpath)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/astroid/modutils.py", line 220, in load_module_from_modpath
    return load_module_from_name(".".join(parts))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/astroid/modutils.py", line 194, in load_module_from_name
    module = importlib.import_module(dotted_name)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/importlib/__init__.py", line 90, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 994, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/usr/lib/python3.12/site-packages/pylint/checkers/refactoring/__init__.py", line 16, in <module>
    from pylint.checkers.refactoring.refactoring_checker import RefactoringChecker
  File "/usr/lib/python3.12/site-packages/pylint/checkers/refactoring/refactoring_checker.py", line 36, in <module>
    nodes.TryExcept, nodes.TryFinally, nodes.While, nodes.For, nodes.If
    ^^^^^^^^^^^^^^^
AttributeError: module 'astroid.nodes' has no attribute 'TryExcept'
```

### Expected behavior

Should display the pylint command options.

### Pylint version

```shell
pylint 2.17.4
astroid 3.0.2
Python 3.12.1 (main, Dec 26 2023, 18:42:33) [GCC 12.2.0]
```

### OS / Environment

Void Linux

**Comment by DanielNoord** [comment]
I don't know how pip allows this, but you shouldn't be using pylint 2.17 with astroid 3. Please upgrade pylint to 3.x as well!
