### ISSUE TITLE
Pylint crash: RecursionError: maximum recursion depth exceeded

### ISSUE THREAD

**Issue by narrieta** [pylint-dev/pylint#9473]
Happens while parsing [this file](https://github.com/Azure/WALinuxAgent/blob/develop/azurelinuxagent/daemon/main.py).

Previously it was parsing fine, but started crashing after this commit: https://github.com/Azure/WALinuxAgent/commit/8ac7e66b2773ba16a33abee41262ad0144c80cd3

pylint command-line options: --rcfile=ci/pylintrc --jobs=0 --disable=no-member

rcfile: https://github.com/Azure/WALinuxAgent/blob/develop/ci/pylintrc

We use pylint with Python 3.5-3.11 and only 3.9 crashes.

crash:

```
2024-02-29T17:30:32.4325652Z Exception on node <Attribute.client l.163 at 0x7f3d51ccce20> in file '/home/runner/work/WALinuxAgent/WALinuxAgent/azurelinuxagent/daemon/main.py'
2024-02-29T17:30:32.4358095Z Traceback (most recent call last):
2024-02-29T17:30:32.4367287Z   File "/opt/hostedtoolcache/Python/3.9.18/x64/lib/python3.9/site-packages/astroid/decorators.py", line 90, in inner
2024-02-29T17:30:32.4368208Z     yield next(generator)
2024-02-29T17:30:32.4369135Z   File "/opt/hostedtoolcache/Python/3.9.18/x64/lib/python3.9/site-packages/astroid/decorators.py", line 44, in wrapped
2024-02-29T17:30:32.4369946Z     if context.push(node):
2024-02-29T17:30:32.4370385Z RecursionError: maximum recursion depth exceeded
2024-02-29T17:30:32.4370704Z 
2024-02-29T17:30:32.4370994Z During handling of the above exception, another exception occurred:
2024-02-29T17:30:32.4371389Z 
2024-02-29T17:30:32.4371523Z Traceback (most recent call last):
2024-02-29T17:30:32.4372501Z   File "/opt/hostedtoolcache/Python/3.9.18/x64/lib/python3.9/site-packages/pylint/utils/ast_walker.py", line 91, in walk
2024-02-29T17:30:32.4373300Z     callback(astroid)
2024-02-29T17:30:32.4374280Z   File "/opt/hostedtoolcache/Python/3.9.18/x64/lib/python3.9/site-packages/pylint/checkers/typecheck.py", line 1089, in visit_attribute
2024-02-29T17:30:32.4375366Z     inferred = list(node.expr.infer())
2024-02-29T17:30:32.4376271Z   File "/opt/hostedtoolcache/Python/3.9.18/x64/lib/python3.9/site-packages/astroid/nodes/node_ng.py", line 170, in infer
2024-02-29T17:30:32.4377208Z     for i, result in enumerate(self._infer(context=context, **kwargs)):
2024-02-29T17:30:32.4378260Z   File "/opt/hostedtoolcache/Python/3.9.18/x64/lib/python3.9/site-packages/astroid/decorators.py", line 103, in inner
2024-02-29T17:30:32.4379032Z     yield from generator
2024-02-29T17:30:32.4379858Z   File "/opt/hostedtoolcache/Python/3.9.18/x64/lib/python3.9/site-packages/astroid/decorators.py", line 49, in wrapped
2024-02-29T17:30:32.4380703Z     for res in _func(node, context, **kwargs):
2024-02-29T17:30:32.4381623Z   File "/opt/hostedtoolcache/Python/3.9.18/x64/lib/python3.9/site-packages/astroid/bases.py", line 177, in _infer_stmts
2024-02-29T17:30:32.4382442Z     for inf in stmt.infer(context=context):
2024-02-29T17:30:32.4383360Z   File "/opt/hostedtoolcache/Python/3.9.18/x64/lib/python3.9/site-packages/astroid/nodes/node_ng.py", line 170, in infer
2024-02-29T17:30:32.4384277Z     for i, result in enumerate(self._infer(context=context, **kwargs)):
2024-02-29T17:30:32.4385307Z   File "/opt/hostedtoolcache/Python/3.9.18/x64/lib/python3.9/site-packages/astroid/decorators.py", line 103, in inner
2024-02-29T17:30:32.4386072Z     yield from generator
2024-02-29T17:30:32.4386873Z   File "/opt/hostedtoolcache/Python/3.9.18/x64/lib/python3.9/site-packages/astroid/decorators.py", line 49, in wrapped
2024-02-29T17:30:32.4387701Z     for res in _func(node, context, **kwargs):
2024-02-29T17:30:32.4388651Z   File "/opt/hostedtoolcache/Python/3.9.18/x64/lib/python3.9/site-packages/astroid/bases.py", line 177, in _infer_stmts
2024-02-29T17:30:32.4389985Z     for inf in stmt.infer(context=context):
2024-02-29T17:30:32.4390994Z   File "/opt/hostedtoolcache/Python/3.9.18/x64/lib/python3.9/site-packages/astroid/nodes/node_ng.py", line 170, in infer
2024-02-29T17:30:32.4391894Z     for i, result in enumerate(self._infer(context=context, **kwargs)):
2024-02-29T17:30:32.4392951Z   File "/opt/hostedtoolcache/Python/3.9.18/x64/lib/python3.9/site-packages/astroid/decorators.py", line 103, in inner
2024-02-29T17:30:32.4393731Z     yield from generator
2024-02-29T17:30:32.4394555Z   File "/opt/hostedtoolcache/Python/3.9.18/x64/lib/python3.9/site-packages/astroid/decorators.py", line 49, in wrapped
2024-02-29T17:30:32.4395362Z     for res in _func(node, context, **kwargs):
2024-02-29T17:30:32.4396342Z   File "/opt/hostedtoolcache/Python/3.9.18/x64/lib/python3.9/site-packages/astroid/nodes/node_classes.py", line 1764, in _infer
2024-02-29T17:30:32.4397174Z     yield from callee.infer_call_result(
2024-02-29T17:30:32.4398123Z   File "/opt/hostedtoolcache/Python/3.9.18/x64/lib/python3.9/site-packages/astroid/bases.py", line 329, in infer_call_result
2024-02-29T17:30:32.4398955Z     for res in node.infer_call_result(caller, context):
2024-02-29T17:30:32.4400064Z   File "/opt/hostedtoolcache/Python/3.9.18/x64/lib/python3.9/site-packages/astroid/bases.py", line 329, in infer_call_result
2024-02-29T17:30:32.4400983Z     for res in node.infer_call_result(caller, context):
2024-02-29T17:30:32.4401965Z   File "/opt/hostedtoolcache/Python/3.9.18/x64/lib/python3.9/site-packages/astroid/bases.py", line 329, in infer_call_result
2024-02-29T17:30:32.4402959Z     for res in node.infer_call_result(caller, context):
2024-02-29T17:30:32.4403490Z   [Previous line repeated 950 more times]
2024-02-29T17:30:32.4404429Z   File "/opt/hostedtoolcache/Python/3.9.18/x64/lib/python3.9/site-packages/astroid/bases.py", line 326, in infer_call_result
2024-02-29T17:30:32.4405334Z     for node in self._proxied.igetattr("__call__", context):
2024-02-29T17:30:32.4406416Z   File "/opt/hostedtoolcache/Python/3.9.18/x64/lib/python3.9/site-packages/astroid/nodes/scoped_nodes/scoped_nodes.py", line 2524, in igetattr
2024-02-29T17:30:32.4407353Z     inferred._proxied.getattr("__get__", context)
2024-02-29T17:30:32.4408551Z   File "/opt/hostedtoolcache/Python/3.9.18/x64/lib/python3.9/site-packages/astroid/nodes/scoped_nodes/scoped_nodes.py", line 2428, in getattr
2024-02-29T17:30:32.4409531Z     values += self._metaclass_lookup_attribute(name, context)
2024-02-29T17:30:32.4410740Z   File "/opt/hostedtoolcache/Python/3.9.18/x64/lib/python3.9/site-packages/astroid/nodes/scoped_nodes/scoped_nodes.py", line 2452, in _metaclass_lookup_attribute
2024-02-29T17:30:32.4411716Z     attrs.update(set(cls_attributes))
2024-02-29T17:30:32.4412844Z   File "/opt/hostedtoolcache/Python/3.9.18/x64/lib/python3.9/site-packages/astroid/nodes/scoped_nodes/scoped_nodes.py", line 2459, in _get_attribute_from_metaclass
2024-02-29T17:30:32.4413916Z     attrs = cls.getattr(name, context=context, class_context=True)
2024-02-29T17:30:32.4415046Z   File "/opt/hostedtoolcache/Python/3.9.18/x64/lib/python3.9/site-packages/astroid/nodes/scoped_nodes/scoped_nodes.py", line 2428, in getattr
2024-02-29T17:30:32.4415987Z     values += self._metaclass_lookup_attribute(name, context)
2024-02-29T17:30:32.4417202Z   File "/opt/hostedtoolcache/Python/3.9.18/x64/lib/python3.9/site-packages/astroid/nodes/scoped_nodes/scoped_nodes.py", line 2448, in _metaclass_lookup_attribute
2024-02-29T17:30:32.4418222Z     metaclass = self.metaclass(context=context)
2024-02-29T17:30:32.4419302Z   File "/opt/hostedtoolcache/Python/3.9.18/x64/lib/python3.9/site-packages/astroid/nodes/scoped_nodes/scoped_nodes.py", line 2740, in metaclass
2024-02-29T17:30:32.4420248Z     return self._find_metaclass(context=context)
2024-02-29T17:30:32.4421344Z   File "/opt/hostedtoolcache/Python/3.9.18/x64/lib/python3.9/site-packages/astroid/nodes/scoped_nodes/scoped_nodes.py", line 2720, in _find_metaclass
2024-02-29T17:30:32.4422337Z     klass = self.declared_metaclass(context=context)
2024-02-29T17:30:32.4423462Z   File "/opt/hostedtoolcache/Python/3.9.18/x64/lib/python3.9/site-packages/astroid/nodes/scoped_nodes/scoped_nodes.py", line 2692, in declared_metaclass
2024-02-29T17:30:32.4424472Z     for baseobj in base.infer(context=context):
2024-02-29T17:30:32.4425376Z   File "/opt/hostedtoolcache/Python/3.9.18/x64/lib/python3.9/site-packages/astroid/nodes/node_ng.py", line 170, in infer
2024-02-29T17:30:32.4426283Z     for i, result in enumerate(self._infer(context=context, **kwargs)):
2024-02-29T17:30:32.4427302Z   File "/opt/hostedtoolcache/Python/3.9.18/x64/lib/python3.9/site-packages/astroid/decorators.py", line 99, in inner
2024-02-29T17:30:32.4428073Z     raise InferenceError(
2024-02-29T17:30:32.4428934Z   File "/opt/hostedtoolcache/Python/3.9.18/x64/lib/python3.9/site-packages/astroid/exceptions.py", line 272, in __init__
2024-02-29T17:30:32.4429696Z     super().__init__(message, **kws)
2024-02-29T17:30:32.4430269Z RecursionError: maximum recursion depth exceeded while calling a Python object

```

**Comment by narrieta** [comment]
There was additional output from pylint:

```
024-02-29T17:30:32.4515621Z ### Command used
2024-02-29T17:30:32.4515807Z 
2024-02-29T17:30:32.4515919Z ```shell
2024-02-29T17:30:32.4516192Z pylint a.py
2024-02-29T17:30:32.4516430Z ```
2024-02-29T17:30:32.4516575Z 
2024-02-29T17:30:32.4516696Z ### Pylint output
2024-02-29T17:30:32.4516870Z 
2024-02-29T17:30:32.4516992Z <details open>
2024-02-29T17:30:32.4517243Z     <summary>
2024-02-29T17:30:32.4517724Z         pylint crashed with a ``AstroidError`` and with the following stacktrace:
2024-02-29T17:30:32.4518272Z     </summary>
2024-02-29T17:30:32.4518423Z 
2024-02-29T17:30:32.4518524Z ```python
2024-02-29T17:30:32.4518830Z Traceback (most recent call last):
2024-02-29T17:30:32.4519738Z   File "/opt/hostedtoolcache/Python/3.9.18/x64/lib/python3.9/site-packages/astroid/decorators.py", line 90, in inner
2024-02-29T17:30:32.4520486Z     yield next(generator)
2024-02-29T17:30:32.4521352Z   File "/opt/hostedtoolcache/Python/3.9.18/x64/lib/python3.9/site-packages/astroid/decorators.py", line 44, in wrapped
2024-02-29T17:30:32.4522136Z     if context.push(node):
2024-02-29T17:30:32.4522533Z RecursionError: maximum recursion depth exceeded
2024-02-29T17:30:32.4522941Z 
2024-02-29T17:30:32.4523222Z During handling of the above exception, another exception occurred:
2024-02-29T17:30:32.4523640Z 
2024-02-29T17:30:32.4523767Z Traceback (most recent call last):
2024-02-29T17:30:32.4524692Z   File "/opt/hostedtoolcache/Python/3.9.18/x64/lib/python3.9/site-packages/pylint/lint/pylinter.py", line 787, in _lint_file
2024-02-29T17:30:32.4525521Z     check_astroid_module(module)
2024-02-29T17:30:32.4526471Z   File "/opt/hostedtoolcache/Python/3.9.18/x64/lib/python3.9/site-packages/pylint/lint/pylinter.py", line 1016, in check_astroid_module
2024-02-29T17:30:32.4527358Z     retval = self._check_astroid_module(
2024-02-29T17:30:32.4528374Z   File "/opt/hostedtoolcache/Python/3.9.18/x64/lib/python3.9/site-packages/pylint/lint/pylinter.py", line 1068, in _check_astroid_module
2024-02-29T17:30:32.4529241Z     walker.walk(node)
2024-02-29T17:30:32.4530082Z   File "/opt/hostedtoolcache/Python/3.9.18/x64/lib/python3.9/site-packages/pylint/utils/ast_walker.py", line 94, in walk
2024-02-29T17:30:32.4530870Z     self.walk(child)
2024-02-29T17:30:32.4531692Z   File "/opt/hostedtoolcache/Python/3.9.18/x64/lib/python3.9/site-packages/pylint/utils/ast_walker.py", line 94, in walk
2024-02-29T17:30:32.4532474Z     self.walk(child)
2024-02-29T17:30:32.4533300Z   File "/opt/hostedtoolcache/Python/3.9.18/x64/lib/python3.9/site-packages/pylint/utils/ast_walker.py", line 94, in walk
2024-02-29T17:30:32.4534059Z     self.walk(child)
2024-02-29T17:30:32.4534493Z   [Previous line repeated 4 more times]
2024-02-29T17:30:32.4535464Z   File "/opt/hostedtoolcache/Python/3.9.18/x64/lib/python3.9/site-packages/pylint/utils/ast_walker.py", line 91, in walk
2024-02-29T17:30:32.4536209Z     callback(astroid)
2024-02-29T17:30:32.4537159Z   File "/opt/hostedtoolcache/Python/3.9.18/x64/lib/python3.9/site-packages/pylint/checkers/typecheck.py", line 1089, in visit_attribute
2024-02-29T17:30:32.4538049Z     inferred = list(node.expr.infer())
2024-02-29T17:30:32.4538937Z   File "/opt/hostedtoolcache/Python/3.9.18/x64/lib/python3.9/site-packages/astroid/nodes/node_ng.py", line 170, in infer
2024-02-29T17:30:32.4539833Z     for i, result in enumerate(self._infer(context=context, **kwargs)):
2024-02-29T17:30:32.4540842Z   File "/opt/hostedtoolcache/Python/3.9.18/x64/lib/python3.9/site-packages/astroid/decorators.py", line 103, in inner
2024-02-29T17:30:32.4541699Z     yield from generator
2024-02-29T17:30:32.4542567Z   File "/opt/hostedtoolcache/Python/3.9.18/x64/lib/python3.9/site-packages/astroid/decorators.py", line 49, in wrapped
2024-02-29T17:30:32.4543373Z     for res in _func(node, context, **kwargs):
2024-02-29T17:30:32.4544257Z   File "/opt/hostedtoolcache/Python/3.9.18/x64/lib/python3.9/site-packages/astroid/bases.py", line 177, in _infer_stmts
2024-02-29T17:30:32.4545080Z     for inf in stmt.infer(context=context):
2024-02-29T17:30:32.4545983Z   File "/opt/hostedtoolcache/Python/3.9.18/x64/lib/python3.9/site-packages/astroid/nodes/node_ng.py", line 170, in infer
2024-02-29T17:30:32.4546889Z     for i, result in enumerate(self._infer(context=context, **kwargs)):
2024-02-29T17:30:32.4547881Z   File "/opt/hostedtoolcache/Python/3.9.18/x64/lib/python3.9/site-packages/astroid/decorators.py", line 103, in inner
2024-02-29T17:30:32.4548638Z     yield from generator
2024-02-29T17:30:32.4549465Z   File "/opt/hostedtoolcache/Python/3.9.18/x64/lib/python3.9/site-packages/astroid/decorators.py", line 49, in wrapped
2024-02-29T17:30:32.4550295Z     for res in _func(node, context, **kwargs):
2024-02-29T17:30:32.4551190Z   File "/opt/hostedtoolcache/Python/3.9.18/x64/lib/python3.9/site-packages/astroid/bases.py", line 177, in _infer_stmts
2024-02-29T17:30:32.4552000Z     for inf in stmt.infer(context=context):
2024-02-29T17:30:32.4552914Z   File "/opt/hostedtoolcache/Python/3.9.18/x64/lib/python3.9/site-packages/astroid/nodes/node_ng.py", line 170, in infer
2024-02-29T17:30:32.4553808Z     for i, result in enumerate(self._infer(context=context, **kwargs)):
2024-02-29T17:30:32.4554782Z   File "/opt/hostedtoolcache/Python/3.9.18/x64/lib/python3.9/site-packages/astroid/decorators.py", line 103, in inner
2024-02-29T17:30:32.4555564Z     yield from generator
2024-02-29T17:30:32.4556394Z   File "/opt/hostedtoolcache/Python/3.9.18/x64/lib/python3.9/site-packages/astroid/decorators.py", line 49, in wrapped
2024-02-29T17:30:32.4557212Z     for res in _func(node, context, **kwargs):
2024-02-29T17:30:32.4558189Z   File "/opt/hostedtoolcache/Python/3.9.18/x64/lib/python3.9/site-packages/astroid/nodes/node_classes.py", line 1764, in _infer
2024-02-29T17:30:32.4559007Z     yield from callee.infer_call_result(
2024-02-29T17:30:32.4559943Z   File "/opt/hostedtoolcache/Python/3.9.18/x64/lib/python3.9/site-packages/astroid/bases.py", line 329, in infer_call_result
2024-02-29T17:30:32.4560811Z     for res in node.infer_call_result(caller, context):
2024-02-29T17:30:32.4561795Z   File "/opt/hostedtoolcache/Python/3.9.18/x64/lib/python3.9/site-packages/astroid/bases.py", line 329, in infer_call_result
2024-02-29T17:30:32.4562645Z     for res in node.infer_call_result(caller, context):
2024-02-29T17:30:32.4563734Z   File "/opt/hostedtoolcache/Python/3.9.18/x64/lib/python3.9/site-packages/astroid/bases.py", line 329, in infer_call_result
2024-02-29T17:30:32.4564596Z     for res in node.infer_call_result(caller, context):
2024-02-29T17:30:32.4565092Z   [Previous line repeated 950 more times]
2024-02-29T17:30:32.4566102Z   File "/opt/hostedtoolcache/Python/3.9.18/x64/lib/python3.9/site-packages/astroid/bases.py", line 326, in infer_call_result
2024-02-29T17:30:32.4566987Z     for node in self._proxied.igetattr("__call__", context):
2024-02-29T17:30:32.4568109Z   File "/opt/hostedtoolcache/Python/3.9.18/x64/lib/python3.9/site-packages/astroid/nodes/scoped_nodes/scoped_nodes.py", line 2524, in igetattr
2024-02-29T17:30:32.4569042Z     inferred._proxied.getattr("__get__", context)
2024-02-29T17:30:32.4570075Z   File "/opt/hostedtoolcache/Python/3.9.18/x64/lib/python3.9/site-packages/astroid/nodes/scoped_nodes/scoped_nodes.py", line 2428, in getattr
2024-02-29T17:30:32.4571080Z     values += self._metaclass_lookup_attribute(name, context)
2024-02-29T17:30:32.4572278Z   File "/opt/hostedtoolcache/Python/3.9.18/x64/lib/python3.9/site-packages/astroid/nodes/scoped_nodes/scoped_nodes.py", line 2452, in _metaclass_lookup_attribute
2024-02-29T17:30:32.4573273Z     attrs.update(set(cls_attributes))
2024-02-29T17:30:32.4574549Z   File "/opt/hostedtoolcache/Python/3.9.18/x64/lib/python3.9/site-packages/astroid/nodes/scoped_nodes/scoped_nodes.py", line 2459, in _get_attribute_from_metaclass
2024-02-29T17:30:32.4575631Z     attrs = cls.getattr(name, context=context, class_context=True)
2024-02-29T17:30:32.4576756Z   File "/opt/hostedtoolcache/Python/3.9.18/x64/lib/python3.9/site-packages/astroid/nodes/scoped_nodes/scoped_nodes.py", line 2428, in getattr
2024-02-29T17:30:32.4577743Z     values += self._metaclass_lookup_attribute(name, context)
2024-02-29T17:30:32.4578932Z   File "/opt/hostedtoolcache/Python/3.9.18/x64/lib/python3.9/site-packages/astroid/nodes/scoped_nodes/scoped_nodes.py", line 2448, in _metaclass_lookup_attribute
2024-02-29T17:30:32.4579924Z     metaclass = self.metaclass(context=context)
2024-02-29T17:30:32.4581006Z   File "/opt/hostedtoolcache/Python/3.9.18/x64/lib/python3.9/site-packages/astroid/nodes/scoped_nodes/scoped_nodes.py", line 2740, in metaclass
2024-02-29T17:30:32.4581943Z     return self._find_metaclass(context=context)
2024-02-29T17:30:32.4583055Z   File "/opt/hostedtoolcache/Python/3.9.18/x64/lib/python3.9/site-packages/astroid/nodes/scoped_nodes/scoped_nodes.py", line 2720, in _find_metaclass
2024-02-29T17:30:32.4584052Z     klass = self.declared_metaclass(context=context)
2024-02-29T17:30:32.4585169Z   File "/opt/hostedtoolcache/Python/3.9.18/x64/lib/python3.9/site-packages/astroid/nodes/scoped_nodes/scoped_nodes.py", line 2692, in declared_metaclass
2024-02-29T17:30:32.4586169Z     for baseobj in base.infer(context=context):
2024-02-29T17:30:32.4587095Z   File "/opt/hostedtoolcache/Python/3.9.18/x64/lib/python3.9/site-packages/astroid/nodes/node_ng.py", line 170, in infer
2024-02-29T17:30:32.4588008Z     for i, result in enumerate(self._infer(context=context, **kwargs)):
2024-02-29T17:30:32.4588991Z   File "/opt/hostedtoolcache/Python/3.9.18/x64/lib/python3.9/site-packages/astroid/decorators.py", line 99, in inner
2024-02-29T17:30:32.4589767Z     raise InferenceError(
2024-02-29T17:30:32.4590618Z   File "/opt/hostedtoolcache/Python/3.9.18/x64/lib/python3.9/site-packages/astroid/exceptions.py", line 272, in __init__
2024-02-29T17:30:32.4591420Z     super().__init__(message, **kws)
2024-02-29T17:30:32.4591969Z RecursionError: maximum recursion depth exceeded while calling a Python object
2024-02-29T17:30:32.4592445Z 
2024-02-29T17:30:32.4592702Z The above exception was the direct cause of the following exception:
2024-02-29T17:30:32.4593137Z 
2024-02-29T17:30:32.4593272Z Traceback (most recent call last):
2024-02-29T17:30:32.4594197Z   File "/opt/hostedtoolcache/Python/3.9.18/x64/lib/python3.9/site-packages/pylint/lint/pylinter.py", line 751, in _lint_files
2024-02-29T17:30:32.4595059Z     self._lint_file(fileitem, module, check_astroid_module)
2024-02-29T17:30:32.4596063Z   File "/opt/hostedtoolcache/Python/3.9.18/x64/lib/python3.9/site-packages/pylint/lint/pylinter.py", line 789, in _lint_file
2024-02-29T17:30:32.4596897Z     raise astroid.AstroidError from e
2024-02-29T17:30:32.4597314Z astroid.exceptions.AstroidError
2024-02-29T17:30:32.4597575Z 
2024-02-29T17:30:32.4597668Z ```
2024-02-29T17:30:32.4597903Z 
2024-02-29T17:30:32.4597909Z 
2024-02-29T17:30:32.4598012Z </details>
2024-02-29T17:30:32.4598157Z 
2024-02-29T17:30:32.4598288Z ### Expected behavior
2024-02-29T17:30:32.4598491Z 
2024-02-29T17:30:32.4598597Z No crash.
2024-02-29T17:30:32.4598762Z 
2024-02-29T17:30:32.4598866Z ### Pylint version
2024-02-29T17:30:32.4599059Z 
2024-02-29T17:30:32.4599154Z ```shell
2024-02-29T17:30:32.4599437Z pylint 3.1.0
2024-02-29T17:30:32.4599686Z astroid 3.1.0
2024-02-29T17:30:32.4600003Z Python 3.9.18 (main, Aug 28 2023, 08:40:21) 
2024-02-29T17:30:32.4600423Z [GCC 9.4.0]
2024-02-29T17:30:32.4600658Z ```
2024-02-29T17:30:32.4600806Z 
2024-02-29T17:30:32.4600915Z ### OS / Environment
2024-02-29T17:30:32.4601118Z 
2024-02-29T17:30:32.4601238Z linux (Linux)
2024-02-29T17:30:32.4601393Z 
2024-02-29T17:30:32.4601514Z ### Additional dependencies
2024-02-29T17:30:32.4601747Z 
2024-02-29T17:30:32.4601941Z <!--
2024-02-29T17:30:32.4602347Z Please remove this part if you're not using any of
2024-02-29T17:30:32.4602895Z your dependencies in the example.
2024-02-29T17:30:32.4603291Z  -->
2024-02-29T17:30:32.4603555Z .
2024-02-29T17:31:58.2892751Z ************* Module azurelinuxagent.daemon.main
2024-02-29T17:31:58.2896344Z azurelinuxagent/daemon/main.py:1:0: F0002: azurelinuxagent/daemon/main.py: Fatal error while checking 'azurelinuxagent/daemon/main.py'. Please open an issue in our bug tracker so we address this. There is a pre-filled template that you can use in '/home/runner/.cache/pylint/pylint-crash-2024-02-29-17-30-32.txt'. (astroid-error)
2024-02-29T17:31:58.2900097Z 
2024-02-29T17:31:58.2900817Z -----------------------------------
2024-02-29T17:31:58.2901854Z Your code has been rated at 0.00/10

```

**Comment by jacobtylerwalls** [comment]
Thanks for reporting the crash. Will handle in #9139
