### ISSUE TITLE
Streamlit page with ChatBot Langchain and Bedrock

### ISSUE THREAD

**Issue by gmarchand** [pylint-dev/pylint#9516]
### Bug description

```python
pylint crashed with a ``AstroidError`` and with the following stacktrace:

Traceback (most recent call last):
  File "/Users/gmarchan/.cache/pre-commit/repo4jgq8qa1/py_env-python3/lib/python3.12/site-packages/pylint/checkers/imports.py", line 765, in _get_imported_module
    return importnode.do_import_module(modname)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/gmarchan/.cache/pre-commit/repo4jgq8qa1/py_env-python3/lib/python3.12/site-packages/astroid/mixins.py", line 102, in do_import_module
    return mymodule.import_module(
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/gmarchan/.cache/pre-commit/repo4jgq8qa1/py_env-python3/lib/python3.12/site-packages/astroid/nodes/scoped_nodes/scoped_nodes.py", line 527, in import_module
    return AstroidManager().ast_from_module_name(absmodname)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/gmarchan/.cache/pre-commit/repo4jgq8qa1/py_env-python3/lib/python3.12/site-packages/astroid/manager.py", line 189, in ast_from_module_name
    return self.ast_from_file(found_spec.location, modname, fallback=False)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/gmarchan/.cache/pre-commit/repo4jgq8qa1/py_env-python3/lib/python3.12/site-packages/astroid/manager.py", line 102, in ast_from_file
    return AstroidBuilder(self).file_build(filepath, modname)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/gmarchan/.cache/pre-commit/repo4jgq8qa1/py_env-python3/lib/python3.12/site-packages/astroid/builder.py", line 133, in file_build
    module, builder = self._data_build(data, modname, path)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/gmarchan/.cache/pre-commit/repo4jgq8qa1/py_env-python3/lib/python3.12/site-packages/astroid/builder.py", line 191, in _data_build
    module = builder.visit_module(node, modname, node_file, package)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/gmarchan/.cache/pre-commit/repo4jgq8qa1/py_env-python3/lib/python3.12/site-packages/astroid/rebuilder.py", line 279, in visit_module
    [self.visit(child, newnode) for child in node.body],
     ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/gmarchan/.cache/pre-commit/repo4jgq8qa1/py_env-python3/lib/python3.12/site-packages/astroid/rebuilder.py", line 622, in visit
    visit_method = getattr(self, visit_name)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'TreeRebuilder' object has no attribute 'visit_typealias'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/gmarchan/.cache/pre-commit/repo4jgq8qa1/py_env-python3/lib/python3.12/site-packages/pylint/lint/pylinter.py", line 713, in _check_file
    check_astroid_module(ast_node)
  File "/Users/gmarchan/.cache/pre-commit/repo4jgq8qa1/py_env-python3/lib/python3.12/site-packages/pylint/lint/pylinter.py", line 912, in check_astroid_module
    retval = self._check_astroid_module(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/gmarchan/.cache/pre-commit/repo4jgq8qa1/py_env-python3/lib/python3.12/site-packages/pylint/lint/pylinter.py", line 962, in _check_astroid_module
    walker.walk(node)
  File "/Users/gmarchan/.cache/pre-commit/repo4jgq8qa1/py_env-python3/lib/python3.12/site-packages/pylint/utils/ast_walker.py", line 93, in walk
    self.walk(child)
  File "/Users/gmarchan/.cache/pre-commit/repo4jgq8qa1/py_env-python3/lib/python3.12/site-packages/pylint/utils/ast_walker.py", line 90, in walk
    callback(astroid)
  File "/Users/gmarchan/.cache/pre-commit/repo4jgq8qa1/py_env-python3/lib/python3.12/site-packages/pylint/checkers/imports.py", line 487, in visit_importfrom
    imported_module = self._get_imported_module(node, basename)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/gmarchan/.cache/pre-commit/repo4jgq8qa1/py_env-python3/lib/python3.12/site-packages/pylint/checkers/imports.py", line 788, in _get_imported_module
    raise astroid.AstroidError from e
astroid.exceptions.AstroidError

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/gmarchan/.cache/pre-commit/repo4jgq8qa1/py_env-python3/lib/python3.12/site-packages/pylint/lint/pylinter.py", line 670, in _check_files
    self._check_file(get_ast, check_astroid_module, file)
  File "/Users/gmarchan/.cache/pre-commit/repo4jgq8qa1/py_env-python3/lib/python3.12/site-packages/pylint/lint/pylinter.py", line 715, in _check_file
    raise astroid.AstroidError from e
astroid.exceptions.AstroidError
```

### Configuration

```ini
When parsing the following file:

<!--
 If sharing the code is not an option, please state so,
 but providing only the stacktrace would still be helpful.
 -->


import base64
import logging
import random
from io import BytesIO
from typing import List, Union

import boto3
import streamlit as st
from langchain.callbacks.base import BaseCallbackHandler
from langchain.chains import ConversationChain
from langchain.memory import ConversationBufferWindowMemory
from langchain.prompts.chat import ChatPromptTemplate, MessagesPlaceholder
from langchain_community.chat_message_histories import \
    StreamlitChatMessageHistory
from langchain_community.chat_models import BedrockChat
from langchain_core.messages import AIMessage, HumanMessage
from libraries import helper
from PIL import Image

logger = logging.getLogger(__name__)


class StreamHandler(BaseCallbackHandler):
    """Callback handler to stream the generated text to Streamlit."""

    def __init__(self, container: st.container) -> None:
        self.container = container
        self.text = ""

    def on_llm_new_token(self, token: str, **kwargs) -> None:
        """Append the new token to the text and update the Streamlit
        container."""
        self.text += token
        self.container.markdown(self.text)


def init_conversationchain(
    temperature: float,
    top_p: float,
    top_k: int,
    max_tokens: int,
    memory_window: int,
    system_prompt: str,
    model_id: str,
) -> ConversationChain:
    """Initialize the ConversationChain with the given parameters."""
    model_kwargs = {
        "temperature": temperature,
        "top_p": top_p,
        "top_k": top_k,
        "max_tokens": max_tokens,
    }

    if system_prompt != "":
        model_kwargs["system"] = system_prompt

    bedrock_client = boto3.client(
        service_name="bedrock-runtime",
        region_name="us-west-2",
    )

    llm = BedrockChat(
        region_name="us-west-2",
        model_id=model_id,
        model_kwargs=model_kwargs,
        streaming=True,
        client=bedrock_client,
    )
    # llm = BedrockChat(model_id=model_id, model_kwargs=model_kwargs, streaming=True)

    conversation = ConversationChain(
        llm=llm,
        verbose=True,
        memory=ConversationBufferWindowMemory(
            k=memory_window,
            ai_prefix="Assistant",
            chat_memory=StreamlitChatMessageHistory(),
            return_messages=True,
        ),
        prompt=CLAUDE_PROMPT,
    )

    # Store LLM generated responses
    if "messages" not in st.session_state:
        st.session_state.messages = [INIT_MESSAGE]

    return conversation


def generate_response(
    conversation: ConversationChain, input: Union[str, List[dict]]
) -> str:
    """Generate a response from the conversation chain with the given input."""
    return conversation.invoke(
        {"input": input}, {"callbacks": [StreamHandler(st.empty())]}
    )


def new_chat() -> None:
    """Reset the chat session and initialize a new conversation chain."""
    st.session_state["messages"] = [INIT_MESSAGE]
    st.session_state["langchain_messages"] = []
    st.session_state["file_uploader_key"] = random.randint(1, 100)


def display_chat_messages(
    uploaded_files: List[st.runtime.uploaded_file_manager.UploadedFile],
) -> None:
    """Display chat messages and uploaded images in the Streamlit app."""
    for message in st.session_state.messages:
        with st.chat_message(message["role"]):
            if uploaded_files:
                if "images" in message and message["images"]:
                    num_cols = 10
                    cols = st.columns(num_cols)
                    i = 0

                    for image_id in message["images"]:
                        for uploaded_file in uploaded_files:
                            if image_id == uploaded_file.file_id:
                                img = Image.open(uploaded_file)

                                with cols[i]:
                                    st.image(img, caption="", width=75)
                                    i += 1

                                if i >= num_cols:
                                    i = 0

            if message["role"] == "user":
                if isinstance(message["content"], str):
                    st.markdown(message["content"])
                elif isinstance(message["content"], dict):
                    st.markdown(message["content"]["input"][0]["content"][0]["text"])
                else:
                    st.markdown(message["content"][0]["text"])

            if message["role"] == "assistant":
                if isinstance(message["content"], str):
                    st.markdown(message["content"])
                elif "response" in message["content"]:
                    st.markdown(message["content"]["response"])


def langchain_messages_format(
    messages: List[Union[AIMessage, HumanMessage]]
) -> List[Union[AIMessage, HumanMessage]]:
    """Format the messages for the LangChain conversation chain."""
    for i, message in enumerate(messages):
        if isinstance(message.content, list):
            if "role" in message.content[0]:
                if message.type == "ai":
                    message = AIMessage(message.content[0]["content"])
                if message.type == "human":
                    message = HumanMessage(message.content[0]["content"])
                messages[i] = message
    return messages


if not helper.check_password():
    st.stop()  # Do not continue if check_password is not True.

CLAUDE_PROMPT = ChatPromptTemplate.from_messages(
    [
        MessagesPlaceholder(variable_name="history"),
        MessagesPlaceholder(variable_name="input"),
    ]
)

INIT_MESSAGE = {
    "role": "assistant",
    "content": "Yo! I am your Solutions Architect AWS. How may I help you?",
}


st.set_page_config(
    page_title="Chatbot with vision",
    page_icon="👀",
    initial_sidebar_state="auto",
    layout="wide",
    menu_items=None,
)
st.title("Chatbot with vision 👀")
st.caption(
    "The chatbot can process a wide range of visual formats, including photos, charts, graphs and technical diagrams."
)
st.button("New Chat", on_click=new_chat, type="primary")

# Generate a unique widget key only once
if "widget_key" not in st.session_state:
    st.session_state["widget_key"] = str(random.randint(1, 1000000))

temperature = 1.0
top_p = 1.00
top_k = 500
max_tokens = 4096
memory_window = 10
system_prompt = "You are a Solutions Architect working at AWS"
model_id = "anthropic.claude-3-sonnet-20240229-v1:0"
conv_chain = init_conversationchain(
    temperature, top_p, top_k, max_tokens, memory_window, system_prompt, model_id
)

# Image uploader
if "file_uploader_key" not in st.session_state:
    st.session_state["file_uploader_key"] = 0

uploaded_files = st.file_uploader(
    "Choose an image",
    type=["jpg", "jpeg", "png"],
    accept_multiple_files=True,
    key=st.session_state["file_uploader_key"],
)

# Display chat messages
display_chat_messages(uploaded_files)

# User-provided prompt
prompt = st.chat_input()

# Get images from previous messages
message_images_list = [
    image_id
    for message in st.session_state.messages
    if message["role"] == "user" and "images" in message and message["images"]
    for image_id in message["images"]
]

# Show image in corresponding chat box
uploaded_file_ids = []
if uploaded_files and len(message_images_list) < len(uploaded_files):
    with st.chat_message("user"):
        num_cols = 10
        cols = st.columns(num_cols)
        i = 0
        content_images = []

        for uploaded_file in uploaded_files:
            if uploaded_file.file_id not in message_images_list:
                uploaded_file_ids.append(uploaded_file.file_id)
                img = Image.open(uploaded_file)
                with BytesIO() as output_buffer:
                    img.save(output_buffer, format=img.format)
                    content_image = base64.b64encode(output_buffer.getvalue()).decode(
                        "utf8"
                    )
                content_images.append(content_image)
                with cols[i]:
                    st.image(img, caption="", width=150)
                    i += 1
                if i >= num_cols:
                    i = 0

        if prompt:
            prompt_text = {"type": "text", "text": prompt}
            prompt_new = [prompt_text]
            for content_image in content_images:
                prompt_image = {
                    "type": "image",
                    "source": {
                        "type": "base64",
                        "media_type": "image/jpeg",
                        "data": content_image,
                    },
                }
                prompt_new.append(prompt_image)
            st.session_state.messages.append(
                {"role": "user", "content": prompt_new, "images": uploaded_file_ids}
            )
            st.markdown(prompt)

elif prompt:
    prompt_text = {"type": "text", "text": prompt}
    prompt_new = [prompt_text]
    st.session_state.messages.append({"role": "user", "content": prompt_new})
    with st.chat_message("user"):
        st.markdown(prompt)

# Modify langchain_messages format
st.session_state["langchain_messages"] = langchain_messages_format(
    st.session_state["langchain_messages"]
)

# Generate a new response if last message is not from assistant
if st.session_state.messages[-1]["role"] != "assistant":
    with st.chat_message("assistant"):
        response = generate_response(
            conv_chain, [{"role": "user", "content": prompt_new}]
        )
    message = {"role": "assistant", "content": response}
    st.session_state.messages.append(message)
```

### Command used

```shell
https://pre-commit.com/
```

### Pylint output

```python
pylint crashed with a ``AstroidError`` and with the following stacktrace:

Traceback (most recent call last):
  File "/Users/gmarchan/.cache/pre-commit/repo4jgq8qa1/py_env-python3/lib/python3.12/site-packages/pylint/checkers/imports.py", line 765, in _get_imported_module
    return importnode.do_import_module(modname)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/gmarchan/.cache/pre-commit/repo4jgq8qa1/py_env-python3/lib/python3.12/site-packages/astroid/mixins.py", line 102, in do_import_module
    return mymodule.import_module(
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/gmarchan/.cache/pre-commit/repo4jgq8qa1/py_env-python3/lib/python3.12/site-packages/astroid/nodes/scoped_nodes/scoped_nodes.py", line 527, in import_module
    return AstroidManager().ast_from_module_name(absmodname)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/gmarchan/.cache/pre-commit/repo4jgq8qa1/py_env-python3/lib/python3.12/site-packages/astroid/manager.py", line 189, in ast_from_module_name
    return self.ast_from_file(found_spec.location, modname, fallback=False)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/gmarchan/.cache/pre-commit/repo4jgq8qa1/py_env-python3/lib/python3.12/site-packages/astroid/manager.py", line 102, in ast_from_file
    return AstroidBuilder(self).file_build(filepath, modname)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/gmarchan/.cache/pre-commit/repo4jgq8qa1/py_env-python3/lib/python3.12/site-packages/astroid/builder.py", line 133, in file_build
    module, builder = self._data_build(data, modname, path)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/gmarchan/.cache/pre-commit/repo4jgq8qa1/py_env-python3/lib/python3.12/site-packages/astroid/builder.py", line 191, in _data_build
    module = builder.visit_module(node, modname, node_file, package)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/gmarchan/.cache/pre-commit/repo4jgq8qa1/py_env-python3/lib/python3.12/site-packages/astroid/rebuilder.py", line 279, in visit_module
    [self.visit(child, newnode) for child in node.body],
     ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/gmarchan/.cache/pre-commit/repo4jgq8qa1/py_env-python3/lib/python3.12/site-packages/astroid/rebuilder.py", line 622, in visit
    visit_method = getattr(self, visit_name)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'TreeRebuilder' object has no attribute 'visit_typealias'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/gmarchan/.cache/pre-commit/repo4jgq8qa1/py_env-python3/lib/python3.12/site-packages/pylint/lint/pylinter.py", line 713, in _check_file
    check_astroid_module(ast_node)
  File "/Users/gmarchan/.cache/pre-commit/repo4jgq8qa1/py_env-python3/lib/python3.12/site-packages/pylint/lint/pylinter.py", line 912, in check_astroid_module
    retval = self._check_astroid_module(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/gmarchan/.cache/pre-commit/repo4jgq8qa1/py_env-python3/lib/python3.12/site-packages/pylint/lint/pylinter.py", line 962, in _check_astroid_module
    walker.walk(node)
  File "/Users/gmarchan/.cache/pre-commit/repo4jgq8qa1/py_env-python3/lib/python3.12/site-packages/pylint/utils/ast_walker.py", line 93, in walk
    self.walk(child)
  File "/Users/gmarchan/.cache/pre-commit/repo4jgq8qa1/py_env-python3/lib/python3.12/site-packages/pylint/utils/ast_walker.py", line 90, in walk
    callback(astroid)
  File "/Users/gmarchan/.cache/pre-commit/repo4jgq8qa1/py_env-python3/lib/python3.12/site-packages/pylint/checkers/imports.py", line 487, in visit_importfrom
    imported_module = self._get_imported_module(node, basename)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/gmarchan/.cache/pre-commit/repo4jgq8qa1/py_env-python3/lib/python3.12/site-packages/pylint/checkers/imports.py", line 788, in _get_imported_module
    raise astroid.AstroidError from e
astroid.exceptions.AstroidError

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/gmarchan/.cache/pre-commit/repo4jgq8qa1/py_env-python3/lib/python3.12/site-packages/pylint/lint/pylinter.py", line 670, in _check_files
    self._check_file(get_ast, check_astroid_module, file)
  File "/Users/gmarchan/.cache/pre-commit/repo4jgq8qa1/py_env-python3/lib/python3.12/site-packages/pylint/lint/pylinter.py", line 715, in _check_file
    raise astroid.AstroidError from e
astroid.exceptions.AstroidError
```

### Expected behavior

No error

### Pylint version

```shell
- repo: https://github.com/pre-commit/mirrors-pylint
    rev: "v3.0.0a5"
    hooks:
      - id: pylint
```

### OS / Environment

Macos

**Comment by jacobtylerwalls** [comment]
Python 3.12 is supported on pylint 3.0 final or higher.
