### ISSUE TITLE
pylint crashes on mac

### ISSUE THREAD

**Issue by wouterpm** [pylint-dev/pylint#9586]
### Bug description

```python
can't run prospector. can't run pylint.
```

### Command used

```shell
pylint main.py
```

### Pylint output

```python
pylint crashed with a ``AstroidError`` and with the following stacktrace:

Traceback (most recent call last):
  File "/Users/wge/dev/pmo/src/functions/function-resize/.direnv/python-3.12/lib/python3.12/site-packages/pylint/checkers/utils.py", line 1390, in safe_infer
    value = next(infer_gen)
            ^^^^^^^^^^^^^^^
  File "/Users/wge/dev/pmo/src/functions/function-resize/.direnv/python-3.12/lib/python3.12/site-packages/astroid/nodes/node_ng.py", line 171, in infer
    yield from self._infer(context=context, **kwargs)
  File "/Users/wge/dev/pmo/src/functions/function-resize/.direnv/python-3.12/lib/python3.12/site-packages/astroid/decorators.py", line 143, in raise_if_nothing_inferred
    yield next(generator)
          ^^^^^^^^^^^^^^^
  File "/Users/wge/dev/pmo/src/functions/function-resize/.direnv/python-3.12/lib/python3.12/site-packages/astroid/decorators.py", line 112, in wrapped
    for res in _func(node, context, **kwargs):
  File "/Users/wge/dev/pmo/src/functions/function-resize/.direnv/python-3.12/lib/python3.12/site-packages/astroid/bases.py", line 177, in _infer_stmts
    for inf in stmt.infer(context=context):
  File "/Users/wge/dev/pmo/src/functions/function-resize/.direnv/python-3.12/lib/python3.12/site-packages/astroid/nodes/node_ng.py", line 184, in infer
    for i, result in enumerate(self._infer(context=context, **kwargs)):
  File "/Users/wge/dev/pmo/src/functions/function-resize/.direnv/python-3.12/lib/python3.12/site-packages/astroid/decorators.py", line 143, in raise_if_nothing_inferred
    yield next(generator)
          ^^^^^^^^^^^^^^^
  File "/Users/wge/dev/pmo/src/functions/function-resize/.direnv/python-3.12/lib/python3.12/site-packages/astroid/decorators.py", line 112, in wrapped
    for res in _func(node, context, **kwargs):
  File "/Users/wge/dev/pmo/src/functions/function-resize/.direnv/python-3.12/lib/python3.12/site-packages/astroid/inference.py", line 279, in infer_call
    yield from callee.infer_call_result(caller=self, context=callcontext)
  File "/Users/wge/dev/pmo/src/functions/function-resize/.direnv/python-3.12/lib/python3.12/site-packages/astroid/nodes/scoped_nodes/scoped_nodes.py", line 2290, in infer_call_result
    if self.is_subtype_of("builtins.type", context) and len(caller.args) == 3:
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/wge/dev/pmo/src/functions/function-resize/.direnv/python-3.12/lib/python3.12/site-packages/astroid/nodes/scoped_nodes/scoped_nodes.py", line 2238, in is_subtype_of
    return any(anc.qname() == type_name for anc in self.ancestors(context=context))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/wge/dev/pmo/src/functions/function-resize/.direnv/python-3.12/lib/python3.12/site-packages/astroid/nodes/scoped_nodes/scoped_nodes.py", line 2238, in <genexpr>
    return any(anc.qname() == type_name for anc in self.ancestors(context=context))
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/wge/dev/pmo/src/functions/function-resize/.direnv/python-3.12/lib/python3.12/site-packages/astroid/nodes/scoped_nodes/scoped_nodes.py", line 2399, in ancestors
    for baseobj in stmt.infer(context):
  File "/Users/wge/dev/pmo/src/functions/function-resize/.direnv/python-3.12/lib/python3.12/site-packages/astroid/nodes/node_ng.py", line 184, in infer
    for i, result in enumerate(self._infer(context=context, **kwargs)):
  File "/Users/wge/dev/pmo/src/functions/function-resize/.direnv/python-3.12/lib/python3.12/site-packages/astroid/decorators.py", line 143, in raise_if_nothing_inferred
    yield next(generator)
          ^^^^^^^^^^^^^^^
  File "/Users/wge/dev/pmo/src/functions/function-resize/.direnv/python-3.12/lib/python3.12/site-packages/astroid/decorators.py", line 112, in wrapped
    for res in _func(node, context, **kwargs):
  File "/Users/wge/dev/pmo/src/functions/function-resize/.direnv/python-3.12/lib/python3.12/site-packages/astroid/inference.py", line 435, in infer_subscript
    for index in self.slice.infer(context):
  File "/Users/wge/dev/pmo/src/functions/function-resize/.direnv/python-3.12/lib/python3.12/site-packages/astroid/nodes/node_ng.py", line 184, in infer
    for i, result in enumerate(self._infer(context=context, **kwargs)):
  File "/Users/wge/dev/pmo/src/functions/function-resize/.direnv/python-3.12/lib/python3.12/site-packages/astroid/decorators.py", line 143, in raise_if_nothing_inferred
    yield next(generator)
          ^^^^^^^^^^^^^^^
  File "/Users/wge/dev/pmo/src/functions/function-resize/.direnv/python-3.12/lib/python3.12/site-packages/astroid/decorators.py", line 112, in wrapped
    for res in _func(node, context, **kwargs):
  File "/Users/wge/dev/pmo/src/functions/function-resize/.direnv/python-3.12/lib/python3.12/site-packages/astroid/bases.py", line 177, in _infer_stmts
    for inf in stmt.infer(context=context):
  File "/Users/wge/dev/pmo/src/functions/function-resize/.direnv/python-3.12/lib/python3.12/site-packages/astroid/nodes/node_ng.py", line 184, in infer
    for i, result in enumerate(self._infer(context=context, **kwargs)):
  File "/Users/wge/dev/pmo/src/functions/function-resize/.direnv/python-3.12/lib/python3.12/site-packages/astroid/decorators.py", line 143, in raise_if_nothing_inferred
    yield next(generator)
          ^^^^^^^^^^^^^^^
  File "/Users/wge/dev/pmo/src/functions/function-resize/.direnv/python-3.12/lib/python3.12/site-packages/astroid/decorators.py", line 112, in wrapped
    for res in _func(node, context, **kwargs):
  File "/Users/wge/dev/pmo/src/functions/function-resize/.direnv/python-3.12/lib/python3.12/site-packages/astroid/bases.py", line 177, in _infer_stmts
    for inf in stmt.infer(context=context):
  File "/Users/wge/dev/pmo/src/functions/function-resize/.direnv/python-3.12/lib/python3.12/site-packages/astroid/nodes/node_ng.py", line 184, in infer
    for i, result in enumerate(self._infer(context=context, **kwargs)):
  File "/Users/wge/dev/pmo/src/functions/function-resize/.direnv/python-3.12/lib/python3.12/site-packages/astroid/decorators.py", line 143, in raise_if_nothing_inferred
    yield next(generator)
          ^^^^^^^^^^^^^^^
  File "/Users/wge/dev/pmo/src/functions/function-resize/.direnv/python-3.12/lib/python3.12/site-packages/astroid/decorators.py", line 112, in wrapped
    for res in _func(node, context, **kwargs):
  File "/Users/wge/dev/pmo/src/functions/function-resize/.direnv/python-3.12/lib/python3.12/site-packages/astroid/bases.py", line 177, in _infer_stmts
    for inf in stmt.infer(context=context):
  File "/Users/wge/dev/pmo/src/functions/function-resize/.direnv/python-3.12/lib/python3.12/site-packages/astroid/nodes/node_ng.py", line 184, in infer
    for i, result in enumerate(self._infer(context=context, **kwargs)):
  File "/Users/wge/dev/pmo/src/functions/function-resize/.direnv/python-3.12/lib/python3.12/site-packages/astroid/decorators.py", line 143, in raise_if_nothing_inferred
    yield next(generator)
          ^^^^^^^^^^^^^^^
  File "/Users/wge/dev/pmo/src/functions/function-resize/.direnv/python-3.12/lib/python3.12/site-packages/astroid/decorators.py", line 112, in wrapped
    for res in _func(node, context, **kwargs):
  File "/Users/wge/dev/pmo/src/functions/function-resize/.direnv/python-3.12/lib/python3.12/site-packages/astroid/inference.py", line 270, in infer_call
    for callee in self.func.infer(context):
  File "/Users/wge/dev/pmo/src/functions/function-resize/.direnv/python-3.12/lib/python3.12/site-packages/astroid/nodes/node_ng.py", line 184, in infer
    for i, result in enumerate(self._infer(context=context, **kwargs)):
  File "/Users/wge/dev/pmo/src/functions/function-resize/.direnv/python-3.12/lib/python3.12/site-packages/astroid/decorators.py", line 143, in raise_if_nothing_inferred
    yield next(generator)
          ^^^^^^^^^^^^^^^
  File "/Users/wge/dev/pmo/src/functions/function-resize/.direnv/python-3.12/lib/python3.12/site-packages/astroid/decorators.py", line 112, in wrapped
    for res in _func(node, context, **kwargs):
  File "/Users/wge/dev/pmo/src/functions/function-resize/.direnv/python-3.12/lib/python3.12/site-packages/astroid/inference.py", line 358, in infer_attribute
    for owner in self.expr.infer(context):
  File "/Users/wge/dev/pmo/src/functions/function-resize/.direnv/python-3.12/lib/python3.12/site-packages/astroid/nodes/node_ng.py", line 184, in infer
    for i, result in enumerate(self._infer(context=context, **kwargs)):
  File "/Users/wge/dev/pmo/src/functions/function-resize/.direnv/python-3.12/lib/python3.12/site-packages/astroid/decorators.py", line 143, in raise_if_nothing_inferred
    yield next(generator)
          ^^^^^^^^^^^^^^^
  File "/Users/wge/dev/pmo/src/functions/function-resize/.direnv/python-3.12/lib/python3.12/site-packages/astroid/decorators.py", line 112, in wrapped
    for res in _func(node, context, **kwargs):
  File "/Users/wge/dev/pmo/src/functions/function-resize/.direnv/python-3.12/lib/python3.12/site-packages/astroid/bases.py", line 177, in _infer_stmts
    for inf in stmt.infer(context=context):
  File "/Users/wge/dev/pmo/src/functions/function-resize/.direnv/python-3.12/lib/python3.12/site-packages/astroid/nodes/node_ng.py", line 184, in infer
    for i, result in enumerate(self._infer(context=context, **kwargs)):
  File "/Users/wge/dev/pmo/src/functions/function-resize/.direnv/python-3.12/lib/python3.12/site-packages/astroid/decorators.py", line 143, in raise_if_nothing_inferred
    yield next(generator)
          ^^^^^^^^^^^^^^^
  File "/Users/wge/dev/pmo/src/functions/function-resize/.direnv/python-3.12/lib/python3.12/site-packages/astroid/decorators.py", line 112, in wrapped
    for res in _func(node, context, **kwargs):
  File "/Users/wge/dev/pmo/src/functions/function-resize/.direnv/python-3.12/lib/python3.12/site-packages/astroid/inference.py", line 304, in infer_import
    yield self.do_import_module(self.real_name(name))
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/wge/dev/pmo/src/functions/function-resize/.direnv/python-3.12/lib/python3.12/site-packages/astroid/nodes/_base_nodes.py", line 146, in do_import_module
    return mymodule.import_module(
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/wge/dev/pmo/src/functions/function-resize/.direnv/python-3.12/lib/python3.12/site-packages/astroid/nodes/scoped_nodes/scoped_nodes.py", line 530, in import_module
    return AstroidManager().ast_from_module_name(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/wge/dev/pmo/src/functions/function-resize/.direnv/python-3.12/lib/python3.12/site-packages/astroid/manager.py", line 246, in ast_from_module_name
    return self.ast_from_file(found_spec.location, modname, fallback=False)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/wge/dev/pmo/src/functions/function-resize/.direnv/python-3.12/lib/python3.12/site-packages/astroid/manager.py", line 138, in ast_from_file
    return AstroidBuilder(self).file_build(filepath, modname)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/wge/dev/pmo/src/functions/function-resize/.direnv/python-3.12/lib/python3.12/site-packages/astroid/builder.py", line 144, in file_build
    module, builder = self._data_build(data, modname, path)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/wge/dev/pmo/src/functions/function-resize/.direnv/python-3.12/lib/python3.12/site-packages/astroid/builder.py", line 204, in _data_build
    module = builder.visit_module(node, modname, node_file, package)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/wge/dev/pmo/src/functions/function-resize/.direnv/python-3.12/lib/python3.12/site-packages/astroid/rebuilder.py", line 254, in visit_module
    [self.visit(child, newnode) for child in node.body],
     ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/wge/dev/pmo/src/functions/function-resize/.direnv/python-3.12/lib/python3.12/site-packages/astroid/rebuilder.py", line 609, in visit
    visit_method = getattr(self, visit_name)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'TreeRebuilder' object has no attribute 'visit_typealias'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/wge/dev/pmo/src/functions/function-resize/.direnv/python-3.12/lib/python3.12/site-packages/pylint/lint/pylinter.py", line 811, in _lint_file
    check_astroid_module(module)
  File "/Users/wge/dev/pmo/src/functions/function-resize/.direnv/python-3.12/lib/python3.12/site-packages/pylint/lint/pylinter.py", line 1085, in check_astroid_module
    retval = self._check_astroid_module(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/wge/dev/pmo/src/functions/function-resize/.direnv/python-3.12/lib/python3.12/site-packages/pylint/lint/pylinter.py", line 1135, in _check_astroid_module
    walker.walk(node)
  File "/Users/wge/dev/pmo/src/functions/function-resize/.direnv/python-3.12/lib/python3.12/site-packages/pylint/utils/ast_walker.py", line 94, in walk
    self.walk(child)
  File "/Users/wge/dev/pmo/src/functions/function-resize/.direnv/python-3.12/lib/python3.12/site-packages/pylint/utils/ast_walker.py", line 94, in walk
    self.walk(child)
  File "/Users/wge/dev/pmo/src/functions/function-resize/.direnv/python-3.12/lib/python3.12/site-packages/pylint/utils/ast_walker.py", line 94, in walk
    self.walk(child)
  [Previous line repeated 1 more time]
  File "/Users/wge/dev/pmo/src/functions/function-resize/.direnv/python-3.12/lib/python3.12/site-packages/pylint/utils/ast_walker.py", line 91, in walk
    callback(astroid)
  File "/Users/wge/dev/pmo/src/functions/function-resize/.direnv/python-3.12/lib/python3.12/site-packages/pylint/checkers/base/basic_error_checker.py", line 430, in visit_call
    self._check_inferred_class_is_abstract(inferred, node)
  File "/Users/wge/dev/pmo/src/functions/function-resize/.direnv/python-3.12/lib/python3.12/site-packages/pylint/checkers/base/basic_error_checker.py", line 447, in _check_inferred_class_is_abstract
    abstract_methods = _has_abstract_methods(inferred)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/wge/dev/pmo/src/functions/function-resize/.direnv/python-3.12/lib/python3.12/site-packages/pylint/checkers/base/basic_error_checker.py", line 78, in _has_abstract_methods
    return len(utils.unimplemented_abstract_methods(node)) > 0
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/wge/dev/pmo/src/functions/function-resize/.direnv/python-3.12/lib/python3.12/site-packages/pylint/checkers/utils.py", line 991, in unimplemented_abstract_methods
    inferred = safe_infer(obj)
               ^^^^^^^^^^^^^^^
  File "/Users/wge/dev/pmo/src/functions/function-resize/.direnv/python-3.12/lib/python3.12/site-packages/pylint/checkers/utils.py", line 1394, in safe_infer
    raise AstroidError from e
astroid.exceptions.AstroidError

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/wge/dev/pmo/src/functions/function-resize/.direnv/python-3.12/lib/python3.12/site-packages/pylint/lint/pylinter.py", line 775, in _lint_files
    self._lint_file(fileitem, module, check_astroid_module)
  File "/Users/wge/dev/pmo/src/functions/function-resize/.direnv/python-3.12/lib/python3.12/site-packages/pylint/lint/pylinter.py", line 813, in _lint_file
    raise astroid.AstroidError from e
astroid.exceptions.AstroidError
```
```


### Expected behavior

working linter

### Pylint version

```shell
❯ pylint --version
pylint 2.17.7
astroid 2.15.8
Python 3.12.2 (main, Feb  6 2024, 20:19:44) [Clang 15.0.0 (clang-1500.1.0.2.5)]
```

### OS / Environment

MacOS 14.3 Sanoma

### Additional dependencies

```python
astroid==2.15.8
black==23.11.0
blinker==1.7.0
build==1.2.1
cachetools==5.3.2
certifi==2023.11.17
cfgv==3.4.0
charset-normalizer==3.3.2
click==8.1.7
cloudevents==1.10.1
deprecation==2.1.0
dill==0.3.8
distlib==0.3.8
dodgy==0.2.1
filelock==3.13.4
flake8==5.0.4
flake8-polyfill==1.0.2
Flask==3.0.0
functions-framework==3.5.0
gitdb==4.0.11
GitPython==3.1.43
google-api-core==2.15.0
google-auth==2.25.2
google-cloud-appengine-logging==1.4.0
google-cloud-audit-log==0.2.5
google-cloud-core==2.4.1
google-cloud-logging==3.9.0
google-cloud-storage==2.14.0
google-crc32c==1.5.0
google-resumable-media==2.7.0
googleapis-common-protos==1.62.0
grpc-google-iam-v1==0.13.0
grpcio==1.60.0
grpcio-status==1.60.0
gunicorn==21.2.0
identify==2.5.36
idna==3.6
isort==5.13.2
itsdangerous==2.1.2
Jinja2==3.1.2
lazy-object-proxy==1.10.0
MarkupSafe==2.1.3
mccabe==0.7.0
mypy-extensions==1.0.0
nodeenv==1.8.0
packaging==24.0
pathspec==0.12.1
pep8-naming==0.10.0
Pillow==10.1.0
pip-tools==7.4.1
platformdirs==4.2.1
pre-commit==3.3.3
prospector==1.10.3
proto-plus==1.23.0
protobuf==4.25.1
pyasn1==0.5.1
pyasn1-modules==0.3.0
pycodestyle==2.9.1
pydocstyle==6.3.0
pyflakes==2.5.0
pylint==2.17.7
pylint-celery==0.3
pylint-django==2.5.3
pylint-flask==0.6
pylint-plugin-utils==0.7
pyproject_hooks==1.1.0
PyYAML==6.0.1
requests==2.31.0
requirements-detector==1.2.2
rsa==4.9
semver==3.0.2
setoptconf-tmp==0.3.1
setuptools==69.5.1
smmap==5.0.1
snowballstemmer==2.2.0
toml==0.10.2
tomlkit==0.12.4
urllib3==2.1.0
virtualenv==20.26.0
watchdog==3.0.0
Werkzeug==3.0.1
wheel==0.43.0
wrapt==1.16.0
yamllint==1.35.1
```

**Comment by Pierre-Sassoulas** [comment]
Hello, thank you for opening the issue. You need pylint 3.0.0 or superior to be able to parse python 3.12 code :)

**Comment by wouterpm** [comment]
kind of impossible: 
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
requirements-detector 1.2.2 requires astroid<3.0,>=2.0, but you have astroid 3.0.3 which is incompatible.
pylint-django 2.5.3 requires pylint<3,>=2.0, but you have pylint 3.0.0 which is incompatible.

**Comment by Pierre-Sassoulas** [comment]
You need pylint-django 2.5.4 in order to be compatible with pylint 3.0.0 and python 3.12. I don't know why `requirements-detector` is imposing restriction on pylint but it shouldn't. Is it coming from prospector ?  (prospector is stuck in the past for now, and incompatible with pylint 3.0)

I don't know how to make this sound nice but you should find a process to be able to update your dependencies without requiring expert interaction with the maintainers of the libs (there's metadata in the packaging, if you just used ``pylint-django`` instead of  hard-coding the version then pip + python 3.12 automatically install the proper version).

**Comment by wouterpm** [comment]
I'm running this command: 
conda create -n pylinttest python=3.12 prospector black pre-commit yamllint -c conda-forge 

and when i run prospector on any python file, it throws an astroid error.

i did the same in a a venv, and got the same result.
