### ISSUE TITLE
Crash ``Building error when trying to create ast representation of module 'aws_cp.__init__'``

### ISSUE THREAD

**Issue by okelet** [pylint-dev/pylint#9717]
When parsing the following file:

```python
import logging
import os

from dotenv import load_dotenv
from flask import g, redirect, request, send_file, session, url_for
from flask_babel import Babel
from flask_socketio import SocketIO, emit

try:
    from flask_debugtoolbar import DebugToolbarExtension

    has_debug_toolbar = True
except ImportError:
    has_debug_toolbar = False

from aws_cp.app import AwsCpApp
from aws_cp.cli import init_app as cli_init_app
from aws_cp.emr.app import init_app as emr_init_app
from aws_cp.glue.app import init_app as glue_init_app
from aws_cp.lf.app import init_app as lf_init_app
from aws_cp.profiles import init_app as profiles_init_app
from aws_cp.utils import AwsSessionInfo, init_logging

LOGGER = logging.getLogger(__name__)


def create_app():
    """
    Create the application.
    """
    load_dotenv()

    init_logging(packages=["aws_cp"], level=logging.DEBUG)

    app = AwsCpApp()
    app.config["SECRET_KEY"] = os.environ["FLASK_SECRET_KEY"]
    app.config["DEBUG_TB_INTERCEPT_REDIRECTS"] = False
    app.config["MONGO_URI"] = os.environ["MONGO_URI"]

    # Init SocketIO
    socket_io = SocketIO(app)

    def get_user_locale():
        return request.accept_languages.best_match(["es", "en"])

    def get_user_timezone():
        return "Europe/Madrid"

    babel = Babel()
    babel.init_app(app, locale_selector=get_user_locale, timezone_selector=get_user_timezone)

    toolbar = None
    if app.debug and has_debug_toolbar:
        toolbar = DebugToolbarExtension()
        toolbar.init_app(app)

    @app.before_request
    def before_request_func():
        """
        Execute before each request.
        """
        g.aws_session_info = None
        aws_profile = session.get("aws_profile")
        aws_region = session.get("aws_region")
        aws_account_id = session.get("aws_account_id")
        if aws_region and aws_account_id:
            g.aws_session_info = AwsSessionInfo(aws_profile, aws_region, aws_account_id)

    @app.context_processor
    def template_context():
        """
        Add context variables to the template.
        """
        return {
            "aws_session_info": g.aws_session_info,
            "regions": {
                "us-east-1": "US East (N. Virginia)",
                "eu-west-1": "EU (Ireland)",
                "eu-south-2": "EU (Spain)",
            }
        }

    @app.route("/")
    def home():
        return redirect(url_for("emr_clusters_list_active"))

    @app.route("/favicon.ico")
    def favicon():
        return send_file("static/favicon.ico")

    # Included routes
    cli_init_app(app)
    profiles_init_app(app)
    emr_init_app(app, socket_io)
    glue_init_app(app)
    lf_init_app(app)

    @socket_io.on('test')
    def handle_message(data):
        print('received message: ' + data)
        emit("server", f"You have said: {data}!!!")

    return app

```

pylint crashed with a ``AstroidBuildingError`` and with the following stacktrace:
```
Traceback (most recent call last):
  File "/Users/xxxxxx/Library/Caches/pypoetry/virtualenvs/aws-cp-F65XvQUA-py3.12/lib/python3.12/site-packages/pylint/lint/pylinter.py", line 1044, in get_ast
    return MANAGER.ast_from_file(filepath, modname, source=True)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/xxxxxx/Library/Caches/pypoetry/virtualenvs/aws-cp-F65XvQUA-py3.12/lib/python3.12/site-packages/astroid/manager.py", line 138, in ast_from_file
    return AstroidBuilder(self).file_build(filepath, modname)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/xxxxxx/Library/Caches/pypoetry/virtualenvs/aws-cp-F65XvQUA-py3.12/lib/python3.12/site-packages/astroid/builder.py", line 145, in file_build
    return self._post_build(module, builder, encoding)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/xxxxxx/Library/Caches/pypoetry/virtualenvs/aws-cp-F65XvQUA-py3.12/lib/python3.12/site-packages/astroid/builder.py", line 169, in _post_build
    self.delayed_assattr(delayed)
  File "/Users/xxxxxx/Library/Caches/pypoetry/virtualenvs/aws-cp-F65XvQUA-py3.12/lib/python3.12/site-packages/astroid/builder.py", line 240, in delayed_assattr
    for inferred in node.expr.infer():
  File "/Users/xxxxxx/Library/Caches/pypoetry/virtualenvs/aws-cp-F65XvQUA-py3.12/lib/python3.12/site-packages/astroid/nodes/node_ng.py", line 171, in infer
    yield from self._infer(context=context, **kwargs)
  File "/Users/xxxxxx/Library/Caches/pypoetry/virtualenvs/aws-cp-F65XvQUA-py3.12/lib/python3.12/site-packages/astroid/decorators.py", line 143, in raise_if_nothing_inferred
    yield next(generator)
          ^^^^^^^^^^^^^^^
  File "/Users/xxxxxx/Library/Caches/pypoetry/virtualenvs/aws-cp-F65XvQUA-py3.12/lib/python3.12/site-packages/astroid/decorators.py", line 112, in wrapped
    for res in _func(node, context, **kwargs):
  File "/Users/xxxxxx/Library/Caches/pypoetry/virtualenvs/aws-cp-F65XvQUA-py3.12/lib/python3.12/site-packages/astroid/bases.py", line 177, in _infer_stmts
    for inf in stmt.infer(context=context):
  File "/Users/xxxxxx/Library/Caches/pypoetry/virtualenvs/aws-cp-F65XvQUA-py3.12/lib/python3.12/site-packages/astroid/nodes/node_ng.py", line 184, in infer
    for i, result in enumerate(self._infer(context=context, **kwargs)):
  File "/Users/xxxxxx/Library/Caches/pypoetry/virtualenvs/aws-cp-F65XvQUA-py3.12/lib/python3.12/site-packages/astroid/decorators.py", line 143, in raise_if_nothing_inferred
    yield next(generator)
          ^^^^^^^^^^^^^^^
  File "/Users/xxxxxx/Library/Caches/pypoetry/virtualenvs/aws-cp-F65XvQUA-py3.12/lib/python3.12/site-packages/astroid/decorators.py", line 112, in wrapped
    for res in _func(node, context, **kwargs):
  File "/Users/xxxxxx/Library/Caches/pypoetry/virtualenvs/aws-cp-F65XvQUA-py3.12/lib/python3.12/site-packages/astroid/bases.py", line 177, in _infer_stmts
    for inf in stmt.infer(context=context):
  File "/Users/xxxxxx/Library/Caches/pypoetry/virtualenvs/aws-cp-F65XvQUA-py3.12/lib/python3.12/site-packages/astroid/nodes/node_ng.py", line 184, in infer
    for i, result in enumerate(self._infer(context=context, **kwargs)):
  File "/Users/xxxxxx/Library/Caches/pypoetry/virtualenvs/aws-cp-F65XvQUA-py3.12/lib/python3.12/site-packages/astroid/decorators.py", line 143, in raise_if_nothing_inferred
    yield next(generator)
          ^^^^^^^^^^^^^^^
  File "/Users/xxxxxx/Library/Caches/pypoetry/virtualenvs/aws-cp-F65XvQUA-py3.12/lib/python3.12/site-packages/astroid/decorators.py", line 112, in wrapped
    for res in _func(node, context, **kwargs):
  File "/Users/xxxxxx/Library/Caches/pypoetry/virtualenvs/aws-cp-F65XvQUA-py3.12/lib/python3.12/site-packages/astroid/bases.py", line 177, in _infer_stmts
    for inf in stmt.infer(context=context):
  File "/Users/xxxxxx/Library/Caches/pypoetry/virtualenvs/aws-cp-F65XvQUA-py3.12/lib/python3.12/site-packages/astroid/nodes/node_ng.py", line 184, in infer
    for i, result in enumerate(self._infer(context=context, **kwargs)):
  File "/Users/xxxxxx/Library/Caches/pypoetry/virtualenvs/aws-cp-F65XvQUA-py3.12/lib/python3.12/site-packages/astroid/decorators.py", line 143, in raise_if_nothing_inferred
    yield next(generator)
          ^^^^^^^^^^^^^^^
  File "/Users/xxxxxx/Library/Caches/pypoetry/virtualenvs/aws-cp-F65XvQUA-py3.12/lib/python3.12/site-packages/astroid/decorators.py", line 112, in wrapped
    for res in _func(node, context, **kwargs):
  File "/Users/xxxxxx/Library/Caches/pypoetry/virtualenvs/aws-cp-F65XvQUA-py3.12/lib/python3.12/site-packages/astroid/bases.py", line 177, in _infer_stmts
    for inf in stmt.infer(context=context):
  File "/Users/xxxxxx/Library/Caches/pypoetry/virtualenvs/aws-cp-F65XvQUA-py3.12/lib/python3.12/site-packages/astroid/nodes/node_ng.py", line 184, in infer
    for i, result in enumerate(self._infer(context=context, **kwargs)):
  File "/Users/xxxxxx/Library/Caches/pypoetry/virtualenvs/aws-cp-F65XvQUA-py3.12/lib/python3.12/site-packages/astroid/decorators.py", line 143, in raise_if_nothing_inferred
    yield next(generator)
          ^^^^^^^^^^^^^^^
  File "/Users/xxxxxx/Library/Caches/pypoetry/virtualenvs/aws-cp-F65XvQUA-py3.12/lib/python3.12/site-packages/astroid/decorators.py", line 112, in wrapped
    for res in _func(node, context, **kwargs):
  File "/Users/xxxxxx/Library/Caches/pypoetry/virtualenvs/aws-cp-F65XvQUA-py3.12/lib/python3.12/site-packages/astroid/inference.py", line 270, in infer_call
    for callee in self.func.infer(context):
  File "/Users/xxxxxx/Library/Caches/pypoetry/virtualenvs/aws-cp-F65XvQUA-py3.12/lib/python3.12/site-packages/astroid/nodes/node_ng.py", line 184, in infer
    for i, result in enumerate(self._infer(context=context, **kwargs)):
  File "/Users/xxxxxx/Library/Caches/pypoetry/virtualenvs/aws-cp-F65XvQUA-py3.12/lib/python3.12/site-packages/astroid/decorators.py", line 143, in raise_if_nothing_inferred
    yield next(generator)
          ^^^^^^^^^^^^^^^
  File "/Users/xxxxxx/Library/Caches/pypoetry/virtualenvs/aws-cp-F65XvQUA-py3.12/lib/python3.12/site-packages/astroid/decorators.py", line 112, in wrapped
    for res in _func(node, context, **kwargs):
  File "/Users/xxxxxx/Library/Caches/pypoetry/virtualenvs/aws-cp-F65XvQUA-py3.12/lib/python3.12/site-packages/astroid/bases.py", line 177, in _infer_stmts
    for inf in stmt.infer(context=context):
  File "/Users/xxxxxx/Library/Caches/pypoetry/virtualenvs/aws-cp-F65XvQUA-py3.12/lib/python3.12/site-packages/astroid/nodes/node_ng.py", line 184, in infer
    for i, result in enumerate(self._infer(context=context, **kwargs)):
  File "/Users/xxxxxx/Library/Caches/pypoetry/virtualenvs/aws-cp-F65XvQUA-py3.12/lib/python3.12/site-packages/astroid/decorators.py", line 143, in raise_if_nothing_inferred
    yield next(generator)
          ^^^^^^^^^^^^^^^
  File "/Users/xxxxxx/Library/Caches/pypoetry/virtualenvs/aws-cp-F65XvQUA-py3.12/lib/python3.12/site-packages/astroid/decorators.py", line 112, in wrapped
    for res in _func(node, context, **kwargs):
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/xxxxxx/Library/Caches/pypoetry/virtualenvs/aws-cp-F65XvQUA-py3.12/lib/python3.12/site-packages/astroid/inference.py", line 334, in infer_import_from
    module = self.do_import_module()
             ^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/xxxxxx/Library/Caches/pypoetry/virtualenvs/aws-cp-F65XvQUA-py3.12/lib/python3.12/site-packages/astroid/nodes/_base_nodes.py", line 146, in do_import_module
    return mymodule.import_module(
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/xxxxxx/Library/Caches/pypoetry/virtualenvs/aws-cp-F65XvQUA-py3.12/lib/python3.12/site-packages/astroid/nodes/scoped_nodes/scoped_nodes.py", line 530, in import_module
    return AstroidManager().ast_from_module_name(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/xxxxxx/Library/Caches/pypoetry/virtualenvs/aws-cp-F65XvQUA-py3.12/lib/python3.12/site-packages/astroid/manager.py", line 246, in ast_from_module_name
    return self.ast_from_file(found_spec.location, modname, fallback=False)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/xxxxxx/Library/Caches/pypoetry/virtualenvs/aws-cp-F65XvQUA-py3.12/lib/python3.12/site-packages/astroid/manager.py", line 138, in ast_from_file
    return AstroidBuilder(self).file_build(filepath, modname)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/xxxxxx/Library/Caches/pypoetry/virtualenvs/aws-cp-F65XvQUA-py3.12/lib/python3.12/site-packages/astroid/builder.py", line 145, in file_build
    return self._post_build(module, builder, encoding)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/xxxxxx/Library/Caches/pypoetry/virtualenvs/aws-cp-F65XvQUA-py3.12/lib/python3.12/site-packages/astroid/builder.py", line 169, in _post_build
    self.delayed_assattr(delayed)
  File "/Users/xxxxxx/Library/Caches/pypoetry/virtualenvs/aws-cp-F65XvQUA-py3.12/lib/python3.12/site-packages/astroid/builder.py", line 240, in delayed_assattr
    for inferred in node.expr.infer():
  File "/Users/xxxxxx/Library/Caches/pypoetry/virtualenvs/aws-cp-F65XvQUA-py3.12/lib/python3.12/site-packages/astroid/nodes/node_ng.py", line 171, in infer
    yield from self._infer(context=context, **kwargs)
  File "/Users/xxxxxx/Library/Caches/pypoetry/virtualenvs/aws-cp-F65XvQUA-py3.12/lib/python3.12/site-packages/astroid/decorators.py", line 143, in raise_if_nothing_inferred
    yield next(generator)
          ^^^^^^^^^^^^^^^
  File "/Users/xxxxxx/Library/Caches/pypoetry/virtualenvs/aws-cp-F65XvQUA-py3.12/lib/python3.12/site-packages/astroid/decorators.py", line 112, in wrapped
    for res in _func(node, context, **kwargs):
  File "/Users/xxxxxx/Library/Caches/pypoetry/virtualenvs/aws-cp-F65XvQUA-py3.12/lib/python3.12/site-packages/astroid/bases.py", line 177, in _infer_stmts
    for inf in stmt.infer(context=context):
  File "/Users/xxxxxx/Library/Caches/pypoetry/virtualenvs/aws-cp-F65XvQUA-py3.12/lib/python3.12/site-packages/astroid/nodes/node_ng.py", line 184, in infer
    for i, result in enumerate(self._infer(context=context, **kwargs)):
  File "/Users/xxxxxx/Library/Caches/pypoetry/virtualenvs/aws-cp-F65XvQUA-py3.12/lib/python3.12/site-packages/astroid/decorators.py", line 143, in raise_if_nothing_inferred
    yield next(generator)
          ^^^^^^^^^^^^^^^
  File "/Users/xxxxxx/Library/Caches/pypoetry/virtualenvs/aws-cp-F65XvQUA-py3.12/lib/python3.12/site-packages/astroid/decorators.py", line 112, in wrapped
    for res in _func(node, context, **kwargs):
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/xxxxxx/Library/Caches/pypoetry/virtualenvs/aws-cp-F65XvQUA-py3.12/lib/python3.12/site-packages/astroid/inference.py", line 1162, in infer_assign
    stmts = list(self.assigned_stmts(context=context))
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/xxxxxx/Library/Caches/pypoetry/virtualenvs/aws-cp-F65XvQUA-py3.12/lib/python3.12/site-packages/astroid/protocols.py", line 412, in _arguments_infer_argname
    is_metaclass = isinstance(cls, nodes.ClassDef) and cls.type == "metaclass"
                                                       ^^^^^^^^
  File "/Users/xxxxxx/Library/Caches/pypoetry/virtualenvs/aws-cp-F65XvQUA-py3.12/lib/python3.12/site-packages/astroid/nodes/scoped_nodes/scoped_nodes.py", line 1874, in _class_type
    if _is_metaclass(klass):
       ^^^^^^^^^^^^^^^^^^^^
  File "/Users/xxxxxx/Library/Caches/pypoetry/virtualenvs/aws-cp-F65XvQUA-py3.12/lib/python3.12/site-packages/astroid/nodes/scoped_nodes/scoped_nodes.py", line 1845, in _is_metaclass
    for baseobj in base.infer():
  File "/Users/xxxxxx/Library/Caches/pypoetry/virtualenvs/aws-cp-F65XvQUA-py3.12/lib/python3.12/site-packages/astroid/nodes/node_ng.py", line 171, in infer
    yield from self._infer(context=context, **kwargs)
  File "/Users/xxxxxx/Library/Caches/pypoetry/virtualenvs/aws-cp-F65XvQUA-py3.12/lib/python3.12/site-packages/astroid/decorators.py", line 143, in raise_if_nothing_inferred
    yield next(generator)
          ^^^^^^^^^^^^^^^
  File "/Users/xxxxxx/Library/Caches/pypoetry/virtualenvs/aws-cp-F65XvQUA-py3.12/lib/python3.12/site-packages/astroid/decorators.py", line 112, in wrapped
    for res in _func(node, context, **kwargs):
  File "/Users/xxxxxx/Library/Caches/pypoetry/virtualenvs/aws-cp-F65XvQUA-py3.12/lib/python3.12/site-packages/astroid/inference.py", line 431, in infer_subscript
    for value in self.value.infer(context):
  File "/Users/xxxxxx/Library/Caches/pypoetry/virtualenvs/aws-cp-F65XvQUA-py3.12/lib/python3.12/site-packages/astroid/nodes/node_ng.py", line 184, in infer
    for i, result in enumerate(self._infer(context=context, **kwargs)):
  File "/Users/xxxxxx/Library/Caches/pypoetry/virtualenvs/aws-cp-F65XvQUA-py3.12/lib/python3.12/site-packages/astroid/decorators.py", line 143, in raise_if_nothing_inferred
    yield next(generator)
          ^^^^^^^^^^^^^^^
  File "/Users/xxxxxx/Library/Caches/pypoetry/virtualenvs/aws-cp-F65XvQUA-py3.12/lib/python3.12/site-packages/astroid/decorators.py", line 112, in wrapped
    for res in _func(node, context, **kwargs):
  File "/Users/xxxxxx/Library/Caches/pypoetry/virtualenvs/aws-cp-F65XvQUA-py3.12/lib/python3.12/site-packages/astroid/inference.py", line 358, in infer_attribute
    for owner in self.expr.infer(context):
  File "/Users/xxxxxx/Library/Caches/pypoetry/virtualenvs/aws-cp-F65XvQUA-py3.12/lib/python3.12/site-packages/astroid/nodes/node_ng.py", line 184, in infer
    for i, result in enumerate(self._infer(context=context, **kwargs)):
  File "/Users/xxxxxx/Library/Caches/pypoetry/virtualenvs/aws-cp-F65XvQUA-py3.12/lib/python3.12/site-packages/astroid/decorators.py", line 143, in raise_if_nothing_inferred
    yield next(generator)
          ^^^^^^^^^^^^^^^
  File "/Users/xxxxxx/Library/Caches/pypoetry/virtualenvs/aws-cp-F65XvQUA-py3.12/lib/python3.12/site-packages/astroid/decorators.py", line 112, in wrapped
    for res in _func(node, context, **kwargs):
  File "/Users/xxxxxx/Library/Caches/pypoetry/virtualenvs/aws-cp-F65XvQUA-py3.12/lib/python3.12/site-packages/astroid/bases.py", line 177, in _infer_stmts
    for inf in stmt.infer(context=context):
  File "/Users/xxxxxx/Library/Caches/pypoetry/virtualenvs/aws-cp-F65XvQUA-py3.12/lib/python3.12/site-packages/astroid/nodes/node_ng.py", line 184, in infer
    for i, result in enumerate(self._infer(context=context, **kwargs)):
  File "/Users/xxxxxx/Library/Caches/pypoetry/virtualenvs/aws-cp-F65XvQUA-py3.12/lib/python3.12/site-packages/astroid/decorators.py", line 143, in raise_if_nothing_inferred
    yield next(generator)
          ^^^^^^^^^^^^^^^
  File "/Users/xxxxxx/Library/Caches/pypoetry/virtualenvs/aws-cp-F65XvQUA-py3.12/lib/python3.12/site-packages/astroid/decorators.py", line 112, in wrapped
    for res in _func(node, context, **kwargs):
  File "/Users/xxxxxx/Library/Caches/pypoetry/virtualenvs/aws-cp-F65XvQUA-py3.12/lib/python3.12/site-packages/astroid/inference.py", line 304, in infer_import
    yield self.do_import_module(self.real_name(name))
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/xxxxxx/Library/Caches/pypoetry/virtualenvs/aws-cp-F65XvQUA-py3.12/lib/python3.12/site-packages/astroid/nodes/_base_nodes.py", line 146, in do_import_module
    return mymodule.import_module(
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/xxxxxx/Library/Caches/pypoetry/virtualenvs/aws-cp-F65XvQUA-py3.12/lib/python3.12/site-packages/astroid/nodes/scoped_nodes/scoped_nodes.py", line 530, in import_module
    return AstroidManager().ast_from_module_name(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/xxxxxx/Library/Caches/pypoetry/virtualenvs/aws-cp-F65XvQUA-py3.12/lib/python3.12/site-packages/astroid/manager.py", line 246, in ast_from_module_name
    return self.ast_from_file(found_spec.location, modname, fallback=False)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/xxxxxx/Library/Caches/pypoetry/virtualenvs/aws-cp-F65XvQUA-py3.12/lib/python3.12/site-packages/astroid/manager.py", line 138, in ast_from_file
    return AstroidBuilder(self).file_build(filepath, modname)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/xxxxxx/Library/Caches/pypoetry/virtualenvs/aws-cp-F65XvQUA-py3.12/lib/python3.12/site-packages/astroid/builder.py", line 144, in file_build
    module, builder = self._data_build(data, modname, path)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/xxxxxx/Library/Caches/pypoetry/virtualenvs/aws-cp-F65XvQUA-py3.12/lib/python3.12/site-packages/astroid/builder.py", line 204, in _data_build
    module = builder.visit_module(node, modname, node_file, package)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/xxxxxx/Library/Caches/pypoetry/virtualenvs/aws-cp-F65XvQUA-py3.12/lib/python3.12/site-packages/astroid/rebuilder.py", line 254, in visit_module
    [self.visit(child, newnode) for child in node.body],
     ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/xxxxxx/Library/Caches/pypoetry/virtualenvs/aws-cp-F65XvQUA-py3.12/lib/python3.12/site-packages/astroid/rebuilder.py", line 609, in visit
    visit_method = getattr(self, visit_name)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'TreeRebuilder' object has no attribute 'visit_typealias'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/xxxxxx/Library/Caches/pypoetry/virtualenvs/aws-cp-F65XvQUA-py3.12/lib/python3.12/site-packages/pylint/lint/pylinter.py", line 730, in _get_asts
    ast_per_fileitem[fileitem] = self.get_ast(
                                 ^^^^^^^^^^^^^
  File "/Users/xxxxxx/Library/Caches/pypoetry/virtualenvs/aws-cp-F65XvQUA-py3.12/lib/python3.12/site-packages/pylint/lint/pylinter.py", line 1066, in get_ast
    raise astroid.AstroidBuildingError(
astroid.exceptions.AstroidBuildingError: Building error when trying to create ast representation of module 'aws_cp.__init__'
```

**Comment by jacobtylerwalls** [comment]
Python 3.12 is only supported on pylint 3 or higher.
