### ISSUE TITLE
Crash F0002 when parsing mssql.py

### ISSUE THREAD

**Issue by jlubken** [pylint-dev/pylint#9871]
### Bug description

Crash when parsing the following ``mssql.py``:

```python
"""Mssql."""

from __future__ import annotations

from abc import ABC
from collections.abc import Generator
from contextlib import contextmanager
from json import dumps
from logging import getLogger
from typing import TYPE_CHECKING, Any

from .persistor import Persistor as BasePersistor
from .service import Service
from .utils import StubError

logger = getLogger(__name__)


try:
    from pymssql import DatabaseError, InterfaceError, _mssql, connect
except ImportError as import_error:  # pragma: nocover
    logger.warning(import_error)

    DatabaseError = InterfaceError = StubError

    def connect(*args, **kwargs):
        """Connect stub."""
        raise NotImplementedError()


if TYPE_CHECKING:
    BaseMixin = Service  # pragma: nocover
else:
    BaseMixin = ABC


class Messages:  # pylint: disable=too-few-public-methods
    """Messages."""

    KEY = "mssql"

    CLOSE = dumps({"key": f"{KEY}.close"})
    COLUMN_PRIVILEGE = dumps({"key": f"{KEY}.warn", "value": "%s"})
    COMMIT = dumps({"key": f"{KEY}.commit"})
    END = dumps({"key": f"{KEY}.end"})
    EXTANT = dumps({"key": f"{KEY}.sql.extant", "value": "%s"})
    ON = dumps({"key": f"{KEY}.on"})
    OPEN = dumps({"key": f"{KEY}.open"})
    ROLLBACK = dumps({"key": f"{KEY}.rollback"})


class Persistor(Messages, BasePersistor):
    """Persistor."""

    YAML = "!mssql"

    @classmethod
    def mogrify(
        cls,
        cur,
        query: str,
        parameters: Any,
    ) -> bytes:
        """Safely mogrify parameters into query or fragment."""
        return _mssql.substitute_params(query, parameters)

    def __init__(
        self,
        *,
        port: int = 1433,
        schema: str = "dbo",
        **kwargs,
    ):
        """__init__."""
        super().__init__(port=port, schema=schema, **kwargs)

    @contextmanager
    def connect(self) -> Generator[Any, None, None]:
        """Connect."""
        # Replace return type with ContextManager[Any] when mypy is fixed.
        con = connect(
            server=self.host,
            user=self.username,
            password=self.password,
            database=self.database,
            port=self.port,
        )
        logger.info(self.OPEN)
        # TODO check semantics on pymssql connection and `with ... as`
        try:
            yield con
        finally:
            con.close()
            logger.info(self.CLOSE)

    def dry_run(
        self,
        parameters: dict[str, Any],
        exceptions=(DatabaseError, InterfaceError),
    ):
        """Dry run.

        Default exceptions provided by mssql driver
        to catch syntax errors before real run.
        """
        super().dry_run(parameters, exceptions)


class Mixin(BaseMixin):
    """Mixin."""

    @classmethod
    def yaml_types(cls) -> None:
        """Yaml types."""
        logger.debug("dsdk.mssql.Mixin.yaml_types()")
        Persistor.as_yaml_type()
        super().yaml_types()

    def __init__(self, *, mssql: Persistor | None = None, **kwargs):
        """__init__."""
        self.mssql = mssql
        super().__init__(**kwargs)

    def as_yaml(self) -> dict[str, Any]:
        """As yaml."""
        return {
            "mssql": self.mssql,
            **super().as_yaml(),
        }

```

### Command used

```shell
pylint --rcfile pyproject.toml src
```

### Pylint output

<details open>
    <summary>
        pylint crashed with a ``AstroidError`` and with the following stacktrace:
    </summary>

```python
Traceback (most recent call last):
  File "/Users/jlubken/projects/dsdk/.py39/lib/python3.9/site-packages/pylint/lint/pylinter.py", line 787, in _lint_file
    check_astroid_module(module)
  File "/Users/jlubken/projects/dsdk/.py39/lib/python3.9/site-packages/pylint/lint/pylinter.py", line 1016, in check_astroid_module
    retval = self._check_astroid_module(
  File "/Users/jlubken/projects/dsdk/.py39/lib/python3.9/site-packages/pylint/lint/pylinter.py", line 1068, in _check_astroid_module
    walker.walk(node)
  File "/Users/jlubken/projects/dsdk/.py39/lib/python3.9/site-packages/pylint/utils/ast_walker.py", line 94, in walk
    self.walk(child)
  File "/Users/jlubken/projects/dsdk/.py39/lib/python3.9/site-packages/pylint/utils/ast_walker.py", line 94, in walk
    self.walk(child)
  File "/Users/jlubken/projects/dsdk/.py39/lib/python3.9/site-packages/pylint/utils/ast_walker.py", line 91, in walk
    callback(astroid)
  File "/Users/jlubken/projects/dsdk/.py39/lib/python3.9/site-packages/pylint/checkers/classes/special_methods_checker.py", line 183, in visit_functiondef
    inferred = _safe_infer_call_result(node, node)
  File "/Users/jlubken/projects/dsdk/.py39/lib/python3.9/site-packages/pylint/checkers/classes/special_methods_checker.py", line 42, in _safe_infer_call_result
    value = next(inferit)
  File "/Users/jlubken/projects/dsdk/.py39/lib/python3.9/site-packages/astroid/nodes/scoped_nodes/scoped_nodes.py", line 1659, in infer_call_result
    yield from returnnode.value.infer(context)
  File "/Users/jlubken/projects/dsdk/.py39/lib/python3.9/site-packages/astroid/nodes/node_ng.py", line 170, in infer
    for i, result in enumerate(self._infer(context=context, **kwargs)):
  File "/Users/jlubken/projects/dsdk/.py39/lib/python3.9/site-packages/astroid/decorators.py", line 90, in inner
    yield next(generator)
  File "/Users/jlubken/projects/dsdk/.py39/lib/python3.9/site-packages/astroid/decorators.py", line 49, in wrapped
    for res in _func(node, context, **kwargs):
  File "/Users/jlubken/projects/dsdk/.py39/lib/python3.9/site-packages/astroid/nodes/node_classes.py", line 1761, in _infer
    for callee in self.func.infer(context):
  File "/Users/jlubken/projects/dsdk/.py39/lib/python3.9/site-packages/astroid/nodes/node_ng.py", line 170, in infer
    for i, result in enumerate(self._infer(context=context, **kwargs)):
  File "/Users/jlubken/projects/dsdk/.py39/lib/python3.9/site-packages/astroid/decorators.py", line 90, in inner
    yield next(generator)
  File "/Users/jlubken/projects/dsdk/.py39/lib/python3.9/site-packages/astroid/decorators.py", line 49, in wrapped
    for res in _func(node, context, **kwargs):
  File "/Users/jlubken/projects/dsdk/.py39/lib/python3.9/site-packages/astroid/nodes/node_classes.py", line 1092, in _infer_attribute
    for owner in node.expr.infer(context):
  File "/Users/jlubken/projects/dsdk/.py39/lib/python3.9/site-packages/astroid/nodes/node_ng.py", line 170, in infer
    for i, result in enumerate(self._infer(context=context, **kwargs)):
  File "/Users/jlubken/projects/dsdk/.py39/lib/python3.9/site-packages/astroid/decorators.py", line 90, in inner
    yield next(generator)
  File "/Users/jlubken/projects/dsdk/.py39/lib/python3.9/site-packages/astroid/decorators.py", line 49, in wrapped
    for res in _func(node, context, **kwargs):
  File "/Users/jlubken/projects/dsdk/.py39/lib/python3.9/site-packages/astroid/bases.py", line 177, in _infer_stmts
    for inf in stmt.infer(context=context):
  File "/Users/jlubken/projects/dsdk/.py39/lib/python3.9/site-packages/astroid/nodes/node_ng.py", line 170, in infer
    for i, result in enumerate(self._infer(context=context, **kwargs)):
  File "/Users/jlubken/projects/dsdk/.py39/lib/python3.9/site-packages/astroid/decorators.py", line 90, in inner
    yield next(generator)
  File "/Users/jlubken/projects/dsdk/.py39/lib/python3.9/site-packages/astroid/decorators.py", line 49, in wrapped
    for res in _func(node, context, **kwargs):
  File "/Users/jlubken/projects/dsdk/.py39/lib/python3.9/site-packages/astroid/nodes/node_classes.py", line 2875, in _infer
    stmts = module.getattr(name, ignore_locals=module is self.root())
  File "/Users/jlubken/projects/dsdk/.py39/lib/python3.9/site-packages/astroid/nodes/scoped_nodes/scoped_nodes.py", line 363, in getattr
    result = [self.import_module(name, relative_only=True)]
  File "/Users/jlubken/projects/dsdk/.py39/lib/python3.9/site-packages/astroid/nodes/scoped_nodes/scoped_nodes.py", line 463, in import_module
    return AstroidManager().ast_from_module_name(
  File "/Users/jlubken/projects/dsdk/.py39/lib/python3.9/site-packages/astroid/manager.py", line 250, in ast_from_module_name
    return self.ast_from_module(named_module, modname)
  File "/Users/jlubken/projects/dsdk/.py39/lib/python3.9/site-packages/astroid/manager.py", line 355, in ast_from_module
    return AstroidBuilder(self).module_build(module, modname)
  File "/Users/jlubken/projects/dsdk/.py39/lib/python3.9/site-packages/astroid/builder.py", line 105, in module_build
    node = self._manager.visit_transforms(node)
  File "/Users/jlubken/projects/dsdk/.py39/lib/python3.9/site-packages/astroid/manager.py", line 126, in visit_transforms
    return self._transform.visit(node)
  File "/Users/jlubken/projects/dsdk/.py39/lib/python3.9/site-packages/astroid/transforms.py", line 158, in visit
    return self._visit(node)
  File "/Users/jlubken/projects/dsdk/.py39/lib/python3.9/site-packages/astroid/transforms.py", line 82, in _visit
    visited = self._visit_generic(value)
  File "/Users/jlubken/projects/dsdk/.py39/lib/python3.9/site-packages/astroid/transforms.py", line 108, in _visit_generic
    return [self._visit_generic(child) for child in node]
  File "/Users/jlubken/projects/dsdk/.py39/lib/python3.9/site-packages/astroid/transforms.py", line 108, in <listcomp>
    return [self._visit_generic(child) for child in node]
  File "/Users/jlubken/projects/dsdk/.py39/lib/python3.9/site-packages/astroid/transforms.py", line 115, in _visit_generic
    return self._visit(node)
  File "/Users/jlubken/projects/dsdk/.py39/lib/python3.9/site-packages/astroid/transforms.py", line 85, in _visit
    return self._transform(node)
  File "/Users/jlubken/projects/dsdk/.py39/lib/python3.9/site-packages/astroid/transforms.py", line 66, in _transform
    if predicate is None or predicate(node):
  File "/Users/jlubken/projects/dsdk/.py39/lib/python3.9/site-packages/astroid/brain/brain_namedtuple_enum.py", line 647, in _is_enum_subclass
    return cls.is_subtype_of("enum.Enum")
  File "/Users/jlubken/projects/dsdk/.py39/lib/python3.9/site-packages/astroid/nodes/scoped_nodes/scoped_nodes.py", line 2080, in is_subtype_of
    return any(anc.qname() == type_name for anc in self.ancestors(context=context))
  File "/Users/jlubken/projects/dsdk/.py39/lib/python3.9/site-packages/astroid/nodes/scoped_nodes/scoped_nodes.py", line 2080, in <genexpr>
    return any(anc.qname() == type_name for anc in self.ancestors(context=context))
  File "/Users/jlubken/projects/dsdk/.py39/lib/python3.9/site-packages/astroid/nodes/scoped_nodes/scoped_nodes.py", line 2255, in ancestors
    for baseobj in stmt.infer(context):
  File "/Users/jlubken/projects/dsdk/.py39/lib/python3.9/site-packages/astroid/nodes/node_ng.py", line 170, in infer
    for i, result in enumerate(self._infer(context=context, **kwargs)):
  File "/Users/jlubken/projects/dsdk/.py39/lib/python3.9/site-packages/astroid/decorators.py", line 90, in inner
    yield next(generator)
  File "/Users/jlubken/projects/dsdk/.py39/lib/python3.9/site-packages/astroid/decorators.py", line 49, in wrapped
    for res in _func(node, context, **kwargs):
  File "/Users/jlubken/projects/dsdk/.py39/lib/python3.9/site-packages/astroid/nodes/node_classes.py", line 586, in _infer
    frame, stmts = self.lookup(self.name)
  File "/Users/jlubken/projects/dsdk/.py39/lib/python3.9/site-packages/astroid/nodes/_base_nodes.py", line 277, in lookup
    return self.scope().scope_lookup(self, name)
  File "/Users/jlubken/projects/dsdk/.py39/lib/python3.9/site-packages/astroid/nodes/scoped_nodes/scoped_nodes.py", line 2221, in scope_lookup
    return frame._scope_lookup(node, name, offset)
  File "/Users/jlubken/projects/dsdk/.py39/lib/python3.9/site-packages/astroid/nodes/scoped_nodes/mixin.py", line 80, in _scope_lookup
    stmts = _filter_stmts(node, self.locals[name], self, offset)
  File "/Users/jlubken/projects/dsdk/.py39/lib/python3.9/site-packages/astroid/filter_statements.py", line 110, in _filter_stmts
    statements = _get_filtered_node_statements(base_node, stmts)
  File "/Users/jlubken/projects/dsdk/.py39/lib/python3.9/site-packages/astroid/filter_statements.py", line 25, in _get_filtered_node_statements
    statements = [(node, node.statement()) for node in stmt_nodes]
  File "/Users/jlubken/projects/dsdk/.py39/lib/python3.9/site-packages/astroid/filter_statements.py", line 25, in <listcomp>
    statements = [(node, node.statement()) for node in stmt_nodes]
  File "/Users/jlubken/projects/dsdk/.py39/lib/python3.9/site-packages/astroid/nodes/scoped_nodes/scoped_nodes.py", line 414, in statement
    raise StatementMissing(target=self)
astroid.exceptions.StatementMissing: Statement not found on <Module.datetime l.0 at 0x1161a5a30>

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/jlubken/projects/dsdk/.py39/lib/python3.9/site-packages/pylint/lint/pylinter.py", line 751, in _lint_files
    self._lint_file(fileitem, module, check_astroid_module)
  File "/Users/jlubken/projects/dsdk/.py39/lib/python3.9/site-packages/pylint/lint/pylinter.py", line 789, in _lint_file
    raise astroid.AstroidError from e
astroid.exceptions.AstroidError

```

</details>

### Expected behavior

No crash.

### Pylint version

```shell
pylint 3.2.6
astroid 3.2.4
Python 3.9.19 (main, Mar 19 2024, 16:08:27) 
[Clang 15.0.0 (clang-1500.3.9.4)]
```

### OS / Environment

darwin (Darwin)

### Additional dependencies

pymssql               2.3.0
types-pymssql         2.1.0

pip install ".[dev]"

Public project here: https://github.com/pennsignals/dsdk. Same error occurs with multiple python version. I'm adding 3.12 support in a branch update_python312. Same error occurs with both 3.9 and 3.12 virtual environments.

**Comment by jlubken** [comment]
Public project here: https://github.com/pennsignals/dsdk. Same error occurs with multiple python version. I'm attemptng to add 3.12 support in a branch update_python312.

**Comment by jlubken** [comment]
Some of the other tickets mentioned shadowing builtin names, so I will check for that this week.

**Comment by jlubken** [comment]
I updated the QA toolchain to the latest in pre-commit config while ensuring that the nbqa tools version matched.

I removed an exclusion for mypy in pyproject.toml that matched the crash, but I think that this is unrelated to astroid and pylint.

I suspect that tools like pylint installed with 'pip install ".[dev]"' were simply newer than what was used by pre-commit.
