### ISSUE TITLE
Crash F0002 (astroid-error)

### ISSUE THREAD

**Issue by anya-czayyx** [pylint-dev/pylint#9965]
### Command used

```shell
pylint a.py
```

### Pylint output

<details open>
    <summary>
        pylint crashed with a ``AstroidError`` and with the following stacktrace:
    </summary>

```python
Traceback (most recent call last):
  File "C:\Users\yvonn\PycharmProjects\CSC148F\.venv\Lib\site-packages\pylint\lint\pylinter.py", line 789, in _lint_file
    check_astroid_module(module)
  File "C:\Users\yvonn\PycharmProjects\CSC148F\.venv\Lib\site-packages\pylint\lint\pylinter.py", line 1018, in check_astroid_module
    retval = self._check_astroid_module(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\yvonn\PycharmProjects\CSC148F\.venv\Lib\site-packages\pylint\lint\pylinter.py", line 1070, in _check_astroid_module
    walker.walk(node)
  File "C:\Users\yvonn\PycharmProjects\CSC148F\.venv\Lib\site-packages\pylint\utils\ast_walker.py", line 94, in walk
    self.walk(child)
  File "C:\Users\yvonn\PycharmProjects\CSC148F\.venv\Lib\site-packages\pylint\utils\ast_walker.py", line 91, in walk
    callback(astroid)
  File "C:\Users\yvonn\PycharmProjects\CSC148F\.venv\Lib\site-packages\python_ta\checkers\redundant_assignment_checker.py", line 63, in visit_functiondef
    self._analyze(node)
  File "C:\Users\yvonn\PycharmProjects\CSC148F\.venv\Lib\site-packages\python_ta\checkers\redundant_assignment_checker.py", line 76, in _analyze
    cfg.start = node.cfg_block
                ^^^^^^^^^^^^^^
AttributeError: 'FunctionDef' object has no attribute 'cfg_block'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\yvonn\PycharmProjects\CSC148F\.venv\Lib\site-packages\pylint\lint\pylinter.py", line 753, in _lint_files
    self._lint_file(fileitem, module, check_astroid_module)
  File "C:\Users\yvonn\PycharmProjects\CSC148F\.venv\Lib\site-packages\pylint\lint\pylinter.py", line 791, in _lint_file
    raise astroid.AstroidError from e
astroid.exceptions.AstroidError

```

</details>

### Expected behavior

No crash.

### Pylint version

```shell
pylint 3.2.7
astroid 3.2.4
Python 3.12.3 (tags/v3.12.3:f6650f9, Apr  9 2024, 14:05:25) [MSC v.1938 64 bit (AMD64)]
```

### OS / Environment

win32 (Windows)

**Comment by jacobtylerwalls** [comment]
Please report this issue to the maintainer of `python-ta`.

**Comment by Pierre-Sassoulas** [comment]
Ha, we might want to detect if the crashing code is external to pylint because right now we're asking users to open issue here in our crash template when an external plugin fail.
